### ISSUE TITLE
AutoFill-Target list unreadable 

### ISSUE THREAD

**Issue by Cris--** [PhilippC/keepass2android#1388] opened 2020-08-26 13:11 UTC
Hi,

the list of AutoFill-Targets with KeePass dark theme is unreadable (black text on black background). If i switch to bright theme all fine.

**Comment by WebworkrNet** [comment] 2021-08-09 16:24
I can confirm that.

**Comment by WebworkrNet** [comment] 2022-01-01 08:44
Duplicate of #1175

**Closed** 2022-01-05 11:53 UTC
