### ISSUE TITLE
[FEAT] keyboard: only show TOTP button, hide OTP button

### ISSUE THREAD

**Issue by pokanoka** [PhilippC/keepass2android#2394] opened 2023-08-05 10:10 UTC
When OTP is configured for the entry, keepass Android keyboard shows both OTP and TOTP buttons. It's confusing. Moreover, pressing the OTP  would "disclose" secret which user would not normally want to change or output anywhere.

My proposition is to hide the "OTP" button. The "TOTP" is the one user wants in about 100% cases.

**Comment by PhilippC** [comment] 2024-01-03 08:28
duplicate of #2033

**Closed by PhilippC** 2024-01-03 08:28 UTC
Labels: enhancement
