### ISSUE TITLE
"maximum request length supported is 4MB" error when synchronising files

### ISSUE THREAD

**Issue by me-and** [PhilippC/keepass2android#1306] opened 2020-07-01 12:31 UTC
Hi,

I'm using 1.08b-pre2, and I'm seeing the error in the below screenshot when I try to merge via Menu > "Synchronize database...". There's a follow-up toast message that implies the merge was successful, but when I retry the merge again it claims there are still unsyncronised changes.

This error started appearing recently, although I can't give you an exact date, and I can't confirm it correlated with taking the 1.08b-pre2 version. I am fairly confident that the size of my password database (around 10MB) hasn't significantly increased recently.

I'm using OneDrive to store the password database.

![Screenshot_20200701-121748__01](https://user-images.githubusercontent.com/1397507/86243676-b12d8a00-bb9e-11ea-9945-353b5a156412.jpg)

**Comment by me-and** [comment] 2020-07-05 10:58
Just checked: I'm getting the same error (with slightly less verbose logs) on the current mainline release, 1.07b-r0.

**Comment by PhilippC** [comment] 2020-07-06 07:05
duplicate of https://github.com/PhilippC/keepass2android/issues/1036

**Closed by PhilippC** 2020-07-06 07:05 UTC
