### ISSUE TITLE
Fingerprint unlock no longer working

### ISSUE THREAD

**Issue by SonicMetal15** [PhilippC/keepass2android#239] opened 2018-02-05 02:53 UTC
Please see included screenshots.  There is now an orange alert circle with an exclamation point indicating an error with the fingerprint unlock feature.  It was working before perfectly fine for me but I am not what broke it.  Upon clicking on the orange circle, there is a long log of Java runtime exception errors detailing the exception raised; I have included a snippet of it in the second screenshot.  

Any idea how to fix this?  I have already tried deleting the app cache and uninstalling the app, then reinstalling it again to no avail (still same error).  
![screenshot_20180204-184234](https://user-images.githubusercontent.com/28214658/35786530-a5f60ac0-09dc-11e8-807b-e081a40f25f3.jpg)
![screenshot_20180204-184251](https://user-images.githubusercontent.com/28214658/35786531-a62011da-09dc-11e8-8ea2-a6958ad7755c.jpg)

**Comment by PhilippC** [comment] 2018-02-08 08:24
please log in with the master password, go to settings -> db settings -> unlock with fingerprint and re-enable fingerprint unlock.
duplicate of #37

**Closed by PhilippC** 2018-02-08 08:24 UTC

**Comment by AndriiK417** [comment] 2020-01-17 10:30
> будь ласка, увійдіть із головним паролем, перейдіть до налаштувань -> налаштування db -> розблокуйте з відбитками пальців та повторно увімкніть розблокування відбитка пальця.
> дублікат [№37](https://github.com/PhilippC/keepass2android/issues/37)

I've tried that before, don't working.
