### ISSUE TITLE
pCloud Login does not work

### ISSUE THREAD

**Issue by DiggiMorris** [PhilippC/keepass2android#1257] opened 2020-05-23 14:18 UTC
Hi, I freshly installed pCloud on my phone. The login to open a database from pCloud does not work. The waiting circle when pressing Login stays for hours without logging in.

This is NOT about the correct folders in pCloud, which are necessary (applications/...)

By the way: The popup for pCloud shows a wrong folder name with a typo: it states to have the folder "application**SS**/..." I am pretty sure the **double s** is wrong. :)

**Comment by majjhima** [comment] 2020-05-24 06:29
I am also experiencing the same problem on a Samsung Note 10+.  I have tried wiping userdata and cache, but login continues to hang.  Login with Google also is not supported.  This did work on My Note 10+ last year.

**Comment by lducerf** [comment] 2020-05-31 15:44
Same problem on a Pixel XL / Android 10: infinite waiting circle loop (while keepass file is stored in Applications/Keepass2Android folder)

**Comment by cbellgit** [comment] 2020-06-02 02:22
Same here on Galexy Tab A. Interestingly it worked on a Pixel 2 but that was about two weeks ago.

**Comment by GhengisKoan** [comment] 2020-06-09 17:23
Confirming identical issue on Pixel 3 XL Android version 10.

**Comment by THmstr2017** [comment] 2020-06-17 11:48
Same issue on a new Samsung S10.

Xiaomi MIX2S device that was working prior, is no longer working for new auth.

**Comment by PhilippC** [comment] 2020-06-17 18:55
@gilbsgilbs any thought on this?

**Comment by typhoon2099** [comment] 2020-06-27 15:16
Same issue here on a Xperia Z3/LineageOS 16.1

**Comment by MisterY** [comment] 2020-07-06 10:25
The workaround would be to use WebDAV.

**Comment by koehlf** [comment] 2020-07-13 14:30
Same issue here on a Samsung S9... 
Already contacted the pcloud support, but they their (not very useful) answer was that they cannot help since they do not officially support pcloud...

**Comment by svprdga** [comment] 2020-07-14 12:03
Same issue here on a Galaxy A3 SM-A230FL

**Comment by k-dx** [comment] 2020-07-15 14:43
Same issue on Xperia Z5 E6653 with Android 7.1.1 :(

**Comment by irkallacz** [comment] 2020-07-16 17:31
Same issue on CAT S52 with Android 9

**Comment by zoltanmaric** [comment] 2020-07-26 07:10
I'm experiencing the same on a Xiaomi Mi A2 (Android 10) and Nexus 5x (Android 8.1) 😟

**Comment by zoltanmaric** [comment] 2020-07-27 18:52
By the way, you don't need a pCloud account to test this. Entering any valid email address and any password will reproduce the bug, where clicking on the log in button just shows an infinite spinner and doesn't show any errors.

@gilbsgilbs I saw that you originally implemented support for pCloud in #523. Would you perhaps have time to look into this issue, pretty please?

**Comment by gilbsgilbs** [comment] 2020-07-27 19:48
Hi! I'm so sorry I have literally zero time to spend on FOSS projects right now as I have to deal with other personal issues 😥.

I have no idea where this issue may come from. Given that it used to work and that we didn't change the implementation (did we?), it may very well come from pCloud themselves but maybe the first thing to do is check whether there were any updates to their Android library and java SDK recently and if so update them and hope for the best. Another idea would be to check if using OAuth tokens from another account would work (I don't know if KP2A still uses mine, but given that I had a commercial dispute with pCloud a few months ago, I wouldn't be surprised should they put my account under some sort of greylist).

As a temporary workaround, I've contributed a SAF provider for rcx recently but unfortunatly it hasn't been merged yet: https://github.com/x0b/rcx/pull/76. This may actually fill your use-case in a indirect way (if you dare opening android studio and compile my branch by yourself).

**Comment by zoltanmaric** [comment] 2020-07-27 20:29
Alright @gilbsgilbs, thanks for all the helpful info, and of course I can understand you having more important issues to deal with.

**Comment by agofa** [comment] 2020-09-24 15:38
Only to report. Same issue here. I just tried to access to pcloud using a fresh installation on a Lenovo Tablet, without success: endless circle

An already configured mobile phone (Motorola X4) has no access issues

**Comment by jonasW3F** [comment] 2020-10-15 07:47
same here

**Comment by Ralph-67** [comment] 2020-10-26 18:22
Same here, Oppo Find X2 Pro - It has worked while my data have been hosted in USA - After moving them to Europe i have again the same problem - Trying to connect via webdav gives an "unexpected response, error 401 unauthorized" ...

**Comment by jonasW3F** [comment] 2020-10-27 07:39
@Ralph-67 That's a good hint, I remember that the support told me that the login in the chrome extension does not yet support EU servers. It's probably the same issue which leads to block logins from Keepass2Android.

Can somebody with a server location in the US comment on whether the login works for them?

**Comment by svprdga** [comment] 2020-10-27 08:17
I have my data in US servers and I can login through webdav without any problem.

**Comment by jonasW3F** [comment] 2020-10-27 16:51
> I have my data in US servers and I can login through webdav without any problem.

But can you link Keepass2Android through the predefined pcloud login?

**Comment by svprdga** [comment] 2020-10-27 17:59
No, I configured via webdav:

1. Click in open database
2. Select HTTP (WebDav)
3. Set URL to http://webdav.pcloud.com/route/to/your/kdb/file
4. Set your username and password
5. Submit values and you should be able to access to your PCloud storage

**Comment by jonasW3F** [comment] 2020-10-27 18:36
> No, I configured it via webdav:
> 
> 1. Click in open database
> 2. Select HTTP (WebDav)
> 3. Set URL to http://webdav.pcloud.com/route/to/your/kdb/file
> 4. Set your username and password
> 5. Submit values and you should be able to access to your PCloud storage

Yes, I understand, but I was wondering whether the "standard" pcloud login from Keepass2Android works for you and US servers. Because as you see in this issue, many people have problems with it. Could you try to login from the pcloud shortcut in Keepass2Android?

**Comment by svprdga** [comment] 2020-10-28 08:06
I tried and I couldn't connect the 'standard' way, same as all of you...that's why I'm connecting via webdav.

**Comment by jonasW3F** [comment] 2020-10-28 14:07
> I tried and I couldn't connect the 'standard' way, same as all of you...that's why I'm connecting via webdav.

Thanks! This hopefully helps some people to figure out where the problem is :)

**Comment by edrik** [comment] 2020-10-31 20:45
Having the same problem 😞 

A somewhat wild guess, but could it be related to the auth flow being done with the embedded web view and not a separate browser. At least the other pCloud login options like Apple, Facebook and Google are complaining about the user agent 🤔

**Comment by edrik** [comment] 2020-11-03 20:21
Might add that the webdav address for Europe is https://ewebdav.pcloud.com/
If you need a workaround.

Would really like to help get this resolve but unfortunately Android development is not my area of expertise. Webdav works but it's really note something pCloud advertice as officially supported, so the method in question would still be preferable.

**Comment by lvhoang1** [comment] 2020-12-15 12:58
Using https://ewebdav.pcloud.com no longer works for me.

Is there any other way to use Pcloud?

What a shame :(

**Comment by typhoon2099** [comment] 2020-12-15 13:10
You should be able to use https://webdav.pcloud.com/, that's what I'm currently using.

**Comment by lvhoang1** [comment] 2020-12-15 13:25
Thanks @typhoon2099 , however I tried https://webdav.pcloud.com/ and I still have the same error 

Just making sure I am doing ti right, I have chosen both "HTTP Webdav" and "HTTPS Webdav".... is that correct?


![image](https://user-images.githubusercontent.com/76050328/102220558-46200780-3ee1-11eb-944b-06dd5ac8ba8a.png)


it says something about URL unauthorized.....



![image](https://user-images.githubusercontent.com/76050328/102220272-e295da00-3ee0-11eb-926b-b3229839859f.png)

**Comment by typhoon2099** [comment] 2020-12-15 14:07
It shouls be HTTPS Webdav as far as I'm aware. The 401 Unauthorised error looks like your authentication details are incorrect. I'd check your username/password to be sure.

**Comment by lvhoang1** [comment] 2020-12-15 14:21
Thank you for your advice,

I did check my password and username, under WEBDAV HTTPS, and really I have the same issue. I am able to connect to Pcloud drive app without issues though.

Oh well :(

**Comment by svprdga** [comment] 2020-12-16 08:04
For me, it's only working with HTTP. Also, take into account that if you have enabled 2FA in your account, connection via webdav won't work.

**Comment by lvhoang1** [comment] 2020-12-16 13:35
For me, even disabling 2FA does not work.
However, I feel this is lowering my safety level, so even if it worked i wouldnt be ready to do it.

I hope there will be either a plug in or a fix for this soon.

**Comment by PhilippC** [comment] 2020-12-24 07:24
please react 👍 on https://github.com/pCloud/pcloud-sdk-java/issues/8 if you are facing this issue with KP2A. Maybe this motivates the pCloud guys to take a look!

**Comment by oha-x4nd1** [comment] 2020-12-27 10:25
> 
> 
> please react 👍 on [pCloud/pcloud-sdk-java#8](https://github.com/pCloud/pcloud-sdk-java/issues/8) if you are facing this issue with KP2A. Maybe this motivates the pCloud guys to take a look!

Done.

Also for information: After changing my 2TB Plan from US to EU Servers, i have the same problem

**Comment by zoltanmaric** [comment] 2020-12-28 18:20
I managed to connect via HTTPS/WebDAV using https://webdav.pcloud.com/ from Europe while connected to a VPN server in the US. I didn't try connecting while **not** connected to VPN, so I'm not sure whether that made any difference to be honest.

**Comment by lvhoang1** [comment] 2020-12-28 21:58
> I managed to connect via HTTPS/WebDAV using https://webdav.pcloud.com/ from Europe while connected to a VPN server in the US. I didn't try connecting while **not** connected to VPN, so I'm not sure whether that made any difference to be honest.

My data region is EU. WHats yours?
Let me try with VPN and revert. Last time I did (without VPN though) it didnt work.

**Comment by zoltanmaric** [comment] 2020-12-28 22:31
> My data region is EU. WHats yours?
Oh dang, I just checked, and it's US. I assumed it was going to be EU since I'm in the EU :/

**Comment by lvhoang1** [comment] 2020-12-31 15:54
ok so, from all the threads I have read and tests I have made, I have come to the following conclusion: 

Pcloud mini app button does not work for anyone.

US data region clients can use https://webdav.pcloud.com/
But EU Data region clients cannot use webdav, whether HTTP or HTTPS.

**Comment by edrik** [comment] 2020-12-31 18:17
@lvhoang1 EU Data region clients can use https://ewebdav.pcloud.com/

Note the `e` prefix in the sub domain.

**Comment by lvhoang1** [comment] 2020-12-31 18:38
Well I have tried it and it does not work for me.
Maybe because of 2FA.

**Comment by edrik** [comment] 2020-12-31 18:55
True, if you enable 2FA you can't apparently use webdav 😞 

But aside from that webdav/ewebdav works.

**Comment by oha-x4nd1** [comment] 2021-01-01 11:07
> 
> 
> please react 👍 on [pCloud/pcloud-sdk-java#8](https://github.com/pCloud/pcloud-sdk-java/issues/8) if you are facing this issue with KP2A. Maybe this motivates the pCloud guys to take a look!

I also wrote the pCloud Support. **Answer (in German):**
Es scheint, dass KeePass die EU-Konten nicht berücksichtigt hat, um mit der App arbeiten zu können.
Dieses Problem liegt nicht auf unserer Seite, daher wenden Sie sich bitte an das Team des Drittanbieter-Tools, um weitere Unterstützung in dieser Angelegenheit zu erhalten.

**Comment by lvhoang1** [comment] 2021-01-01 11:30
So they are basically saying this is the Keepass' problem, not theirs.... :(
It looks like Pcloud does not care about this

**Comment by PhilippC** [comment] 2021-01-01 19:56
@oha-x4nd1 can you ask them how I can "consider EU accounts"?
I don't see anything in the developer settings that would affect this?

![grafik](https://user-images.githubusercontent.com/5421734/103445407-ce3d3580-4c73-11eb-9da5-771e3fecc9a0.png)

**Comment by agofa** [comment] 2021-01-01 21:00
> I also wrote the pCloud Support. **Answer (in German):**

I'm a pcloud subscriber too
I wrote to the support and I'm waiting for the reply, I let you know

**Comment by agofa** [comment] 2021-01-04 14:26
> 
> 
> > I also wrote the pCloud Support. **Answer (in German):**
> 
> I'm a pcloud subscriber too
> I wrote to the support and I'm waiting for the reply, I let you know

Same answer, but in English :-(

_Since Keepass2android is a third party application, it hasn't been tested with pCloud.
We are not responsible for the errors of the other apps. Please contact the Keepass2android developers regarding the issues._

**Comment by lvhoang1** [comment] 2021-01-04 15:04
I've had the same exact answer from Pcloud Support.
They don't want to troubleshoot this issue. I did ask specifically about EU vs USA data region and they gave me the same copy paste.

Since Keepass2android is a third party application, it hasn't been tested with pCloud.
We are not responsible for the errors of the other apps. Please contact the Keepass2android developers regarding the issues.

**Comment by oha-x4nd1** [comment] 2021-01-04 17:22
> @oha-x4nd1 can you ask them how I can "consider EU accounts"?
> I don't see anything in the developer settings that would affect this?

@PhilippC Replies from pCloud:

**German:**
Ich habe mich mit unserem Entwicklerteam in Verbindung gesetzt, um zu überprüfen, ob von unserer Seite noch etwas getan werden kann, um das Problem zu lösen.
In der Zwischenzeit versuchen Sie bitte, die Anwendung neu zu installieren und sehen Sie, ob dies hilft.

Wäre es möglich, dass die KeyPass-Entwickler uns anschreiben, damit wir sie über die richtige API beraten können?

Bitte stellen Sie diese Dokumentation dem Keepass-Team zur Verfügung, damit es die entsprechenden Änderungen für die EU-Konten vornehmen kann.
https://docs.pcloud.com/methods/oauth_2.0/authorize.html


**English (Translator):**
I got in touch with our development team to see if anything could be done on our part to resolve the problem.
In the meantime, please try reinstalling the application and see if that helps.

Would it be possible for the KeyPass developers to write to us so that we can advise them on the right API?

Please provide this documentation to the Keepass team so that they can make the appropriate changes for the EU accounts.
https://docs.pcloud.com/methods/oauth_2.0/authorize.html

**Closed** 2021-01-08 05:38 UTC

**Comment by PhilippC** [comment] 2021-01-08 05:43
thanks for supporting me with this! After pCloud updated the SDK, I integrated it and it is now working also for EU data location. This fix will be included in 1.08d-r1 (should be available soon through https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by lvhoang1** [comment] 2021-01-08 07:30
> thanks for supporting me with this! After pCloud updated the SDK, I integrated it and it is now working also for EU data location. This fix will be included in 1.08d-r1 (should be available soon through https://play.google.com/apps/testing/keepass2android.keepass2android)

Oh wow thank you so much!
Would you know if 2FA can be activated or not? No problem of it has to be kept off for Pcloud.

Anyway i can't wait for the update 😊

**Comment by oha-x4nd1** [comment] 2021-01-08 07:34
@lvhoang1 2FA works :-)

**Comment by lvhoang1** [comment] 2021-01-08 07:41
Amazing!!!! Cheers man

**Comment by Ralph-67** [comment] 2021-01-08 11:03
Well done Philipp, it now also works for me - Thank you very much!

**Comment by agofa** [comment] 2021-01-08 11:18
Many many thanks: it works! :-)

**Comment by lvhoang1** [comment] 2021-01-10 23:54
Amazing work Philip!
Thank you so much.
Can confirm it works beautifully.

**Comment by GhengisKoan** [comment] 2021-01-11 02:41
The update has fully restored the pCloud integration feature for me as well.
Your work on this issue is truly appreciated, Philip.
Thanks!

**Comment by maddes-b** [comment] 2021-01-14 20:11
Just experienced the same issue and 1.08d-rc1 solved the issue for me (non-2FA usage currently). Thanks for your great support (earned you some more beers :) ).

**Comment by maddes-b** [comment] 2021-02-22 18:55
Went from beta back to release 1.08d and get again "authentication failed". Either the build is broken or pCloud just changed something while I switched. Will test beta again tonight.

**Comment by maddes-b** [comment] 2021-02-22 19:06
Beta also does not work (anymore) for me. I see that the [pCloud client][1] was updated 2 days ago on my phone. Coincendence?

[1]: https://play.google.com/store/apps/details?id=com.pcloud.pcloud

**Comment by maddes-b** [comment] 2021-02-22 19:46
Found a solution. Whenever I deinstall and reinstall any version of Keepass 2 Android I have to clear K2A from pCloud's "Linked Apps": Web Interface only > Settings > Linked Apps.
After this I can re-login and re-allow K2A.

**Comment by Mic75** [comment] 2021-02-22 20:25
@maddes-b I removed both K2A and pCloud client from my phone and reinstalled both. I am still having the same issue as you describe (pCloud login page blinking and "Authentifcation failed" message).

I don' see K2A in the Linked Apps though.

Any ideas?

**Comment by Darkilen** [comment] 2021-02-25 19:02
I am having the same issue as you ("Session expired, please login" message and infinite loading on the login button)
I just install pCloud today and I had K2A for years, with dropbox connection.

**Comment by PhilippC** [comment] 2021-03-01 20:20
@maddes-b @Mic75 If you see the "Authentication failed." toast, please switch to 1.09a-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android) - it will appear there once, but you can then try again and it should work again.

@Darkilen can you please open a different issue for this?

**Comment by Mic75** [comment] 2021-03-01 20:36
@PhilippC This is still failing for me. After desinstalling K2A and reinstalling,  I manage to have the pCloud login page. The entering my credential to login I got the Auth failed toaster. Now, if I try to open my DB via the pCloud I am getting the "Auth failed" toaster with blinking pCloud login page (same as before).

I am on the pCloud European server.
Android version is: 10

**Comment by PhilippC** [comment] 2021-03-02 19:45
do you know how to create a logcat?

**Comment by Mic75** [comment] 2021-03-03 13:49
@PhilippC nop, but I can give it a try.

**Comment by PhilippC** [comment] 2021-03-03 18:27
just filter for "KP2A"

**Comment by kminkov** [comment] 2021-03-04 20:50
I also cannot get it to work even when I did all the steps described above by @maddes-b . 
The pCloud login screen blinks and the "Authentication failed" toast is shown with version 1.09a-pre1.
I noticed that if I click super fast on the sign in link in pCloud login screen "Authentication failed" is not shown and I can enter my credentials. But when I click sign in it is shown again and still cannot connect. 

Xiaomi mi 6
Android 9

**Comment by Mic75** [comment] 2021-03-06 02:20
@PhilippC  gotcha, I'll try to send you the dump this weekend.

**Comment by robertour** [comment] 2021-03-06 18:37
I am experiencing the same problem as @kminkov. If I quickly click int he exact Sign in spot, then it doesn't loop back to the screen with "Open file...". However, it fails once I put the credentials: 

Xiaomi Mi A2 (Android 10)

**Comment by Mic75** [comment] 2021-03-07 16:47
@PhilippC Logcat sent to playstore developer mail account.

**Comment by ldecoster** [comment] 2021-03-07 21:09
Hi, I am experiencing the same behaviour as @Mic75 , I just enabled 2FA on my pCloud account and when I'm trying to open my Keepass database from the pCloud app the toast "Authentication failed" is popping up and I can only see the pCloud login page for one second

Android 10 with files stored in the USA

**Comment by vallejoboy** [comment] 2021-03-13 03:37
Same problem as above but I was able to open the kdbx file directly from the pcloud app using Keepass2Android(1.09a-pre1)

Note20 Ultra
Android 11 with files in the US

**Comment by amplejoe** [comment] 2021-11-25 18:07
Hi! Thank you so much for all your effort. Unfortunately none of the suggestions work for me - the login circle keeps spinning indefinitely. I've tried:
Phone: Asus Zenfone 8 with Android 11 (files in US, but play store is set to EU)

- deleting my pcloud K2A link
- login using 1.09a-r3
- login using 1.09b-r0
