### ISSUE TITLE
Keepass2Android can't open a database that is shared from another Google Drive account

### ISSUE THREAD

**Issue by chordchaos** [PhilippC/keepass2android#1469] opened 2020-11-19 03:22 UTC
If the database is shared from another Google Drive account, the file is not able to be opened by Keepass2Android. The app should either follow the new shortcut method recently introduced in Google Drive, or allow the user to navigate to the "Shared with me" portion of Google Drive. Based on the error, it looks like it just attempts to open the 0 byte shortcut file.

1. UserA shares database with UserB on Google Drive
1. UserB moves the database to "My Drive" (creates shortcut)
1. UserB opens "database" via Google Drive in the Keepass2Android app
1. Keepass2Android fails with an error reporting the database header is corrupt

**Comment by tilowiklundSensmetry** [comment] 2020-11-25 16:40
The exact error message is "An error occured: The file header is corrupted. Less data than expected could be read from the file."

**Comment by davemecha** [comment] 2020-11-27 13:43
The shortcuts in google drive are like windows shortcuts. The App should implement support for linked files. It's not even a workaround to share a folder with a `.kdbx` file because the file browser is not able to follow the links. 

For business-accounts (GSuite / Google Workspace) there might be a workaround by placing the original file in a shared drive bud I did not test this. When tested I'll give some feedback.

**Comment by Mi-Mey** [comment] 2021-01-19 09:24
Hi All, same issue.  Solution appreciated.

**Comment by PhilippC** [comment] 2021-01-19 18:19
duplicate of https://github.com/PhilippC/keepass2android/issues/189. A workaround is to use a tool like FolderSync to get access to the file.

**Closed by PhilippC** 2021-01-19 18:19 UTC
