### ISSUE TITLE
keepass keyboard on opening app

### ISSUE THREAD

**Issue by basbakker** [PhilippC/keepass2android#321] opened 2018-03-30 10:20 UTC
Can you make it that when you open the app it will change to the keepass keyboard? So I can enter my password in the 'safe' keyboard?

Atm it only switches when you select a entry.

(I'm using the keyboard swap plugin)

**Comment by basbakker** [comment] 2018-04-03 09:49
awesome! can't wait for it. great work.

**Comment by DJCrashdummy** [comment] 2018-07-19 09:24
this sounds like a reasonable feature request, but please just optional!
i use a FOSS keyboard (which i'm pretty sure is safe) on an FOSS AOSP-fork so i hardly need the KP2A-keyboard. beside that i setup KP2A to only use "the small KP2A-keyboard" (which wouldn't make sense in this case) as a fallback.

**Comment by PhilippC** [comment] 2018-09-12 02:54
duplicate of #67

**Closed by PhilippC** 2018-09-12 02:54 UTC
