### ISSUE TITLE
[FEAT] Please put this on the F-droid store and please implement proton drive support

### ISSUE THREAD

**Issue by NastyFlytrap** [PhilippC/keepass2android#2424] opened 2023-09-21 00:18 UTC
As title says.

I really like this, but it not being on the F-Droid store is a real bummer, and i also wish to use this with protondrive aswell

**Comment by PhilippC** [comment] 2023-09-25 07:08
duplicate of https://github.com/PhilippC/keepass2android/issues/38

**Closed by PhilippC** 2023-09-25 07:08 UTC
Labels: enhancement
