### ISSUE TITLE
Search for login not opening in Android Pie

### ISSUE THREAD

**Issue by fantini29** [PhilippC/keepass2android#496] opened 2018-08-10 14:55 UTC
After you switch to keepass keyboard I normally use the keepass key on the bottom left to open keepass and find the entry for the app. This had stopped working on Android Pie. If I long press the key it opens the keyboard settings or keyboard switch icons

**Comment by scwalla** [comment] 2018-08-11 18:16
Confirm that I also have this problem on pixel 2 XL running android 9 Pie.

**Comment by PhilippC** [comment] 2018-08-15 02:04
duplicate of https://github.com/PhilippC/keepass2android/issues/377

**Closed by PhilippC** 2018-08-15 02:04 UTC
