### ISSUE TITLE
Autofill Info undeletable

### ISSUE THREAD

**Issue by carsten-engelke** [PhilippC/keepass2android#323] opened 2018-04-02 11:58 UTC
The App shows a big info bar at the bottom of main screen when the autofill option is not selected. This bar is too huge to leave it, it is too annoying. Please remove it or add an option to ignore autofill in options. Thanks.

**Comment by PhilippC** [comment] 2018-04-04 02:12
duplicate of #311

**Closed by PhilippC** 2018-04-04 02:12 UTC
