### ISSUE TITLE
Feature Request: Unlock with Pixel 4 Face Unlock

### ISSUE THREAD

**Issue by UweBo** [PhilippC/keepass2android#1006] opened 2019-10-25 04:24 UTC
I was able to quickly unlock the database with my fingerprint on my Pixel 2. Now I have a Pixel 4 with Google Face Unlock. Please also implement the unlock of the database with this new technology.

**Comment by PhilippC** [comment] 2019-10-25 07:00
duplicate of #795

**Closed by PhilippC** 2019-10-25 07:00 UTC
