### ISSUE TITLE
Suggestion for attachments

### ISSUE THREAD

**Issue by Mellelmejor** [PhilippC/keepass2android#1421] opened 2020-09-22 18:17 UTC
When you select the option to add an attachment it would be nice if the app would give you the option to directly select the camera rather than a picture stored on your phone (suppose I want to take a picture of a document and I don't want to have it stored on my local storage, but directly take a picture from the Keepass2Android app itself and upload it directly). It would also be extremely good to have some sort of image compression method available to keep the database small and avoid issues such as not being able to load the database to Onedrive because of large size (<4Mb), as well as optimizing load times.

Thanks for the awesome project and keep up the good work :)

**Comment by PhilippC** [comment] 2020-09-28 07:22
duplicate of https://github.com/PhilippC/keepass2android/issues/23

**Closed by PhilippC** 2020-09-28 07:22 UTC
