### ISSUE TITLE
Fingerprint not working on some devices

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#37] opened 2017-10-09 08:33 UTC
Fails to init cipher

**Comment by PhilippC** [comment] 2017-10-09 08:35
BQ Aquaris X Pro 
![screenshot_20170907-082911](https://user-images.githubusercontent.com/5421734/31330145-754b42f2-acdd-11e7-8289-3827808609e8.png)

![screenshot_20170907-082922](https://user-images.githubusercontent.com/5421734/31330162-7f08299a-acdd-11e7-8609-27dba55de63c.png)

**Comment by Airwave1981** [comment] 2017-10-09 10:43
Hi,

same problem on:
HTC U11

Cheers
Airwave

**Comment by thecodemonk** [comment] 2017-11-04 19:34
Galaxy S8+ here. Fingerprint unlock was throwing this same error. I was going to start digging in the code, but before I did, I started searching for this error and came across a blog post saying that this message can pop up if lock screens are disabled or if fingerprints are added after the master key is created. I'm not an android dev, but I am a dev, so this had me starting to play with things. I first deleted my fingerprints in my phone and readded them. I removed all iris scanning (I was previously using it, but stopped, so I deleted the biometric data). I then opened the app and still had the error. I logged into the database, went to database settings, turned off finger prints then turned it back on. To my surprise, it prompted me to use my fingerprint to verify. Once I did, it is now working! I had a Galaxy S7 previously while using this app and fingerprints were enabled. Could this be a migration from one phone to another issue?

**Comment by jeff-schram** [comment] 2017-11-13 10:30
Per your request, copy/pasted from #98:

At Fingerprint Rotionderdelen.init()[0x000d0]
...
caused by
InvalidKeyException: Only SecretKey is supported

Note that the Nokia 8 integrated the fingerprint sensor in the (capacitive) home button. Placing a finger on the sensor results in returning to the home screen

**Comment by maxmax20** [comment] 2017-11-13 10:48
logcat from #90 
[logcat.txt](https://github.com/PhilippC/keepass2android/files/1466445/logcat.txt)

**Comment by AlexWayfer** [comment] 2017-11-25 18:39
From #135, closed as duplicate of this issue:

> OnePlus 5, in both stable and beta channels.
>
> Fingerprint doesn't work at all (it's in Home button, and I'm returning to Home by touch it).
>
> The red bang mark near master-password field, by touch on it pop-up with "Fingerprint unlock" title and error stack trace. I can't to screenshot because of it isn't allowed by app. And there is no "send" or "copy" buttons.
>
> Begins with:
>
> ```
> Exception of type 'Java.Lang.RuntimeException' was thrown.
>   at keepass2android.FingerprintDecryption.Init () [0x00d0] in <aaa7e0749da146d3871f57c8138c11ad>:0
>   at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00089] in <aaa7e0749da146d3871f57c8138c11ad>:0
>   --- End of managed Java.LangRuntimeException stack trace ---
> java.lang.RuntimeException: Failed to init Cipher
>   at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
>   at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
> ```
>
> I tired to type, sorry. Please, make button for email to developer this stack trace (or at least copy to clipboard).

**Comment by poblabs** [comment] 2017-12-02 16:01
Just wanted to update that @thecodemonk's suggestion:

> I logged into the database, went to database settings, turned off finger prints then turned it back on. To my surprise, it prompted me to use my fingerprint to verify. Once I did, it is now working!

worked for me as well on my Pixel 2 (see https://github.com/PhilippC/keepass2android/issues/62). The automatic app migration from my old phone to my new phone must have saved some sort of device-specific ID? 

Anyways, just wanted to share my experience.

**Comment by PhilippC** [comment] 2017-12-02 16:05
thanks for the feedback. I purchased an HTC U11 device hoping I could reproduce the issue (as @Airwave1981 has reported to have the issue there) but was not able to do so. So maybe this really simply means you have to re-enable fingerprint?

**Comment by poblabs** [comment] 2017-12-02 16:07
Perhaps. I don't know if there's a way to disable the fingerprint option on app migration to a new phone? That might force us into realizing that we need to re-enable it?

**Comment by jeff-schram** [comment] 2017-12-02 16:14
I tried turning the fingerprint option off and on on my Nokia 8 and it
worked.

Op 2 dec. 2017 17:07 schreef "poblabs" <notifications@github.com>:

Perhaps. I don't know if there's a way to disable the fingerprint option on
app migration to a new phone? That might force us into realizing that we
need to re-enable it?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PhilippC/keepass2android/issues/37#issuecomment-348701624>,
or mute the thread

**Comment by frimtec** [comment] 2017-12-02 17:43
Same with my pixel 2. Disable fingerprint and re-enable helped.

**Comment by AlexWayfer** [comment] 2017-12-02 19:47
You're geniuses, guys! Thank you! It works for OnePlus 5 (app was restored via Google Sync from Sony Z5 Compact).

**Comment by Airwave1981** [comment] 2017-12-02 20:41
Jipii, yes disable and enable fingerprint again also now worked for me HTCU11!!!

Now everything is fine.

Thanks a lot.


Cheers
Airwave

**Closed** 2017-12-06 04:35 UTC
Labels: bug

**Comment by Neutral67fr** [comment] 2017-12-11 13:15
Nice! I had the same issue and I cold fix it with the trick found in this thread :-)
Thanks @thecodemonk 

OnePlus 3T Oxygen OS 5.0 (Android 8.0.0)
