### ISSUE TITLE
[Feature Request] MEGA cloud support

### ISSUE THREAD

**Issue by Brontoloo** [PhilippC/keepass2android#233] opened 2018-02-01 17:25 UTC
It would be great to load my DBs directly from MEGA, which I'm using since it offers a lot more free space than dropbox/drive/onedrive (and I like the linux/windows/android client much more).
At the moment I can open them through the MEGA android app, but a native solution would be better.
I hope I'm not the only one asking for this :)

**Comment by lucarillosi** [comment] 2018-02-05 00:01
I agree :+1: Mega also offers a sync client for Linux whereas Drive does not!

**Comment by PhilippC** [comment] 2018-02-08 08:22
duplicate of #99

**Closed by PhilippC** 2018-02-08 08:22 UTC
