### ISSUE TITLE
Keypass to Android app is no longer available on Chromebook from the Play Store. Is there another way I can access it? Thank you. I uninstalled it and now I cannot reinstall it.[QUESTION] 

### ISSUE THREAD

**Issue by Marigotthis** [PhilippC/keepass2android#2448] opened 2023-10-24 22:21 UTC
**What version of Keepass2Android are you using?**
Please follow these steps to find your app version:
1. Click the **⁝** icon in the top right corner
2. Select **Settings**
3. Click **About**
4. Find the "Version" information and provide it here:

**Comment by Spiralpine** [comment] 2023-10-24 23:01
@Marigotthis ,

It can be frustrating for @PhilippC  (the app developer) when a redundant issue is opened without conducting a prior search. It seems that you may have missed the fact that I have already opened an issue for this. It would have been helpful if you had performed a search beforehand.

https://github.com/PhilippC/keepass2android/issues/2316

You can close yours.

**Comment by PhilippC** [comment] 2023-11-21 08:48
duplicate of #2316

**Closed by PhilippC** 2023-11-21 08:48 UTC
Labels: question
