### ISSUE TITLE
Keyboard menu doens't insert text into web forms

### ISSUE THREAD

**Issue by kibinimatik** [PhilippC/keepass2android#2047] opened 2022-08-06 17:06 UTC
When you invoke the keyboard menu and pick a string field from it, its value is not inserted.
You can insert the value with usual keybord buttons, but it's difficult when the entry has a great number of additional string fields.
The issue only appears with web forms. The keyboard menu works properly when you use it for app controls, e.g. for the location bar.

The attached video demonstrates all of that.
https://user-images.githubusercontent.com/30236498/183258798-1f811a43-ee48-4fcf-8538-30726093f6e4.mp4

The system on which the problem occurs:
Xiaomi Redmi 9c (MIUI 12.0.22, Android 10)
Keepass2Android 1.09d-r0
Browsers: Opera, Chrome

There're devices on which the keyboard menu works correctly:
Android 7.1.2 (Resurrection Remix), Android 7.1.1

**Comment by LordMerlin** [comment] 2022-08-08 08:31
I confirm the error. Values are not inserted through the menu.

The system on which the problem occurs:
Xiaomi Redmi Note 10 Pro (MIUI 12.5.5, Android 11)
Keepass2Android 1.09d-r0
Browsers: Maxthon, Vivaldi

**Comment by gab** [comment] 2022-09-13 01:16
Same here on multiple Samsung devices. TOTP entry through menu doesn't work, through button it does.

**Comment by PhilippC** [comment] 2024-01-03 10:49
duplicate of #1787

**Closed by PhilippC** 2024-01-03 10:49 UTC
