### ISSUE TITLE
feature request: option to hide 'disable autofill for XYZ' menuitem 

### ISSUE THREAD

**Issue by Eddict** [PhilippC/keepass2android#1894] opened 2022-01-02 22:08 UTC
hi. could you please add a setting to allow me to hide the 'disable autofill for XYZ' menuitem. i accidentally click it way too often and then it's quite a hassle to undo that. i love the autofill, except that annoyance. thanks!

**Comment by Indubius** [comment] 2022-02-08 03:54
Guess it's there, as long as it's not only in the beta I'm participating... 😉

**Comment by PhilippC** [comment] 2022-02-09 18:55
closed in 2c93fd15422d03f98c39f16297518e1ff031b8ea, duplicate of #1843

**Comment by PhilippC** [comment] 2022-02-09 18:55
this is available in beta (1.09d)

**Closed by PhilippC** 2022-02-09 18:55 UTC

**Comment by Eddict** [comment] 2022-02-12 21:16
> this is available in beta (1.09d)

awesome, thanks!
