### ISSUE TITLE
Can no longer use Google drive

### ISSUE THREAD

**Issue by jackgeek** [PhilippC/keepass2android#441] opened 2018-07-03 23:51 UTC
Whenever opening a database from Google drive it fails with an error message "the name must not be empty: null"

**Comment by jackgeek** [comment] 2018-07-03 23:57
Sorry forgot to mention this was on android. But I solved this by clearing my application storage. Works now 👌

**Comment by lofgren007** [comment] 2018-07-09 07:03
I had this too. Seems to be a bug after the latest update.
I was prompted to allow or deny a permission - selected allow - then the Google drive db would not open.
Tried various things and after one attempt noted the toast message @jackgeek mentions above (name must not be empty).

I removed and added permissions and tried again - it worked. Clearing cache was going to be my next option...

**Comment by PhilippC** [comment] 2018-07-09 08:56
duplicate of #432

**Closed by PhilippC** 2018-07-09 08:56 UTC
