### ISSUE TITLE
Show password is not showing the whole password

### ISSUE THREAD

**Issue by l-marchesi** [PhilippC/keepass2android#269] opened 2018-02-24 11:42 UTC
Hey Philipp!

I really appreciate your work and use your app weekly, if not daily.
When setting up a new computer, I usually need passwords to access a network storage, which is stored in my database. This is a long one, so I have to look at my mobile phone and type it at my computer.
However, I got access denied several times.
Why?
Because the app is not showing the full password length: Password is 30 characters, app only shows 20 characters. 
However, when I rotate the screen, it does show the full password.
Maybe my phone screen is simply to small (4.6") :man_shrugging: 

Have a nice day!

**Comment by PhilippC** [comment] 2018-02-25 07:47
duplicate of #230

**Closed by PhilippC** 2018-02-25 07:47 UTC
