### ISSUE TITLE
[FEAT] Add support for pronto drive to save key file.

### ISSUE THREAD

**Issue by recoder-lab** [PhilippC/keepass2android#2594] opened 2024-05-04 00:32 UTC
Would make everything more secure if we can use pronto drive to store the key file.  Is there anything preventing this implementation?   Google and Dropbox are not ideal.

**Comment by PhilippC** [comment] 2024-05-04 02:35
do you mean Proton or Pronto? I haven't heard of the latter?

**Comment by recoder-lab** [comment] 2024-05-04 02:56
Yes Proton, sorry for the typoOn May 3, 2024 10:36 PM, PhilippC ***@***.***> wrote:
do you mean Proton or Pronto? I haven't heard of the latter?

**Comment by PhilippC** [comment] 2024-05-04 04:55
duplicate of https://github.com/PhilippC/keepass2android/issues/2313

**Closed by PhilippC** 2024-05-04 04:55 UTC
Labels: enhancement
