### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by luisbraganca** [PhilippC/keepass2android#314] opened 2018-03-27 11:11 UTC
First of all: Great job with your app.
Would be a great idea to publish your sources into F-Droid.
F-Droid is a Google Play-like App repository but all the F-Droid apps are open-source.
Since this project is a great contribution to the open-source community, I suggest you would consider publishing it into f-droid.
Me (and I'm pretty sure that lots of other people) don't trust anything-google-related-stuff that's not open-source, and I have no idea what changes they do to your code, so, since your project already meets the requirements to be published in f-droid (must be open-source), I really suggest you would do that. Pretty sure it would also increase keepass2android user count.
In order to give a little help, here are a few links about F-Droid app publishing:
https://forum.f-droid.org/t/how-to-publish-my-app-on-f-droid/198
https://f-droid.org/docs/FAQ_-_App_Developers/?title=FAQ_-_App_Developers
Thank you for your time. :)

**Comment by Karreg** [comment] 2018-03-27 12:09
The request makes sense, but it's already discussed here : #38 

Also, the source code is not published on Play Store, it's the binary app that is published :smile: 

Google may decompile the app to make changes, but it would be known by now.

If you don't trust Google you can download the app directly [here](https://github.com/PhilippC/keepass2android/releases) but the version is not up-to-date.

Also, you can compare the binary published here, and the binary from the play store available in APK Mirror ([here](https://www.apkmirror.com/apk/philipp-crocoll-croco-apps/keepass2android-password-safe/)) so you can make you own opinion about changes done in apps :smiley:

**Comment by Karreg** [comment] 2018-03-27 12:09
Duplicate #38

**Comment by Karreg** [comment] 2018-03-27 12:09
Close #314

**Comment by PhilippC** [comment] 2018-03-28 01:37
duplicate of #38

**Closed by PhilippC** 2018-03-28 01:37 UTC
