### ISSUE TITLE
Unable to access onedrive (Samsung Galaxy S9+)

### ISSUE THREAD

**Issue by lazi3b0y** [PhilippC/keepass2android#1136] opened 2020-02-01 16:11 UTC
When I try to access my database file on my onedrive, the first attempt (usually after I've killed the app from running in the background) it seems to be redirected to another page with a black/dark grey top border with the rest completely blank and then immediately (after like half a second) redirected back to the main menu, I never get the chance to choose what file too open.
If I (after being redirected to the main menu) click "open file..." again and try to open onedrive, the app crashes every time until I kill the app and then I'm back to where I started with the blank screen.

EDIT: I have since writing this rooted my device and am now running LineageOS which does not have this problem. So I'm assuming that the problem was related to Samsungs android version.
Also noteworthy is that I'd done a factory reset before getting these problems.

**Comment by PhilippC** [comment] 2020-02-11 18:48
interesting, thanks for the edit. I will close this for now if the problem is gone for you.

**Closed by PhilippC** 2020-02-11 18:48 UTC
