### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Latruffy** [PhilippC/keepass2android#2378] opened 2023-07-12 10:38 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I'm trying to use Keepass2Android with a kdbx database file hosted on pCloud :
- If I try to use a "real" subfolder such as /Applications/Keepass2Android/latruffe/, Keepass2Android correctly lists this folder and allows me to select my kdbx file inside.
- But if (still in /Applications/Keepass2Android/) latruffe is a shared folder (with me) from another pCloud account, Keepass2Android doesn't display it.

### Describe what you expected to happen:

I'd like Keepass2Android allow me to select a kdbx database file hosted in a shared folder on pCloud.

Maybe some pieces of solutions : 
- According to [pCloud dev docs](https://docs.pcloud.com/), I guess Keepass2Android code is using listfolder method. And I just see a listshares method exists too. It may perhaps help.
- Trying to investigate with Insomnia (SoapUI Linux alternative), I can see json answer for a "real" folder diplays the attribute
    "ismine": true
while for a shared folder
    "ismine": false,
    "ismount": true,

Thanx by advance

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

10

**Comment by hyproman** [comment] 2023-07-25 00:47
Hi @Latruffy,

The current version of KP2A is using an older version of the pCloud Java SDK that does not support shared folders (KP2A is using v1.2.0, while shared folder support was added in v1.8.0).

However, it looks like there has been related work done ([see here](https://github.com/pCloud/pcloud-sdk-java/issues/33)). It looks like @PhilippC was successful in upgrading KP2A to the new pCloud SDK (at least personally), but that was over a year ago and KP2A is still running the old version, with no related open Pull Requests.

I will see if I can do this SDK upgrade, however I don't have much experience with integrating oauth (or pcloud's SDK), so I can't promise anything. Even if I am able to, it would need to be approved/released by KP2A's author.

**Comment by hyproman** [comment] 2023-07-25 21:23
PR #2388 contains the updated pCloud SDK. Unfortunately the new authentication does not work (as mentioned [here](https://github.com/pCloud/pcloud-sdk-java/issues/33), the "redirect_uri" problem). That can only be fixed by changing KP2A configuration on pCloud, which I don't have access to.

That said, I was able to open and save a shared DB (same structure as you described) with the new code, before my old authentication got cleared out. That should mean that updating the redirect_uri is the last step in fixing this issue.

**Comment by hyproman** [comment] 2023-10-05 20:15
The redirect URI change must be done to the KP2A App configuration on KP2A's PCloud developer account. It's not something that can be fixed through a normal user's PCloud account. Sorry.

**Comment by PhilippC** [comment] 2023-11-21 12:10
duplicate of #1949

**Closed by PhilippC** 2023-11-21 12:10 UTC
Labels: bug
