### ISSUE TITLE
Database on Tresorit

### ISSUE THREAD

**Issue by kazaam66** [PhilippC/keepass2android#1139] opened 2020-02-02 17:01 UTC
I have my database on Tresorit and everything works fine with KeypassXC on my PC. 

I was trying to open the database on Keypass2android app but an error showed up saying "the file is only temporarily available for Keypass2Android. To use it, you must copy it to another location. Tap okay to copy to another location where the file should be copied"
I have no idea what to do next. Hoping for a fix in the next update,

**Comment by PhilippC** [comment] 2020-02-13 19:53
duplicate of #57

**Closed by PhilippC** 2020-02-13 19:53 UTC
