### ISSUE TITLE
Username field entry hits enter

### ISSUE THREAD

**Issue by pokelhospital** [PhilippC/keepass2android#159] opened 2017-12-11 20:27 UTC
When using the keypass keyboard plugin to enter username the username is pasted followed by a return resulting in many websites attempting login before data is entered in the password field. This results in an invalid login result from the website. Some websites clear the username field.

Workaround: I have been entering passwords before usernames.

Requested change: user input buttin should past the username without a return.

**Comment by PhilippC** [comment] 2017-12-13 20:25
duplicate of #151

**Closed by PhilippC** 2017-12-13 20:25 UTC
