### ISSUE TITLE
Frequent OneDrive authorization request

### ISSUE THREAD

**Issue by wombat01** [PhilippC/keepass2android#1038] opened 2019-11-13 14:18 UTC
Since version 1.08 (pre3), it is necessary to confirm authorization on OneDrive almost every time I want to open it.

https://i.ibb.co/nr91Bc1/x-Screenshot-Nov-13-2019-3-11-49-PM.png

**Comment by parovi01** [comment] 2019-11-13 21:33
Same issue here with version 1.07b-r0.

I use Microsoft authenticator, maybe that is the reason.

Pablo

**Comment by J-O-P** [comment] 2019-11-25 20:10
I have the same or a similar problem - Every time when the app is started fresh and it tries to access the database on Onedrive for Business I get an Onedrive Authentication Message "Pick an account" (I use different O365 accounts for different purposes). 
Then I select the account where my keepass DB ist stored, 
Next I get a message "Are you trying to sign in to Keepass2Anfroid?" (this seems to be the same screen as wombat01 posted above) and I click "Continue".
Then the sync works (I do not hae to selected the databse again). However these authentication dialogs keep coming back every time the app is restarted.

**Comment by towadroid** [comment] 2019-12-03 08:36
Already described the problem when the offline access bug was fixed: [here](https://github.com/PhilippC/keepass2android/issues/806#issuecomment-547357891) There is also a log file.

**Comment by priv** [comment] 2020-07-28 08:48
For me this pops up about one time a day.

**Comment by wombat01** [comment] 2020-07-29 09:13
Since the last update **1.08b-r0**, everything seems to be fine.

**Comment by towadroid** [comment] 2020-09-17 13:57
I am using 1.08b-r1 and I get inconsistent behavior.
The only scenario I am able to reproduce is the following: The authorization window pops up every time if 1) the app has been stopped forcefully and 2) there is an internet connection when opening the app.

However I have also experienced that I could not access my database without an internet connection at all because the app tried to authorize onedrive access.

**Comment by JNavas2** [comment] 2020-10-13 00:22
Like @J-O-P I have 2 OneDrive accounts, and I often get a prompt when opening the database asking me which account I want to use. (The 2nd account is not on my Android device, has never been used in the app.) I speculate that this is being triggered by Microsoft, which knows that I have more than one account.

**Comment by Mercerudy** [comment] 2020-10-28 13:24
Just switched from Dropbox to Onedrive sync and also having this issue with 1.08b-r1.

**Comment by JNavas2** [comment] 2020-10-28 21:38
Since my earlier comment I've paid more attention to this problem, and it seems to be related to the quality of my Internet connection. It never seems to happen on a solid Internet connection, just when I'm on a bad connection with poor speed and high latency. And when the issue occurs, I can open my database without new authorization by backing up and trying again. My guess is that authentication is timing out, and that the app assumes it's an authentication error, so opens a new unnecessary authorization. That would seem to be a possible bug or at least poor error recovery.

**Comment by Mercerudy** [comment] 2020-10-29 01:23
I've also noticed that I can just back up and try again, successfully opening the database. I assumed that I was just working with local cache, but what you're saying makes sense @JNavas2.

**Comment by JNavas2** [comment] 2020-10-30 20:23
Video showing unnecessary OneDrive authorization: https://youtu.be/lSAg-oATW0k
Video starts immediately after launching app. After much spinning, OneDrive authorization screen appears.
I touch back, and open database appears (black screen since app prohibits screen capture).

**Comment by JNavas2** [comment] 2020-10-30 20:47
I enabled logging, and reproduced the problem. Log file attached (OneDrive details deleted).
[Keepass2Android.log](https://github.com/PhilippC/keepass2android/files/5467557/Keepass2Android.log)

**Comment by JNavas2** [comment] 2020-10-31 16:47
**Video showing issue: https://youtu.be/jGcLJiKc77I**
Starts with fingerprint (not captured) opening of database.
App opens database [see capture below], but displays OneDrive authorization screen.
Single back touch then displays _open_ database.

![Screenshot_20201031-092236](https://user-images.githubusercontent.com/14850792/97784726-d1298600-1b5d-11eb-8f92-b71bc6dba9bb.png)

**Comment by PhilippC** [comment] 2020-11-09 11:01
a user noted that the authorization request happens after updating the file from the Windows client. this might help diagonising this.

**Comment by Mercerudy** [comment] 2020-11-09 13:37
It happens for me even when the local android device was the last to update the file.

**Comment by priv** [comment] 2020-11-10 04:12
This is very strange behavior.  Even if you just close this dialog, file is still synchronized correctly.  The re-auth is just unnecessary.

**Comment by JNavas2** [comment] 2020-11-10 04:36
@PhilippC
>  a user noted that the authorization request happens after updating the file from the Windows client. this might help diagonising this.

See my video and log. The behavior was _not_ after a Windows update of the file.

**Comment by PhilippC** [comment] 2020-11-10 18:29
I'm not saying this is the only option how to produce this, but in my previous tests I wasn't able to reproduce this behavior (which makes it very difficult to fix), so I thought this might be a good hint for me when fixing.

**Comment by JNavas2** [comment] 2020-11-10 18:43
@PhilippC 
It can be hard to reproduce, but the problem appears to entirely be a function of what's happening on the phone, not anything external. How I reproduce it (how I got the log file and video I posted):

1. Reboot the phone
2. Wait a few minutes until the reboot dust has settled
3. Open the database on OneDrive.

I just did it again to confirm that _it does reproduce the problem_.

**Comment by Mercerudy** [comment] 2020-11-10 19:17
> Since my earlier comment I've paid more attention to this problem, and it seems to be related to the quality of my Internet connection. It never seems to happen on a solid Internet connection, just when I'm on a bad connection with poor speed and high latency. And when the issue occurs, I can open my database without new authorization by backing up and trying again. My guess is that authentication is timing out, and that the app assumes it's an authentication error, so opens a new unnecessary authorization. That would seem to be a possible bug or at least poor error recovery.

@JNavas2's hypothesis from a couple of weeks ago^ fits my observations as well. Is there no reason that a premature authentication timeout might be the culprit? @PhilippC

**Comment by alwils** [comment] 2020-11-18 20:54
This behavior (as shown in the video) happens to me very frequently (so much so, that each time I open the manager I expect it to do this double auth behavior). I do not have the Windows client installed and do not modify the database outside of Kp2A. I have a fast WiFi connection and a Pixel 4 XL.

However, I cannot repro the problem reliably... even with JNavas2's instructions. To me, it seems like the popup likelihood is positively correlated with respect to the time passed since the database was last opened. If I have opened it recently it does not occur, but if I opened it a few days ago (exact time TBD) it seems to popup.

**Comment by JNavas2** [comment] 2020-11-18 20:57
@alwils 
I agree that time since it was last opened is a factor. The longer it has been the more likely the problem will occur.

**Comment by Mercerudy** [comment] 2020-11-18 21:02
Another anecdote: I just moved from a Pixel 3 to a Pixel 5.  Same Android version and all apps are also the same.  The reauth does still happen but maybe 20% as often as before with my Pixel 3.  This also makes me wonder whether a slow authentication is triggering the reauth.  With more compute power in my newer device, I'm guessing it's beating that timeout threshold more often.

Agree with the previous comment as well: if I do have to reauth, then it will tend to successfully load without reauth if I quickly try it a few more times.

**Comment by priv** [comment] 2020-11-24 11:41
Btw,
Though I'm not very familiar with onedriver auth or Android app development, I can reproduce this many times a day on my phone.  Please tell me where to add log, I can build test apk and do logcat or something.

**Comment by JNavas2** [comment] 2020-11-24 13:53
@priv 
Go to Settings > App > Log file for debugging.

**Comment by priv** [comment] 2020-11-25 01:53
@JNavas2 

I mean add more log in code

I've already inspected the app log, there's no telling why it triggers the re-auth activity.

**Comment by cjk28** [comment] 2020-11-25 15:07
I regularly get this issue. I recently started seeing this too which requires a force close to be able to get back in to the database. Not sure if related to the issue in question but posting it just in case
![Screenshot_20201125-150437](https://user-images.githubusercontent.com/37836054/100245374-e365cc80-2f2f-11eb-80e0-f7fe540e6f18.png)

**Comment by bnsonear** [comment] 2020-12-03 11:01
I'm using Galaxy Samsung Note 9 (Android 10) and Keepass 1.08b-r1. 
I'm frequently asked to log-in to Microsoft Account, and forced to tap "Yes" button for "Are you trying to sign in to Keepass2Android?"
![Screenshot_20201023-081521_Kiwi Browser](https://user-images.githubusercontent.com/75421289/101001167-1d734600-35a2-11eb-8b8e-35b06486b031.jpg)

This is very painful to use Keepass. Is there any other workaround except downgrading to 1.07?

**Comment by CzBiX** [comment] 2020-12-03 11:19
There are two workarounds.
1. Just press back when opening auth web page(even in white screen) on unlocking, k2a will still success open database.
2. Open database in offline mode, and manually sync database on demand.(I'm using this one, since my database changed infrequently.)

**Comment by bnsonear** [comment] 2020-12-03 11:41
Thank you for the fast response! 
For me, frequent and fluent sync between mobile and desktop is very important. Therefore I have to downgrade and will wait for 1.09, thank you again!

**Comment by roboxv** [comment] 2020-12-03 11:58
I face this issue almost every time I open the app.

Is there anything I can provide to help you to debug this problem, @PhilippC?

**Comment by PhilippC** [comment] 2020-12-10 04:01
is this the same as https://github.com/PhilippC/keepass2android/issues/1495?

**Comment by JNavas2** [comment] 2020-12-10 05:19
@PhilippC 
#1495 does appear to be a dup.

**Comment by JNavas2** [comment] 2020-12-14 21:30
Problem persists in 1.08c-r1

**Comment by towadroid** [comment] 2021-02-17 23:02
I want to throw in the following observation:
Previously, when I had the option `Pre-load database file` disabled, I often (almost always) got the authorization request. After enabling said option, until now, I did not encounter the extra authorization.

Also someone on [reddit](https://www.reddit.com/r/KeePass/comments/km9t7z/comment/gheee6r) mentioned that it might be related to KeePass checking whether the file is in sync. Indeed my experience confirms that if the toast message "source file and cache are synchronized" comes early enough, then no extra authorization is requested. If the option `Pre-load database file` is enabled, then waiting sufficiently long for the message before opening the database prevents the extra login page from showing up. Conversely, if the login page has showed up, the notification toast pops up a few moments later.

To me this sounds like a race condition. When pre-loading is disabled, I assume the check whether the files are in sync is carried out only after successfull unlock. In that time frame, if the check is fast enough (maybe correlating with fast internet and/or fast CPU), the authorization does not show up. If the check doesn't return successfully within a certain time frame, the reauthorization is triggered.

All this seems to be in accordance with previous observations, e.g. [Comment 1](https://github.com/PhilippC/keepass2android/issues/1038#issuecomment-718223853) @JNavas2 , [Comment 2](https://github.com/PhilippC/keepass2android/issues/1038#issuecomment-729951249) @Mercerudy 

My best bet to reproduce the behaviour is as follows:
1) Disable pre-loading.
2) Force stop the app.
3) Open the app and unlock the database.
4) Reauthorization shows up.

My setup:
S9+, Android 10, 1.08d-r5
S20, Android 11, 1.08d-r5

**Comment by JNavas2** [comment] 2021-02-17 23:27
Alas, I have `Pre-load database file` _enabled_, yet I _still_ usually get the unnecessary Microsoft login. 

I have `Database caching` _disabled_. Perhaps that makes a difference.

It's a really unfortunate issue, because it keeps me from recommending the app to colleagues and clients.

Device: Pixel 4a (5G) running Android 11 (RQ1C.210205.006).

**Comment by towadroid** [comment] 2021-02-18 00:06
As you could tell I have `database caching` enabled.

Do you still get the login page if you wait a while before unlocking the database?

**Comment by JNavas2** [comment] 2021-02-18 01:08
@towadroid 
Suddenly I'm unable to make it fail either with or without delay. Go figure.
I'll report back if it starts failing again.

**Comment by JNavas2** [comment] 2021-02-18 07:04
@towadroid 
Alas, I spoke too soon, because the problem happened again. The difference is that I did other things for an extended period of time, then opened this app, quickly unlocking (without thinking), and got the unnecessary Microsoft login. So it's hard to readily reproduce.

**Comment by towadroid** [comment] 2021-02-18 08:58
I'm a bit confused. Your observations neither contradict my description nor do they support it. Quickly unlocking and getting the login page does fit to my description.

I proposed to _forcefully stop_ the application before opening the app again. Not only closing the app from the task menu but really forcing the app to stop via the app info menu. Do you get consistent behaviour with this procedure? I.e. 
1) with pre-loading enabled, does waiting before unlocking prevent the login page from showing up?
2) with pre-loading disabled, does the login page show up?

When the app was forcefully stopped before opening again I can get consistent behaviour. Otherwise I also can't fully reliably reproduce the error. I know that this is not a realistic scenario but it would be helpful if we could  at least reproduce the bug.

**Comment by JNavas2** [comment] 2021-02-18 15:17
@towadroid 
In response to your post, I did 3 quick tests with pre-load _enabled_ (and quick fingerprint unlocking):
1. After a long delay from prior use, _did_ get the unnecessary Microsoft login.
2. After Force Close, did _not_ get the unnecessary Microsoft login.
3. After Force Close, did _not_ get the unnecessary Microsoft login.

Then 3 quick test with pre-load _disabled_ (and quick fingerprint unlocking):
1. After Force Close, _did_ get the unnecessary Microsoft login.
2. After Force Close, _did_ get the unnecessary Microsoft login.
3. After Force Close, _did_ get the unnecessary Microsoft login.

So pre-load reduces but does not completely eliminate the unnecessary Microsoft login for me, depending on how long it's been since I last opened the database, even with Force Close. Thus it's time-consuming for me to reproduce. Perhaps the OneDrive document provider is doing its own caching.

My guess is that the unnecessary Microsoft login is due to a too-short timeout condition—when the database doesn't open within the too-short timeout, the app launches an unnecessary Microsoft login.

**Comment by towadroid** [comment] 2021-02-18 23:37
@JNavas2 Well, 3 out of 3 of your tests confirm my instructions to reproduce the error from my [earlier comment](https://github.com/PhilippC/keepass2android/issues/1038#issuecomment-780911897):

> My best bet to reproduce the behaviour is as follows:
> 
> 1. Disable pre-loading.
> 2. Force stop the app.
> 3. Open the app and unlock the database.
> 4. Reauthorization shows up.

The fact that the login page may appear depending on how long it's been since the database was last opened just shows that some factors may be different after a fresh open after a forced close. I mean, I do see that we still cannot predict under which exact circumstances it appears but at least it seems that we are now able to _consistently reproduce the error_.

@PhilippC Maybe this could be a new approach to investigate the problem?

**Closed** 2021-02-19 06:03 UTC

**Comment by PhilippC** [comment] 2021-02-19 08:21
thanks @towadroid, the hint with the preloading setting allowed to reproduce this reliably - so I could finally locate and fix the bug.

**Comment by towadroid** [comment] 2021-02-19 09:13
@PhilippC no worries, thank you for developing the app! Keep it up!

**Comment by cube79** [comment] 2021-03-07 09:29
Is it fixed for all of you? I have just started using keepass, after leaving LastPass and it still is happening to me. From time to time the onedrive login screen is presented but if I cancel it the database is normal. 
All the rest works fine. Thank you for this great app.

**Comment by layanto** [comment] 2021-03-07 09:55
I am on 1.08d-r5 and I still get the OneDrive login screen.

**Comment by towadroid** [comment] 2021-03-07 10:37
I think, there has not been a new release since the fix, 1.08d-r5 was released on 2021-01-24 and the commit that fixed the bug was on 2021-02-19... So, sit back and relax :)

**Comment by PhilippC** [comment] 2021-03-08 08:09
please join the beta tester channel on https://play.google.com/apps/testing/keepass2android.keepass2android to get 1.09a-pre1 where this fix is included.

**Comment by cube79** [comment] 2021-03-08 12:30
Did it yesterday and since that got no problems so fora. THX

**Comment by Severus157** [comment] 2021-03-18 17:20
Is there any way to get the Beta Version without the Google Play Store? I also have this problem almost every day and cannot access Google Play.

**Comment by t-b-x** [comment] 2021-06-17 21:26
Hey everyone, I have same problem. Hope the fix is published soon to official release - are there any release plans or next release date?

Thanks for this great app :)

Kind regards :)

**Comment by JNavas2** [comment] 2021-06-17 21:33
@t-b-x 

> ... join the beta tester channel on https://play.google.com/apps/testing/keepass2android.keepass2android to get 1.09a-pre1 where this fix is included.

**Comment by t-b-x** [comment] 2021-06-18 16:12
> 
> 
> @t-b-x
> 
> > ... join the beta tester channel on https://play.google.com/apps/testing/keepass2android.keepass2android to get 1.09a-pre1 where this fix is included.

Thanks, will do.
