### ISSUE TITLE
GBoard keyboard switch doesn't list Keepass2android

### ISSUE THREAD

**Issue by AlexanderSidorenko** [PhilippC/keepass2android#56] opened 2017-10-19 06:13 UTC
I am not sure if it's a GBoard issue or if it's Keepass2android issue.
I have been using GBoard + Keepass2android forever, but after recent updates, Keepass2android disappeared from the list of keyboards when I long-press globe in GBoard. I still can select Keepass2android from "select keyboard" in notifications drop down, though.

Here's my device/version info:
![screenshot_20171018-230730](https://user-images.githubusercontent.com/4994575/31756646-e9836f90-b459-11e7-8af8-c0fee9b6e310.png)

**Comment by AlexanderSidorenko** [comment] 2017-10-19 06:28
As an experiment, I enabled AOSP keyboard in settings:
![screenshot_20171018-232348](https://user-images.githubusercontent.com/4994575/31757017-ee875e8c-b45b-11e7-8d49-9a01e2cd3ce4.png)

And it shows up correctly in the list when I long press Globe in GBoard:
![screenshot_20171018-232320](https://user-images.githubusercontent.com/4994575/31757041-043a7d5e-b45c-11e7-92ae-e6e2c1371060.png)

**Comment by PhilippC** [comment] 2017-10-20 04:10
another user reported something similar after using the KeyboardSwap plugin. Did you try this previously, so maybe that's the culprit?

**Comment by AlexanderSidorenko** [comment] 2017-10-20 05:29
I just checked, and I don't have any plugins for Keepass2Android installed.
How can I help with debugging?

**Comment by PhilippC** [comment] 2017-10-23 09:24
if you did not use that plugin, please ask the gboard developers if they can provide more information or check this.

**Comment by Microscotch** [comment] 2017-10-23 22:47
Same issue since last update of GBoard.
Tested with another virtual keyboard provided by my phone (Huawei Swype): it is listed by gboard as an alternate keyboard, while keepass2android is not.

**Comment by dolphinkite** [comment] 2017-10-31 17:32
I too have been seeing the same problem since my last Android update (to Android 8.0.0).

Basically, when browsing a website and where I could press the globe to select my Keepass keyboard (to enter my credentials on a website I must log-in, for example), I now only see the English and French keyboards offered, whereas before I would also have the keepass keyboard offered. That option is gone.

**Comment by ginkel** [comment] 2017-11-07 10:57
Just a guess, but all the other keyboards seem to publish some subtype / language information, which Keypas2Android apparently does not.

https://developer.android.com/guide/topics/text/creating-input-method.html#IMESubTypes

I'm also affected by the issue and will be more than happy to help testing a fix.

**Comment by PhilippC** [comment] 2017-11-13 09:46
Ok, I needed to add another input languge to the GBoard keyboard to get the globe, now I can reproduce. But as a note, I recommend switching the keyboard through Share URL whenever this is possible. And as a workaround, use the notification from the notification drawer until I fix this.

**Comment by ginkel** [comment] 2017-11-13 09:58
Excellent, thanks!

"Share URL" unfortunately does not work for native apps and the keyboard switching notification no longer exists in Android 8.

**Comment by et304383** [comment] 2018-01-16 03:36
Any updates here?  This was one of my fav features and I greatly miss it.

**Comment by per11235813** [comment] 2018-01-16 08:37
I can change keyboard to through a system notification that pops up when a input field i activated.

I do not know this is intended as s correction, but it works pretty well.

**Comment by et304383** [comment] 2018-01-25 03:39
Can we please get a fix for this?  It's incredibly inconvenient having to access the username and password from the notification card.

**Comment by PhilippC** [comment] 2018-02-04 18:42
this is assigned to the next milestone. So if I can find a solution, I will integrate it. Please be patient, I am developing in my spare time only.

**Comment by et304383** [comment] 2018-02-04 21:52
@PhilippC thanks for all your hard work.  Truly appreciate it.  Looking forward to the release.

**Comment by aviposs** [comment] 2018-02-08 21:40
@PhilippC I also have this issue and I just wanted to thank for all the time and effort you put into this.

**Comment by rodmur** [comment] 2018-02-14 21:04
I see the notification to switch to Keepass2android keyboard, it but it never pops up now, I'm using Keepass2android 1.03 and Android 8.1.  I think this problem started when I upgraded to 8.1, but I'm not absolutely sure now.

**Comment by Mrfiregem** [comment] 2018-03-20 18:51
Came to say I have this issue as well. Thought Gboard just didn't list any other keyboard apps at first, but I realized SwiftKey showed up when I installed it.

**Closed** 2018-03-27 19:58 UTC

**Comment by AlexanderSidorenko** [comment] 2018-03-28 05:04
Nice! Thanks for fixing it!
Do you have an estimate when you are going to cut the next release?

**Comment by PhilippC** [comment] 2018-03-31 05:03
it's available in the beta channel. The regular release will require quite a bit of time.

**Comment by freMea** [comment] 2018-05-04 22:29
Issue is fixed in 1.05-pre2.

Thanks
