### ISSUE TITLE
Add specific character on QuickUnlock keyboard

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [PhilippC/keepass2android#324] opened 2018-04-02 17:56 UTC
I have some specific characters in my main password (like € £ ¥ ₩ • ...) and I can't type them on QuickUnlock .-. 
So for now I have to copy paste :/

**Comment by PhilippC** [comment] 2018-04-04 02:10
which version are you running? Should be a duplicate of #161 which is fixed in 1.05-pre.

**Comment by PhilippC** [comment] 2018-04-16 07:58
no reaction. Closing for now. Please open if you have 1.05 and still have the problem.

**Closed by PhilippC** 2018-04-16 07:58 UTC
