### ISSUE TITLE
Paste password in the password field of the keepass2android app database 

### ISSUE THREAD

**Issue by Villard** [PhilippC/keepass2android#1595] opened 2021-03-04 06:55 UTC
Hello
Great app I'm using since long years and I am glad to offer beers from time to time ! 

Just an issue I've noticed some months ago

In the Keepass2android app, I can't paste in the password field of an entry, nor copy anyway. 
I think I was able to do it some time ago. Maybe I've changed a parameter. This feature was useful  for mewhen I was receiving a password on a site with no specific security or confidentialité issue and I didn't want to bother to change it. 
Thank you for your advice.
Martin 
I'm runnning Xiaomi Redmi Note 8T with Android 11

**Comment by PhilippC** [comment] 2021-03-08 09:32
cannot reproduce. Can anybody else?

**Comment by ei-ke** [comment] 2021-03-23 19:02
Can't confirm this (Samsung Galaxy M51)

**Comment by PhilippC** [comment] 2021-03-29 08:16
closing as not reproducible. Please add further steps to reproduce, then re-open.

**Closed by PhilippC** 2021-03-29 08:16 UTC
