### ISSUE TITLE
Fingerprint fails the first time; works the second

### ISSUE THREAD

**Issue by dliuzzi** [PhilippC/keepass2android#3] opened 2017-09-25 07:10 UTC
I'm running 1.02-pre3 on a OnePlus 3T. On this phone, the fingerprint sensor is located on the Home button, so tapping this button will either go to the home screen, or scan the fingerprint, depending on the state of the current app.

I've always had _Enable Fingerprint Unlock for QuickUnlock_ selected under _Settings → Database → Fingerprint unlock_ and (save for the app occasionally forgetting this setting and having to select it again) I never had any issue on the stable release of K2A. Ever since I switched to the beta channel, though, I immediately started experiencing a problem: whenever I get to the QuickUnlock screen, fingerprint unlock doesn't work (despite showing a fingerprint icon); trying to unlock with fingerprint registers as a home button press, so I'm taken to the launcher instead.

When this happens I switch back to K2A and this time fingerprint unlock works just fine. I can repeatedly reproduce this, as it happens every time; fingerprint unlock doesn't work the first time, yet it works flawlessly on the second.

**Comment by PhilippC** [comment] 2017-10-03 04:41
can you please collect a logcat of this? I cannot reproduce on my system. Thanks!

**Comment by dliuzzi** [comment] 2017-10-03 08:38
Not sure if I'm doing this correctly as I don't have any logcat experience. Anyway, here you go:

- [device_info.txt](https://github.com/PhilippC/keepass2android/files/1351618/device_info.txt)
- [2017-10-03-10-23-49.txt](https://github.com/PhilippC/keepass2android/files/1351616/2017-10-03-10-23-49.txt)

**Comment by PhilippC** [comment] 2017-10-04 20:30
should be fixed in the next update, please watch the beta channel for testing.

**Comment by dliuzzi** [comment] 2017-10-05 12:13
WOW, That was fast! Found 1.02-pre4 was available today. Installed it and so far so good. Thanks a lot!

**Comment by jeroen7s** [comment] 2017-10-06 07:32
fixed it for me as well 👍

**Closed** 2017-10-09 07:53 UTC
Labels: test-after-update
