### ISSUE TITLE
Keypass2Android Keyboard Button

### ISSUE THREAD

**Issue by HeroGregg** [PhilippC/keepass2android#500] opened 2018-08-12 13:58 UTC
In Android Pie, the Keypass2Android button on the Keypass2Android keyboard does not work. On Oreo (and before) the button would bring up a dialog box asking if you wanted to search for an entry based on the app name. Now, the button does not do anything, unless an entry has already been selected manually through the app. Additionally, when an entry has been selected, and you're on the single line keyboard, the Keypass2Android button doesn't do anything at all there. Previously it would allow you to enter the URL, or other things, associated with an entry.

**Comment by PhilippC** [comment] 2018-08-15 02:11
duplicate of https://github.com/PhilippC/keepass2android/issues/377

**Closed by PhilippC** 2018-08-15 02:11 UTC
