### ISSUE TITLE
doesnt work with kiwi browser on android

### ISSUE THREAD

**Issue by nascentt** [PhilippC/keepass2android#1773] opened 2021-08-22 23:12 UTC
Used to work with kiwi browser (chromium based) but doesn't seem to anymore. It's not listed in the disabled apps list.

It does however still work with ice raven which is a firefox browser I have installed.

I've tried disabling /enabling the chromium integrated password filling service but it doesn't seem to make a difference

**Comment by PhilippC** [comment] 2021-08-23 07:28
do other password managers work (using Autofill service) with Kiwi?

**Comment by nascentt** [comment] 2021-08-23 07:32
Yeah the built in Google one works.
Used to be able to use lastpass before they killed off free usage

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2021-09-13 11:47
Never worked with kiwi #834

**Comment by PhilippC** [comment] 2021-09-20 07:43
closing as duplicate of https://github.com/PhilippC/keepass2android/issues/834

**Closed by PhilippC** 2021-09-20 07:43 UTC
