### ISSUE TITLE
Have I been pawned offline database checker plugin[FEAT] 

### ISSUE THREAD

**Issue by 3D-Pink-Girl** [PhilippC/keepass2android#2518] opened 2024-01-17 16:18 UTC
It would be beneficial if the devs can add the offline database to check email address, usernames, passwords in keepass2android database so that user can change password and add 2fa. It's important not to use cloud to check passwords to the have I been pawned database.

**Comment by PhilippC** [comment] 2024-01-17 17:27
Duplicate of #403

**Closed by PhilippC** 2024-01-17 17:27 UTC
Labels: enhancement
