### ISSUE TITLE
[FEAT] Do the DB Sync in the background, when opening Keepass2android

### ISSUE THREAD

**Issue by finsterwalder** [PhilippC/keepass2android#2427] opened 2023-09-26 05:58 UTC
When I open Keepass2android on slow connections, it sometimes takes quite some time, until I can use it, because it first tries to sync the DB with the remote DB. 
It would be great, if it would always start quickly with the locally cached data and automatically trigger the sync to run in the background. Because it's usually more important to use it quickly, then to have the most up to date data. And most of the times the sync only finds that the DBs are identical anyways. ;-)

**Comment by NumbGnat** [comment] 2024-01-08 02:26
I normally have a relatively fast connection available, so maybe I'm not experiencing what you are.

These are my File Handling settings...

![Screenshot_20240107-212201.png](https://github.com/PhilippC/keepass2android/assets/1946849/1bfed796-e507-42e2-b09d-7d3b1e76b221)

**Comment by finsterwalder** [comment] 2024-01-08 07:56
I use the same settings.

**Comment by PhilippC** [comment] 2024-01-09 04:39
Note: you can suppress the sync if you switch to "Work on internal cache only", but I understand this is not what you are asking for.

closing as duplicate of https://github.com/PhilippC/keepass2android/issues/1144

**Closed by PhilippC** 2024-01-09 04:39 UTC
Labels: enhancement
