### ISSUE TITLE
infinite fingerprint trials

### ISSUE THREAD

**Issue by illionas** [PhilippC/keepass2android#424] opened 2018-06-23 17:56 UTC
in quick unlock mode the database closes itself to normal mode after just one wrong guess (to protect against brute force attack of the very weak 3 letter password part).

however, when fingerprint unlocking is enabled, the app does not lock after the first wrong fingerprint trial.

therefore, an intruder could theoretically try out many different fingerprints or copies thereof (e.g. from smeared display).

I don't know how safe the fingerprint sensor is, but I think not many want to trust in this case. (additionally, the fingerprint sensor can have multiple fingerprint stored, some of which could be of someone else, like ones wife/husband, to enable easy access to the phone itself).

I don't know whether the phone even informs the app if wrong fingerprint trials. therefore I think that a timeout for the quick unlock (reverting to normal password input) could be an easier solution (like I mentioned in  #405).

**Comment by PhilippC** [comment] 2018-06-25 08:10
duplicate of #16

**Closed by PhilippC** 2018-06-25 08:10 UTC
