### ISSUE TITLE
CACert Cerificate warning - Oreo

### ISSUE THREAD

**Issue by keynet** [PhilippC/keepass2android#554] opened 2018-09-17 11:49 UTC
I'm getting certificate warning per the screenshot on my new Oreo-based Android. My old Android 4 didn't show this with the same config and CACERT roots installed as "user trusted" certs as before.  Is this a Keepass2android thing or Oreo? My website that uses the same cert works in Chrome without warnings and gets marked as secure. Thanks for a great app BTW!
![screenshot_20180916-204711](https://user-images.githubusercontent.com/5302023/45621352-da3b6400-ba77-11e8-9fc9-4bbf95451680.png)

**Comment by PhilippC** [comment] 2018-09-17 12:27
duplicate of https://github.com/PhilippC/keepass2android/issues/419. Please switch to beta channel to get the 1.07 release earlier.

**Closed by PhilippC** 2018-09-17 12:27 UTC

**Comment by keynet** [comment] 2018-09-17 12:57
Thanks - will test it

**Comment by keynet** [comment] 2018-09-20 09:18
I am now marked as beta tester, but I received no update. So I uninstalled and reinstalled, The Play Store says I have the beta installed but still on V1.06f, and the problem remains. Something isn't right!

**Comment by PhilippC** [comment] 2018-09-21 03:38
I haven't released 1.07 in beta. I said you will get it earlier but not now. Sorry.

**Comment by keynet** [comment] 2018-09-21 08:07
No problem, thanks for your work, I look fwd to testing it when ready
