### ISSUE TITLE
Hide clipboard preview on Android 13

### ISSUE THREAD

**Issue by gerdablum** [PhilippC/keepass2android#2071] opened 2022-09-12 12:13 UTC
Hi!

I recently updated my phone to Android 13, and now copied passwords are shown in the new clipboard preview as clear text.
There is a way to obscure sensitive content in the new preview: https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent

**Comment by AriehSchneier** [comment] 2022-10-23 23:33
Duplicate of #2058

**Comment by PhilippC** [comment] 2022-12-18 14:48
marking as duplicate

**Closed by PhilippC** 2022-12-18 14:48 UTC
