### ISSUE TITLE
White text on light background

### ISSUE THREAD

**Issue by dtwitkowski** [PhilippC/keepass2android#1616] opened 2021-03-21 16:29 UTC
A recent update causes white text to appear on a light background.  This breaks search, and I've also seen an issue where Dark theme causes white text on the pull down menu.

![Screenshot_20210321-092520_Keepass2Android](https://user-images.githubusercontent.com/59034880/111912655-d82b3500-8a27-11eb-9d09-4b38ee8e4c39.jpg)

**Comment by PhilippC** [comment] 2021-03-29 10:09
is this a Samsung device?

**Comment by PhilippC** [comment] 2021-03-29 10:11
if you think this is caused by an app update, can you check with an older version from https://github.com/PhilippC/keepass2android/releases?

**Comment by dtwitkowski** [comment] 2021-03-29 16:08
> is this a Samsung device?

Yes, it's a Samsung Note 20 Ultra running OneUI 3.1.  Is there a known issue with Samsung devices?

...dtw

**Comment by wiscor** [comment] 2021-04-04 15:43
I had this issues after transferring data and apps from Google Pixel to a Samsung S21.  I opened the Keepass2Android App properties and cleared cache and storage and then reopened database and everything works fine.

**Comment by jsoberg** [comment] 2021-04-10 23:18
I've also observed this issue on my Samsung Galaxy S20 FE (SM-G781U1/DS). I'm using version 1.08d-r5 of the app, off of Google Play.

**Comment by M4xZ** [comment] 2021-04-27 17:39
Same for me. Both Samsumg S20 and S21.
It wasn't like that at the beginning when I installed the app.
Reinstalled the app and it was solved.  Waiting to see whether it comes back again.

**Comment by PhilippC** [comment] 2021-05-12 03:43
just realized this is a duplicate of https://github.com/PhilippC/keepass2android/issues/1435

**Closed by PhilippC** 2021-05-12 03:43 UTC
