### ISSUE TITLE
Please List on F-Droid!

### ISSUE THREAD

**Issue by cuancena** [PhilippC/keepass2android#1546] opened 2021-01-18 07:19 UTC
Many privacy-concious users do not want Google Play or anything Google related installed on their phones. Since this app is already open source, why not list it on F-Droid?

**Comment by PhilippC** [comment] 2021-01-18 10:27
duplicate of https://github.com/PhilippC/keepass2android/issues/38

**Closed by PhilippC** 2021-01-18 10:27 UTC
