### ISSUE TITLE
Chromebook: how to use a drivepen for the "key-file"?

### ISSUE THREAD

**Issue by Alessandro-2011-11-25** [PhilippC/keepass2android#1852] opened 2021-11-25 08:10 UTC
Premise: I use Keepass on the Windows PC and in addition to the password I insert a drivepen where the file for the additional key-file is stored.

I bought a Chromebook and installed Keepass2android. Everything works but the file opens even after I extract the drivepen! The keyfile remains stored somewhere (I don't know where ...).

For safety, I would like the database to open **ONLY IF** the drivepen is present in the USB port.

How can I delete the org.chromium.arc.volumeprovider / [my_key_file_name. txt] file?
I have nowhere found a way to delete it and it always remains present!

Apart from everything, it is not possible to capture the screen of Keepass2android (key control + shift + keyScreen): a black rectangle always appears! I had to take the photograph ....
.
![2021_11_25_Keepass_Forum](https://user-images.githubusercontent.com/95018596/143403481-28413633-8e54-4ca8-b648-926e17c496d3.jpg)

**Comment by PhilippC** [comment] 2021-11-26 16:38
taking screenshots is disabled by default in the app's display settings (for security reasons).

What you experience is the caching of the keyfile. You can disable caching in the app's setting, but this means you might not have access to your database either, when not connected to the internet (unless your database is stored locally). 

This is a duplicate of https://github.com/PhilippC/keepass2android/issues/1251

**Closed by PhilippC** 2021-11-26 16:38 UTC
