### ISSUE TITLE
[Feature] changeable password generator

### ISSUE THREAD

**Issue by 927589452** [PhilippC/keepass2android#633] opened 2018-12-06 12:38 UTC
It would be nice to provide alternative password generators I a way to easier integrate for example a word based password generator like https://xkpasswd.net/s/

**Comment by lindhe** [comment] 2018-12-09 23:53
I don't see the use for letting the user change generator, but having a passphrase generator like in KeePassXC (on the desktop) would be swell.

**Comment by dave-kennedy** [comment] 2019-07-27 20:11
I'd love to be able to generate a passphrase from the app.

**Comment by PhilippC** [comment] 2019-08-19 09:55
duplicate of https://github.com/PhilippC/keepass2android/issues/284

**Closed by PhilippC** 2019-08-19 09:55 UTC
