### ISSUE TITLE
kdbx is trashed

### ISSUE THREAD

**Issue by cbrims** [PhilippC/keepass2android#1483] opened 2020-11-29 23:34 UTC
I have recently started using KeePass, I use KeePassXC and KeePass2Android. My database is on my Gdrive, when I add anything to the database using KPXC and try to open the database with KP2A I get an error that the database is trashed. I have to completely close the database and re-select the location of the database and key file in order to get the changes to be shown in KP2A. I have the database set as v4 using Argon2. Is there something I am doing wrong or is this just how these 2 programs work together?

**Comment by PhilippC** [comment] 2020-11-30 08:39
duplicate of https://github.com/PhilippC/keepass2android/issues/882

**Closed by PhilippC** 2020-11-30 08:39 UTC
