### ISSUE TITLE
QuickUnlock with finger print sensor not working on Pixel 2

### ISSUE THREAD

**Issue by frimtec** [PhilippC/keepass2android#123] opened 2017-11-19 10:35 UTC
The QuickUnlock with the finger print sensor of the Pixel 2 is not working.

Beside the password input field a red (!) icon is shown.
When tipping the icon the following error message is shown - can not screenshot or copy this message therefore I'm not sure if there are typos in it ;-):
```
Error initializing Fingerprint Unlock:
Java.Lang.RuntimeException: Exception of type 'Jana.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init() [0x000d0] in <...>;0
  at keepass2android.FingerprintDecryption.InitFingerprintUnlock() [0x0015e] in <...>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
  Java.Lang.RuntimeException:: Failed to init Cipher
...
```

**Comment by dixonte** [comment] 2017-11-19 12:16
I have a Pixel 2 XL, and haven't encountered this issue, so it must be specific to the smaller model (which is made by a different manufacturer, btw)

**Comment by frimtec** [comment] 2017-11-19 13:06
Other apps which have support for the finger print sensor work with my pixel 2 withoout issues. 
So it seams to be a problem of keepsass2android in combination with the pixel 2 device :-(

**Comment by dixonte** [comment] 2017-11-19 14:18
That is what I meant, sorry.

**Comment by florianletsch** [comment] 2017-11-19 22:21
I experience the same exception on my Xperia XZ.

I happens after I did a factory reset of my phone and keepass2android was re-installed from Sony's own backup tool.

**Comment by frimtec** [comment] 2017-11-20 17:55
Tried to re-install the app on my pixel 2 as well. But no change - still not working.

**Comment by PhilippC** [comment] 2017-11-25 18:29
duplicate of #37

**Closed by PhilippC** 2017-11-25 18:29 UTC
