### ISSUE TITLE
Allow to disable AutoFill Service

### ISSUE THREAD

**Issue by finsterwalder** [PhilippC/keepass2android#430] opened 2018-06-27 15:31 UTC
I enabled AutoFill on Android 8.
When I check the settings now I see it's enabled. Touching it doesn't do anything.
It would be nice if touching it would take me to the systems settings to disable it.

**Comment by Sinutok** [comment] 2018-07-03 03:06
push.
Same Problem here (Oreo,K2A 1.05e)

**Comment by Small-Ku** [comment] 2019-01-17 17:02
Would it duplicated with #253 ?
BTW, it is solved now. Could you close this issue?

**Comment by PhilippC** [comment] 2019-01-19 11:51
duplicate of #253

**Closed by PhilippC** 2019-01-19 11:51 UTC
