### ISSUE TITLE
"Algorithm negotiation fail" on sftp

### ISSUE THREAD

**Issue by Trallali** [PhilippC/keepass2android#88] opened 2017-11-01 14:57 UTC
I get "Algorithm negotiation fail" on a sftp connection, which has not been changed for months. User+Password are correct, e.g. FileZilla on PC or the sftp-Plugin for TotalCommander on the phone works fine with the same credentials. A new "file open" doesn't work, with the same message. Any idea?
Provider is DomainFactory. Contact me if you want a test account or more information. German is fine.

Thanks

**Comment by pc-coholic** [comment] 2017-11-08 10:42
I can confirm this bug - funnily enough also with DomainFactory...

**Comment by Trallali** [comment] 2017-11-12 16:09
I asked DomainFactory. They updated some server components. Since then, they use stronger SSL ciphers. Which fits with the error message "algorithm negotiatian fail". So please @PhilippC , could you check if support for the stronger ciphers is possible? Which are, according to the [blog entry](https://www.df.eu/forum/threads/81603-Aktualisierung-von-PHP-Apache-und-anderer-Softwarekomponenten-vom-4-10-06-10-2017):
* Ciphers chacha20-poly1305@openssh.com,aes256...cm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
* KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
* MACs hmac-sha2-512-etm@openssh.com,hmac-s...28@openssh.com

Thanks

**Comment by pc-coholic** [comment] 2017-11-12 16:23
I guess, then the problem could be solved by simply updating the JSch-component, which is (iirc) right now at 0.1.50.

According to their [Change-Log](http://www.jcraft.com/jsch/ChangeLog), 0.1.51 and 0.1.52 seem to introduce those missing KexAlgorithms, we're looking for (except for curve).

**Comment by jstachowiak** [comment] 2018-02-21 22:07
Hi! This is also an issue to me. Could you please update JSch to the latest version (0.1.54)? JSch 0.1.50 was released on 2013-05-09 (almost 5 years ago!) and does not support modern TLS/SSL cipher suites. We don't want to use outdated insecure cipher suites.

**Comment by pc-coholic** [comment] 2018-02-25 14:22
There is already #48 on the milestone list for 1.05 that should (hopefully) take care of this issue.

**Comment by B4rc1** [comment] 2022-01-31 21:09
In case someone comes across this like I did:

This happens because in `openssh 8.8p1` `ssh-rsa` got disabled by default. The fix was adding the following to my *servers* sshd config:

```ssh-config
HostKeyAlgorithms +ssh-rsa
PubkeyAcceptedKeyTypes +ssh-rsa
```

**Comment by PhilippC** [comment] 2022-02-07 10:23
just found https://github.com/PhilippC/keepass2android/issues/1812 as a duplicate of this issue. I'm closing this, howevre, because the other one has more upvotes.

**Closed by PhilippC** 2022-02-07 10:23 UTC
