### ISSUE TITLE
support of OneDrive Personal Vault as a place to store the key file

### ISSUE THREAD

**Issue by LubomirH** [PhilippC/keepass2android#991] opened 2019-10-13 14:14 UTC
Hi,
I am new to KeePass, so it might be I am missing some knowledge.
I have set up my desktop KeePass the way that the key file which is used together with master password to open the database is saved in the Personal Vault which is now part of the OneDrive service.
But when I try to browse the key file while opening a DB with your app, there is no way to find the Personal Vault folder on OneDrive, it doesn't work with your OneDrive file picker neither with the system one. 
It would be great if you could look in to it and fix your picker before the system one is fixed.

thanks in advance

LH

**Comment by PhilippC** [comment] 2019-10-15 08:48
Duplicate of #972.

**Closed by PhilippC** 2019-10-15 08:48 UTC
