### ISSUE TITLE
KP2A keyboard always auto submit

### ISSUE THREAD

**Issue by Draic** [PhilippC/keepass2android#252] opened 2018-02-11 19:09 UTC
KP2A keyboard always presses submit when I use it to fill in a username. I am forced to first enter the password and then the username because of that. There is no option anywhere to disable this.

Pixel 2 running 8.1.0

**Comment by PhilippC** [comment] 2018-02-12 07:36
duplicate of #151

**Closed by PhilippC** 2018-02-12 07:36 UTC
