### ISSUE TITLE
System File Picker - Onedrive (via MS app) is seen as read only

### ISSUE THREAD

**Issue by cjk28** [PhilippC/keepass2android#1531] opened 2021-01-11 10:20 UTC
With onedrive app installed, you can access files in there via the system file picker (I'm on android 10).
KeepassDX can successfully use this as a means to sync your database (RW), without needing to have its own onedrive login implementation.
Keepass2Android determines that this method of access is read only.
Perhaps it's worth considering using this as the primary method of onedrive access if this read-only behaviour can be addressed.
This would solve some issues like: https://github.com/PhilippC/keepass2android/issues/1038
I'm not sure what the minimum version of android is for this system file picker linking is though, so it might only be useful for newer devices.
Despite not liking microsofts apps, this is probably a neater way of doing it, and potentially better from a cyber security point of view.

**Comment by jryberg** [comment] 2021-01-31 18:30
It's the same for files opened from Nextcloud. It's opened fine but it's not possible to save without exception

**Comment by PhilippC** [comment] 2021-02-19 07:45
duplicate of https://github.com/PhilippC/keepass2android/issues/1212

**Closed by PhilippC** 2021-02-19 07:45 UTC
