### ISSUE TITLE
Enhancement - pronounceable password

### ISSUE THREAD

**Issue by sinavir** [PhilippC/keepass2android#255] opened 2018-02-13 15:58 UTC
I think the app should have a "pronounceable" password generating function. I know it is difficult to develop but it could be interesting when you want a password you can remember.

**Comment by Karreg** [comment] 2018-02-13 16:02
I'm curious about your use case. The point of using a password manager is to avoid having to remember passwords, hence having more secure passwords. What would be the case to have to remember a password is you use a password manager?

Also about the feature itself, seems pretty hard, since rules about "pronounceable" password are not the same depending on the language. It would be a great research subject for a language research team :)

**Comment by sinavir** [comment] 2018-02-23 06:38
In some cases it is useful to remember a password when you haven't got your database (or your phone) with you.

To be more concrete, I had to put an rememberable password for my drive account because I can't use my phone at school. An other case is when you want to generate the database's main password.

About the hardness of developing this feature, I thought that the generation could be done in two steps :
     1. Generate randomly a vowel and consonant sound pattern (but how I haven't any idea)
     2. Put randomly the sounds

**Comment by xgpt** [comment] 2018-02-26 21:38
Google: Correct horse battery staple. There's a web generator I'd like to see implemented as inspiration. Keepass XC also has something very similar..

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2019-02-16 19:53
Keepass have plugin pronounceable password and
"Correct horse battery staple" as plugin wurfelware

https://www.xkcd.com/936/

**Comment by PhilippC** [comment] 2019-09-08 04:33
duplicate of #284 (this one was created earlier, but #284 has more up-votes)

**Closed by PhilippC** 2019-09-08 04:33 UTC
