### ISSUE TITLE
Failure to load running on chromebook

### ISSUE THREAD

**Issue by rwf1** [PhilippC/keepass2android#1917] opened 2022-01-24 02:26 UTC
A recent update has left the app unusable on a Chromebook.  When I try to open a data base that uses a key file after entering the password it pops up a window the says "Working... Loading database... (Parsing database...)".  It stays in that state forever.  This is version 1.09c-r0 of keepass2android and version 97.0.4692.91 of Chrome OS.

**Comment by PhilippC** [comment] 2022-01-24 07:36
duplicate of #1884

**Closed by PhilippC** 2022-01-24 07:36 UTC

**Comment by waaweech** [comment] 2022-01-24 15:36
> A recent update has left the app unusable on a Chromebook. When I try to open a data base that uses a key file after entering the password it pops up a window the says "Working... Loading database... (Parsing database...)". It stays in that state forever. This is version 1.09c-r0 of keepass2android and version 97.0.4692.91 of Chrome OS.

@rwf1 - I've the same issue and have opened https://github.com/PhilippC/keepass2android/issues/1884 

I'm currently using a workaround which is: 
After a few seconds when it says "Working... Loading database... (Parsing database...)", try to minimize the KP2A window and then maximize it. This opens the DB for me immediately. Try and confirm if it works for you too.

However, while the KP2A Online version is currently experiencing this issue, the KP2A Offline version opens the same DB immediately with no problem.

**Comment by rwf1** [comment] 2022-01-24 15:53
First I need to apologize for creating a duplicate thread.  I searched on Google but failed to search within this forum before posting.  The workaround is effective for me.
