### ISSUE TITLE
I want the language switch button

### ISSUE THREAD

**Issue by Ngchpr** [PhilippC/keepass2android#1878] opened 2021-12-27 15:57 UTC
Because the language is not really complete.  Specifically Vietnamese.  Should use even more difficult than English.  I would like to ask for the language switch button on the new version.  To use English.  Thank you

**Comment by PhilippC** [comment] 2021-12-29 11:24
duplicate of #201

**Closed by PhilippC** 2021-12-29 11:24 UTC

**Comment by Ngchpr** [comment] 2021-12-29 23:23
Thank you so much for listening to us.  From Vietnam
