### ISSUE TITLE
[FEAT] Android 14 Credential Manager

### ISSUE THREAD

**Issue by dbrand666** [PhilippC/keepass2android#2337] opened 2023-05-13 15:23 UTC
I just saw an article that says Android 14 will have a credential manager and they expect 1Password, Dashlane, Keeper, and Okta to support it at launch.

https://android-developers.googleblog.com/2023/02/bringing-together-sign-in-solutions-and-passkeys-android-new-credential-manager.html

Does KP2A have a place in that ecosystem?

**Comment by PhilippC** [comment] 2023-05-15 06:26
Seems like this definitely should be supported. Unfortunately, the linked dev guide (https://developer.android.com/training/sign-in/passkeys) only provides information on how to use this API as a consumer, not a provider of passwords. And I think Android 14 is not yet supported by Xamarin at present.

**Comment by madkai93** [comment] 2023-07-28 20:24
Seems like Google put this in beta now. Maybe it´s worth a look again?
https://android-developers.googleblog.com/2023/07/credential-manager-beta-easy-secure-authentication-with-passkeys-on-android.html

**Comment by patricksadowski** [comment] 2023-08-01 21:05
Here is guidance on integrating Credential Manager with other credential providers like Keepass: https://developer.android.com/training/sign-in/credential-provider

This issue seems to be a duplicate of #2099

**Comment by boergondier** [comment] 2023-10-12 09:36
+1

**Comment by juanhs12** [comment] 2023-10-26 23:42
The latest beta version of KeepassXC have the possibility of to do import and export passkeys.

The pull request with the WebAuthn was accept today, 26 october 2023.

https://snapshot.keepassxc.org/latest/

https://github.com/keepassxreboot/keepassxc/pull/8825

**Comment by F3000** [comment] 2023-10-31 00:49
> The latest beta version of KeepassXC have the possibility of to do import and export passkeys.
> 
> 
> 
> The pull request with the WebAuthn was accept today, 26 october 2023.
> 
> 
> 
> https://snapshot.keepassxc.org/latest/
> 
> 
> 
> https://github.com/keepassxreboot/keepassxc/pull/8825

So wen can expect a full release in the near future ?

**Comment by juanhs12** [comment] 2023-10-31 20:58
> > The latest beta version of KeepassXC have the possibility of to do import and export passkeys.
> > The pull request with the WebAuthn was accept today, 26 october 2023.
> > https://snapshot.keepassxc.org/latest/
> > [keepassxreboot/keepassxc#8825](https://github.com/keepassxreboot/keepassxc/pull/8825)
> 
> So wen can expect a full release in the near future ?

In KeepassXC will be in the next release, but in Keepass2Android we have to pray and send energies to @PhilippC. 
I will pay some beers to someone who implement it on android.

**Comment by PhilippC** [comment] 2023-11-13 09:18
closing as duplicate of #2099

**Closed by PhilippC** 2023-11-13 09:19 UTC
Labels: enhancement
