### ISSUE TITLE
quick unlock fingerprint doesn't work the first time

### ISSUE THREAD

**Issue by jeroen7s** [PhilippC/keepass2android#20] opened 2017-10-03 08:18 UTC
when i open the app (from autofill notification or otherwise) i press the fingerprintsensor/home key. 
what happens then is i either go to my home screen or open google assistant.
if i open k2a again from the homescreen or close google assistant and then press the fingerprint sensor it does detect it correctly and open my vault

**Comment by PhilippC** [comment] 2017-10-04 16:58
duplicate of #3

**Closed by PhilippC** 2017-10-04 16:58 UTC
