### ISSUE TITLE
[BUG] Fingerprint Sensor not found after upgrade to Android 14

### ISSUE THREAD

**Issue by AndreasS71** [PhilippC/keepass2android#2432] opened 2023-10-06 15:00 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I use a Google pixel 7 pro and upgrade to Android 14

Now keepass doesn't find the fingerprint sensor

### Describe what you expected to happen:

Unlock with biometric fingerprint 

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

14

**Comment by AndreasS71** [comment] 2023-10-07 21:35
Not a bug, android 14 brings a new option for biometric for apps. This was not activated

**Comment by Spiralpine** [comment] 2023-10-07 21:55
Interesting. Would you elaborate?  Does this new option need to be turned on by the user or the KP2A developer?

**Comment by AndreasS71** [comment] 2023-10-08 08:52
![Screenshot_20231008-105058](https://github.com/PhilippC/keepass2android/assets/147176365/3335aac9-5fda-4bac-a464-1123ebc03ec4)



The setting must be made by the user.

Is the last button (see picture)

**Comment by Spiralpine** [comment] 2023-10-08 13:54
@AndreasS71 - Thanks for stepping in. That last setting is not unique to Android 14.  Android 13 has the same setting. So, nothing new here.

By the way,  since this is not a bug with Keepass2Android app, if you like, you can close this issue :-)

**Closed** 2023-10-08 14:46 UTC
Labels: bug

**Comment by maricn** [comment] 2024-04-10 15:20
Same issue here, upgraded lineageos 20 to 21 on Pixel 6 Pro, and fingerprint sensor stopped working only in this app.

Regarding the screenshot above, I can't find that menu, I checked my security and privacy settings, and fingerprint settings, but everything seems fine and other apps use it properly.

When I click on Biometric Unlock button, a toast notification pops up:
> Invalid argument (internal Keystore code: - 38
> message system/security/keystore2/src/securi...

(can't see the whole text of the notification, that's all i see)
