### ISSUE TITLE
Add a setting to force Merge Synchronisation instead of prompting the user each time.

### ISSUE THREAD

**Issue by TheBliTzzzzzz** [PhilippC/keepass2android#1302] opened 2020-06-27 16:24 UTC
I often update my KeePass database on my PC, and then press "Synchronize Database" in the app in order to synchronise the databases. It will prompt asking to Merge, Overwrite or Cancel, and I wish there was a setting to force Merge every time, as this prompt gets quite annoying. [It's available on KeePass 2](https://i.imgur.com/gHn2x9h.pngl), and is an incredibly handy little feature I would love to see added.

This may be a duplicate of #1218 but I never saw a response.

**Comment by PhilippC** [comment] 2020-06-28 18:42
duplicate of #1218

**Closed by PhilippC** 2020-06-28 18:42 UTC
