### ISSUE TITLE
Not working with DEX on Samsung Galaxy S9

### ISSUE THREAD

**Issue by bazhub** [PhilippC/keepass2android#779] opened 2019-04-07 11:29 UTC
keepass2android doesn't start in DEX mode on Samsung Galaxy S9 (Android 9).

**Comment by Small-Ku** [comment] 2019-04-08 05:17
Would #625 helps?

> just one thing you might try is to disable the "screen protection" in the app settings. Maybe this causes this behavior.

If not, please provide debug log.

**Comment by fcrozat** [comment] 2019-05-01 07:48
duplicate of #625

**Closed** 2019-08-05 04:27 UTC
