### ISSUE TITLE
Cant Open Database stored in PCloud.

### ISSUE THREAD

**Issue by centinal-centinal** [PhilippC/keepass2android#1480] opened 2020-11-25 02:51 UTC
![Screenshot_20201124-204510_Keepass2Android](https://user-images.githubusercontent.com/45610680/100176761-7d793680-2e96-11eb-9aa4-ce82646a62c7.jpg)
![Screenshot_20201124-204455_Keepass2Android](https://user-images.githubusercontent.com/45610680/100176774-8407ae00-2e96-11eb-83ed-a9cf6905c920.jpg)
![Screenshot_20201124-204440_Keepass2Android](https://user-images.githubusercontent.com/45610680/100176785-8833cb80-2e96-11eb-9a67-35cd5a618ec8.jpg)

When I moved my database over to PCloud and then tried to open it would not allow me to. I ended up just using dropbox again since that works like a charm.

Thanks  for the App its some great stuff!

**Comment by PhilippC** [comment] 2020-11-30 08:51
duplicate of https://github.com/PhilippC/keepass2android/issues/1257

**Closed by PhilippC** 2020-11-30 08:51 UTC
