### ISSUE TITLE
v1.09e-r3 NoNet crashes when I tap on the "User Name" value both when I edit an existing entry and also when I create a new entry

### ISSUE THREAD

**Issue by FranLa** [PhilippC/keepass2android#2281] opened 2023-03-18 15:20 UTC
v1.09e-r3 nonet crashes when I as the first thing during edit tap on the "User Name" value - both when I edit an existing entry and also when I create a new entry.

If I tap any other field / value **before** I tap the "User Name" value it works fine. So fortunately there is this circumvention

So: 
1) Open an entry - switch to edit mode - tap on 'User name' value: Crash
2) Open an entry - switch to edit mode - tap on any field except for 'User name' and **then** tap on 'User name' : Works - no crash

I have seen this on two phones : Oneplus 5 (Android 10) and Nokia 5.4 (Android 12)

This problem **only** happen in the '**NoNet**' version - when I try this with the 'Net' version it doesn't crash

**Comment by uli-on** [comment] 2023-03-18 15:42
Same here, on Android 10, though. Error log (caught with the Scoop app) follows:

```
FATAL EXCEPTION: main
Process: keepass2android.keepass2android_nonet, PID: 27297
android.runtime.JavaProxyThrowable: System.ArgumentException: An item with the same key has already been added. Key: keepass2android.services.AutofillBase.ViewNodeInputField
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x0015a] in <8c1f40060880450f83bb90f0629b1667>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <8c1f40060880450f83bb90f0629b1667>:0 
  at Kp2aAutofillParser.StructureParserBase`1[FieldT].Parse (System.Boolean forFill, System.Boolean isManualRequest, Kp2aAutofillParser.AutofillView`1[TField] autofillView) [0x002d2] in <9d921e539c20416fbc81d0c3c5afc0c5>:0 
  at keepass2android.services.AutofillBase.StructureParser.Parse (System.Boolean forFill, System.Boolean isManualRequest, Kp2aAutofillParser.AutofillView`1[TField] autofillView) [0x00000] in <2c79b7425a854bebbd39062e5dbd2d83>:0 
  at keepass2android.services.AutofillBase.StructureParser.ParseForFill (System.Boolean isManual) [0x00018] in <2c79b7425a854bebbd39062e5dbd2d83>:0 
  at keepass2android.services.AutofillBase.AutofillServiceBase.OnFillRequest (Android.Service.Autofill.FillRequest request, Android.OS.CancellationSignal cancellationSignal, Android.Service.Autofill.FillCallback callback) [0x0009f] in <2c79b7425a854bebbd39062e5dbd2d83>:0 
  at Android.Service.Autofill.AutofillService.n_OnFillRequest_Landroid_service_autofill_FillRequest_Landroid_os_CancellationSignal_Landroid_service_autofill_FillCallback_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_request, System.IntPtr native_cancellationSignal, System.IntPtr native__callback) [0x00020] in <e74dcf35373743e2bbf871ba34f3d1e2>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_V (_JniMarshal_PPLLL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0, System.IntPtr p1, System.IntPtr p2) [0x00005] in <e74dcf35373743e2bbf871ba34f3d1e2>:0 
	at crc6402e1bf64a3331322.AutofillServiceBase.n_onFillRequest(Native Method)
	at crc6402e1bf64a3331322.AutofillServiceBase.onFillRequest(AutofillServiceBase.java:42)
	at android.service.autofill.-$$Lambda$I0gCKFrBTO70VZfSZTq2fj-wyG8.accept(Unknown Source:8)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:300)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

**Comment by PhilippC** [comment] 2023-03-19 09:06
can you please verify that this is fixed in https://github.com/PhilippC/keepass2android/releases/tag/v1.09e-r5?

**Comment by FranLa** [comment] 2023-03-19 09:26
I can confirm that the problem is solved (tested both on Android 10 and 12). Great - thanks for the quick follow up and fix :-)

**Comment by tome9111991** [comment] 2023-03-19 11:39
I still have a crash with the r5 but it has gotten better. can't reproduce it yet.

**Comment by uli-on** [comment] 2023-03-19 12:50
Tried around a dozen times and not crashing any more. Thanks, Philipp!

**Closed** 2023-03-19 18:41 UTC
