### ISSUE TITLE
URL are replaced by ANDROIDAPP

### ISSUE THREAD

**Issue by chrisbiomed** [PhilippC/keepass2android#861] opened 2019-07-05 11:24 UTC
Hello, in keepass2andrdoid the field "URL" is completed by ANDROIDAPP://toto.com instead of "http://toto.com" which is unusable on a personnel computer under Linux or Windows.
Is it possible to use another field to stock this information instead of URL field ?

thanks

**Comment by temoto** [comment] 2019-07-11 17:55
Duplicate of https://github.com/PhilippC/keepass2android/issues/531

**Closed** 2019-08-18 19:37 UTC
