### ISSUE TITLE
Can't fetch password db via WebDAV

### ISSUE THREAD

**Issue by levinus** [PhilippC/keepass2android#116] opened 2017-11-13 20:22 UTC
hey,
I can't get the latest version of my password db via WebDAV since the latest Play Store Beta version. I use a Seafile server with seafdav. WebDAV worked all the time for me until now. Caching works, I can use the old one but that doesn't really help me in this case. Every time the app tries to get the file this strange java error appears:
![screenshot_20171113-210817](https://user-images.githubusercontent.com/12646813/32747254-7b1a8926-c8b8-11e7-95b5-cf9b05120dcd.png)
If anyone needs the translation I can provide it but I think Philipps German is perfectly fine :)
Im on a Nexus 5X with Android 8.0.

**Comment by PhilippC** [comment] 2017-11-13 21:12
duplicate of #114

**Closed by PhilippC** 2017-11-13 21:12 UTC
