### ISSUE TITLE
[BUG] Title doesn't resolve references

### ISSUE THREAD

**Issue by cap1024** [PhilippC/keepass2android#2470] opened 2023-11-25 13:32 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

The title field doesn't resolve references in a list of database entries:

Related issue: #1327 

![image](https://github.com/PhilippC/keepass2android/assets/5022086/0cb0c03c-ee60-49c6-bbde-09dc759de041)

### Describe what you expected to happen:

The title is shown with resolved references.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

13

**Comment by PhilippC** [comment] 2024-01-02 20:02
treating this a duplicate of #1327 for which I just pushed a fix

**Closed by PhilippC** 2024-01-02 20:02 UTC
Labels: bug

**Comment by cap1024** [comment] 2024-01-26 08:10
Hello, @PhilippC !
Does v1.10-pre contains a fix for this issue?
