### ISSUE TITLE
Database name

### ISSUE THREAD

**Issue by peteraarum** [PhilippC/keepass2android#458] opened 2018-07-17 06:20 UTC
Since last update I cannot synchronize the database. The app says that the name is null. I have a name in dialog.

**Comment by PhilippC** [comment] 2018-07-17 19:48
duplicate of #432, see https://github.com/PhilippC/keepass2android/issues/432#issuecomment-401561254 for how to resolve.

**Closed by PhilippC** 2018-07-17 19:48 UTC
