### ISSUE TITLE
Make URL links inside notes clickable and text inside notes selectable.

### ISSUE THREAD

**Issue by gio-vanni** [PhilippC/keepass2android#1328] opened 2020-07-20 01:05 UTC
Currently only the entire "Notes" field can be copied to clipboard. Is it possible to make links inside notes clickable?
Also, is it possible to make parts of the text inside Notes selectable, instead of the entire Note?

**Comment by PhilippC** [comment] 2020-07-20 07:17
duplicate of https://github.com/PhilippC/keepass2android/issues/689

**Closed by PhilippC** 2020-07-20 07:17 UTC
