### ISSUE TITLE
keepass2android doesn't start in Samsung DeX mode

### ISSUE THREAD

**Issue by fcrozat** [PhilippC/keepass2android#625] opened 2018-11-28 16:59 UTC
When trying to start keepass2android on Galaxy Tab S4 (Oreo 8.1) in DeX mode (https://developer.samsung.com/samsung-dex) , it is refused by the system. It is not clear why, but it could be some missing requirements in the manifest.

Everything is explained on https://developer.samsung.com/samsung-dex/modify-optimizing

**Comment by bazhub** [comment] 2019-03-02 11:20
I've a Samsung Galaxy S9. It's not working there in DeX mode, too. Would be very cool if you could fix this.

**Comment by PhilippC** [comment] 2019-03-23 18:25
I purchased the required hardware to troubleshoot this but cannot reproduce. Are you running Android 8 or 9? My S8 with Android 9 works fine.

**Comment by raregtp** [comment] 2019-03-23 20:00
I'm using a Tab S4 and switching into Dex mode when I get the message.

Matt

________________________________

**Comment by raregtp** [comment] 2019-03-24 15:27
Apologies on my last reply.....should have gave you more info.  My Tab S4 is currently on Android 8.1....trying to launch the app generates a message that it cannot run in Dex mode and to try running in tablet mode.  Tablet mode of course works fine.

Let me know if you have any beta releases I can test for you....happy to help out.

**Comment by PhilippC** [comment] 2019-03-25 07:34
just one thing you might try is to disable the "screen protection" in the app settings. Maybe this causes this behavior. Apart from that, I would suggest you wait for Android 9 which I think should be rolled out at some time: https://tabletmonkeys.com/samsung-galaxy-tab-s4-android-9-0-pie-update-officially-certified-today/

**Comment by raregtp** [comment] 2019-03-25 17:07
No go….I’m assuming you’re talking about the setting to prevent copying the screen??

Thanks!!

Matt

**Comment by raregtp** [comment] 2019-04-24 19:51
Just updated my Tab S4 to Android 9.....no change in this issue.  I've tried with screen protection enabled and disabled.  Thanks!

**Comment by tturner** [comment] 2019-04-27 12:28
I am having the same issue. I attach logs. One with the screen protect setting on and one with it off. It doesn't work in either mode.

[keepass_dex_screen_protect_off.log](https://github.com/PhilippC/keepass2android/files/3123865/keepass_dex_screen_protect_off.log)
[keepass_dex_screen_protect_on.log](https://github.com/PhilippC/keepass2android/files/3123866/keepass_dex_screen_protect_on.log)

The error is a toast that pops up saying "Keepass2Android cannot run in Samsung Dex. Try running in phone mode."

Based on the fact that this text does not appear in the Keepass2Android source code, I assume that Samsung Dex is checking something about the Keepass2Android application and deciding it is not compatible.

It would be really nice if it was possible to figure out what the issue is so we can run the application in Dex mode.

Let me know if there is further testing or logging that I can do to help identify the issue.

**Comment by tturner** [comment] 2019-04-27 12:36
Forgot to mention I'm using a Samsung Galaxy S9 running Android 9

**Comment by fcrozat** [comment] 2019-05-01 07:49
Samsung DeX seems to disable all keyboard applications except Samsung one. I wonder if a keepass2android build with keyboard disabled would work

**Comment by raregtp** [comment] 2019-05-01 09:13
Seems reasonable.....I can certainly try it out if you want to do a test build.  Assuming that outside of the Dex environment there would be no input available within Keepass2android?  At least with the test build?

Matt

________________________________

**Comment by fcrozat** [comment] 2019-05-01 12:49
That would be acceptable. On Pie, autofill password Api makes keyboard almost useless..

**Comment by vitordapper** [comment] 2019-05-29 18:19
> I purchased the required hardware to troubleshoot this but cannot reproduce. Are you running Android 8 or 9? My S8 with Android 9 works fine.

Just to add to this discussion, I think I got why it is working for some people but not for others (still dont know how to fix it): it works when using Dex on the extended display (probably because the tablet/phone stays in normal mode and therefore there is no conflict with Dex); however if you use your tablet alone (no extra display, meaning your tablet display will be in Dex mode) then the issue occurs and you can not select any input method other than the Samsung one. I guess that is why some people are not seeing this issue, because if you have a galaxy phone, you wouldnt have this stand-alone option and so it works just fine.

**Comment by finndo77** [comment] 2019-09-14 02:51
Chiming in here, just got a galaxy tab S6 with the keyboard case and the issue occurs on it as well. My USB-c to hdmi cable is at home and I'm at work now, but will test for external display issues and report back.

Android version 9
Samsung Galaxy Tab S6  SM-T860
Works when not in DeX mode only
Tested using POGO attached physical KB
Tested without POGO KB also

Was trying to setup a laptop replacement configuration for doing lite work

**Comment by chris5a** [comment] 2019-12-04 22:36
I have the same issue with Samsung Galaxy S10+ running Android Version 9.
It would be great if this program worked in DeX mode.
Thanks

**Comment by solarelf** [comment] 2019-12-28 10:43
On startup, any build crashes with message “This app cannot run in DeX, please try tablet mode”. I understand the issue is not looking as on the top of priority but could you please add it on the list to fix the app manifest to allow KP2A for Samsung DeX users where it is HIGHLY appreciated?

Thank you!

P.S. Works for OneUI 1.1 (ordinary tablet) shell. From my experience in porting to DeX, the app manifest must be updated to allow KP2A to start.

@PhilippC

**Comment by solarelf** [comment] 2019-12-28 10:45
> > I purchased the required hardware to troubleshoot this but cannot reproduce. Are you running Android 8 or 9? My S8 with Android 9 works fine.
> 
> Just to add to this discussion, I think I got why it is working for some people but not for others (still dont know how to fix it): it works when using Dex on the extended display (probably because the tablet/phone stays in normal mode and therefore there is no conflict with Dex); however if you use your tablet alone (no extra display, meaning your tablet display will be in Dex mode) then the issue occurs and you can not select any input method other than the Samsung one. I guess that is why some people are not seeing this issue, because if you have a galaxy phone, you wouldnt have this stand-alone option and so it works just fine.

Yes, it seems this is the case. The Manifest might need some fixing.

**Comment by PhilippC** [comment] 2020-01-03 19:43
@solarelf  it's not clear to me what step to take according to your link. It says that you should not use something like
`<uses-feature  android:name="android.hardware.touchscreen"  android:required="true" />`
but I don't have that in the manifest. Any idea?

**Comment by RolandSM** [comment] 2020-01-09 09:28
Hello, 
I am on a Galaxz S10+ With Andoird 10 and same error. 
Will a fix come or is in meantime an existing workaround for

**Comment by gpion** [comment] 2020-02-23 07:12
Galaxy S9 here, Android 10.
Similar (but not exactly same) error:
![image](https://user-images.githubusercontent.com/2971216/75105437-8b521080-5613-11ea-9674-6efd5839ae8f.png)


Full text

> L'écran actuellement valide riest pas marqué comme sécurisé. Cela signifie que des captures d'écran peuvent être prises par d'autres applications. 
Keepass2Android est configuré pour afficher des informations sensibles sur les écrans sécurisés uniquement. Veuillez changer pour un écran 
sécurisé (par exemple en détachant un moniteur HDMI) ou modifier les paramètres de l'application. 

(sorry my setup is in French, Google translate should give approximately equivalent English error text)

**Comment by gpion** [comment] 2020-02-23 07:27
> I'm unable to find which setting I have to change.

Found, this has to be unchecked:
![settings form](https://i.imgur.com/lU5eEgV.png)

BTW you should really re consider adding app language selection as requested here: #201 
That would really help users with non English default languages to do better reports

**Comment by Schwefelholz** [comment] 2020-02-29 15:40
> > I'm unable to find which setting I have to change.
> 
> Found, this has to be unchecked:
> ![settings form](https://camo.githubusercontent.com/f4636aba8e05953c604d58000ffdb4be6482c6e8/68747470733a2f2f692e696d6775722e636f6d2f6c5535654567562e706e67)
> 


This actually doesn't make any difference for me (Galaxy Tab S6 in Dex mode)...

**Comment by Schwefelholz** [comment] 2020-03-01 09:20
I got it working on DeX once I enabled DeX Developer Options...

**Comment by finndo77** [comment] 2020-05-26 04:03
I have found that if you are using an external display for DEX (tested with my Galaxy Tab S6) you CAN open Keepass2android on the "internal" display and use the copy paste feature to enter information into the DEX screen. as you can use "phone" apps on the main device screen while DEX runs on the external screen (at least on the TabS6)

**Comment by TraderDom** [comment] 2020-07-03 14:32
S20 Ultra Exynos, Android 10, One UI 2.1
Dex Developer Options turned on.
Disabled Protect Data Display (K2A Settings > Display > Protect Data Display)
K2A still won't launch in Dex mode on external display. 
Error -  "Keepass2Android cannot run in Samsung Dex. Try running in phone mode."

**Comment by Napsterbater** [comment] 2021-02-07 19:09
Samsung Galaxy Tab S4 Latest Updates as of this post.

Setting Force Resize (I already had this set so not sure if it was still required)
And Disabling K2A's Autofill and/or Simple Keyboard options.

This allowed K2A to open in Dex Mode.

**Comment by fcrozat** [comment] 2021-02-08 22:31
> Samsung Galaxy Tab S4 Latest Updates as of this post.
> 
> Setting Force Resize (I already had this set so not sure if it was still required)
> And Disabling K2A's Autofill and/or Simple Keyboard options.
> 
> This allowed K2A to open in Dex Mode.

I just tried (Galaxy Tab S4) and it is still impossible.

Could you share which firmware on Tab S4, which version of K2A and exactly which settings allow to start it in DeX mode ?

**Comment by Klinghust** [comment] 2021-02-20 19:42
Thanks @Schwefelholz 

I too had the same problem...

Fix:
Enable DeX Developer Options to make it work in Dex.
How to:
https://youtu.be/nXTOfxF-wnw

**Comment by hojjatabdollahi** [comment] 2021-06-26 03:24
I also had the same issue on Tab S7 with the keyboard cover Dex mode.
I enabled the Developer mode and it got fixed.

**Comment by daemoniac** [comment] 2021-07-21 12:27
Hi, I had the same issue on Galaxy Tab S7+ 5G with Android 11 and DEX 4.0.02.12.

I did the following two changes:
1. enable developer mode in dex (see youtube link above)
2. open K2A in tablet mode, open the database -> Settings -> Application -> Display -> disable "Protect Database"

(hope the translation is correct, I use it with german language and it is "Einstellungen -> Anwendung -> Anzeige -> Datenbankanzeige schützen".)

Now K2A also works in DEX.

Thanks for the help!

**Comment by PhilippC** [comment] 2022-01-15 14:24
I'm closing this as there is a workaround (enabling Dex dev options) and I consider this an issue in Samsung's policies and not in KP2A

**Closed by PhilippC** 2022-01-15 14:24 UTC

**Comment by micsutka** [comment] 2022-03-26 20:04
three steps must be taken in order to enable K2A on samsung DEX:
1. enable developer mode in dex (see youtube link above)
2. open K2A in tablet mode, open the database -> Settings -> Application -> Display -> disable "Protect Database"
3. reboot dex
4. in dex mode open settings -> "samsung dex" -> "Samsung LABS" ->  Enable checkbox "Force Resize"
