### ISSUE TITLE
"Algorithm negotiation fail" on sftp connection

### ISSUE THREAD

**Issue by 3zra** [PhilippC/keepass2android#198] opened 2018-01-07 13:47 UTC
I'm getting an "Algorithm negotiation fail" error message, when trying to sftp connect to a database file that is hostet by an SSH server on my home PC running a debian based OS (https://osmc.tv/).

host PC information:
`osmc@osmc:~$ uname -a
Linux osmc 4.9.29-10-osmc #1 SMP PREEMPT Mon Oct 9 02:18:18 UTC 2017 armv7l GNU/Linux`
`osmc@osmc:~$ ssh -V 
OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016`

Any ideas on how to solve this issue?
Thanks in advance.

**Comment by PhilippC** [comment] 2018-01-07 20:28
duplicate of #88

**Closed by PhilippC** 2018-01-07 20:28 UTC
