### ISSUE TITLE
[BUG] Doesn't work in Samsung Dex

### ISSUE THREAD

**Issue by DAE51D** [PhilippC/keepass2android#2700] opened 2024-11-01 06:09 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I was in Samsung Dex mode and tried to open my favorite password manager only to be created with this message which seems bizarre since why would it care that it's index mode or not?

![Screenshot_20241031-230235_Samsung DeX home](https://github.com/user-attachments/assets/b7cb262f-ff95-4580-8e3e-fb9bf53a166c)

### Describe what you expected to happen:

it should just load like any other app does

### What version of Keepass2Android are you using?

1.11-r0

### Which version of Android are you on?

Android 12. oneUI 4.1.1

**Comment by PhilippC** [comment] 2024-11-05 08:21
duplicate of https://github.com/PhilippC/keepass2android/issues/625

**Closed by PhilippC** 2024-11-05 08:21 UTC
Labels: bug
