### ISSUE TITLE
use OneDrive2 will show login page sometimes.

### ISSUE THREAD

**Issue by CzBiX** [PhilippC/keepass2android#1236] opened 2020-05-01 03:58 UTC
After I switch to OneDrive2 protocol from OneDrive, There is a chance k2a will pop a browser with MS login page after I typed password to unlock database. I can directly close the browser and wait for database opened without issue.
The login page probably pop out one time per day.

**Comment by PhilippC** [comment] 2020-05-01 17:18
duplicate of #1038

**Closed by PhilippC** 2020-05-01 17:18 UTC
