### ISSUE TITLE
white text on white background search results 

### ISSUE THREAD

**Issue by SirLogician** [PhilippC/keepass2android#1696] opened 2021-05-24 21:49 UTC
I am using 1.08dr5 version on Samsung s20 phone and when I search a keyword, ajax search results prefilled are displayed with white font on a white background so, they are not readable. they work if you click on them but you can't see what they are.

changing skin to light or dark does not fix the issue

**Comment by PhilippC** [comment] 2021-05-26 19:00
duplicate of #1435

**Closed by PhilippC** 2021-05-26 19:00 UTC
