### ISSUE TITLE
Add support for new KDBX 4.1 file format

### ISSUE THREAD

**Issue by SnoutBaron** [PhilippC/keepass2android#1712] opened 2021-06-18 15:24 UTC
KDBX 4.1 was introduced with KeePass 2.48. The developer has not made it default as of yet to allow time for developers of major alternative clients to update their projects and add the new format.

Please add the new format to KeePass2Android.

Thanks.

https://keepass.info/help/kb/kdbx_4.1.html

**Comment by PhilippC** [comment] 2021-07-03 10:57
duplicate of #1670 , already implemented and in beta

**Closed by PhilippC** 2021-07-03 10:57 UTC
