### ISSUE TITLE
Cannot unlock Android with fingerprint if app is topmost active while locked

### ISSUE THREAD

**Issue by rpresser** [PhilippC/keepass2android#1125] opened 2020-01-22 17:16 UTC
Device: Nokia 6.1 (TA-1045)
Carrier: Cricket (AT&T)
Android version: 9 (build 00WW_3_54H_SPO4)
Keepass2Android version: 1.07b-r0
Installed through Google Play Store

Scenario:
My database, encrypted only by password, is open but locked.
QuickUnlock is enabled and ready to unlock the database.
The app is running and on the screen at the time that Android locks.

Problem:
When I pick up the locked device and put my finger on the fingerprint reader, nothing happens. It should have unlocked the device. I had to use password to unlock instead.

**Comment by vepman** [comment] 2020-01-30 15:54
Device: SM-T865 
Android 9
Same to me. Fingerprint Readers doesn't work.

**Comment by rpresser** [comment] 2020-01-31 18:14
> Device: Nokia 6.1 (TA-1045)
> Android version: 9 (build 00WW_3_54H_SPO4)

> When I pick up the locked device and put my finger on the fingerprint reader, nothing happens. It should have unlocked the device. I had to use password to unlock instead.

For what it's worth: After receiving the Android 10 upgrade on my Nokia 6.1, **this is no longer a problem.**  Fingerprint unlock is now working correctly.

**Comment by nift4** [comment] 2020-02-02 06:45
Use the recents to quit the app and go again in. Then it should work.

**Comment by vepman** [comment] 2020-02-02 08:20
No, unfortunately version keepass2android-1.08-pre3 doesn't work either.

**Comment by t-p-tan** [comment] 2020-04-08 12:32
Device: Asus ZS660KL
This happens on when I got the phone with Android 9 and still happens for when I newly upgrade to Android 10.

Currently the only way is to avoid locking your phone when K2A is active. Go back to homescreen or to another app first.

**Comment by miblond** [comment] 2020-06-04 10:02
In addition to the behavior described above, the database is closed and quick unlock is disabled. So I need to enter the full master password again.
This happens if I have a database entry open (not in edit mode) and the phone locks (because not using it for 2minutes). When I want to use fingerprint to unlock the phone, it does not work. I first need to push the power button and then I can unlock the phone with the fingerprint. But it takes a while as KeePass2Android seems to block the processing while it is closing the DB. Then I get thrown back to the main login screen of KeePass2Android.
This does not happen if KeePass2Android shows a list (group) of entries when the phone gets locked.
_Workaround_: always close the entry before the phone locks (go back to group view or main view)

_Expected behaviour:_ 
when the phone locks, KeePas2Android should switch back to be ready for quick-unlock after the phone has been unlocked. And it should of course not influence the behaviour to unlock the phone.

Device: Huawei P20 Pro

**Comment by miblond** [comment] 2020-06-04 18:32
Looks as if Update 1.08-r0 - released today-  solves the problem. Great! Thanks! Beer is coming :-)

**Comment by t-p-tan** [comment] 2020-06-05 10:15
Confirmed working. Mine will start out with quickunlock without the fingerprint prompt. Just press on circle fingerprint beside the quick unlock field. Prost!

**Comment by vepman** [comment] 2020-06-06 07:11
Feedback:
Fingerprint works on Tab S6 fine now. Good job.

**Closed** 2020-06-09 18:24 UTC
