### ISSUE TITLE
Keyboard "user" button auto-submits

### ISSUE THREAD

**Issue by HairyDude** [PhilippC/keepass2android#167] opened 2017-12-15 03:17 UTC
When I press the "User" button in the mini keyboard, the login form appears to auto-submit even though the password field is blank. Currently this means I am unable to log in to forums.factorio.com using the mini keyboard because phpBB clears the username field on a failed login. The same issue happened just now on Github (which doesn't clear the username field). This is with Chrome 62.

**Comment by PhilippC** [comment] 2017-12-16 15:13
duplicate of #89

**Closed by PhilippC** 2017-12-16 15:13 UTC
