### ISSUE TITLE
[Feature Proposal] Favicon Downloader

### ISSUE THREAD

**Issue by ikellenberger** [PhilippC/keepass2android#662] opened 2019-01-04 14:31 UTC
As our eyes are already used to the 'official' logos/(fav)icons it is the most convenient and fastest way to use the favicons provided by the corresponding websites.
So a new feature or plugin like https://sourceforge.net/projects/keepass-favicon would be really handy!
Thnx for your great work - it is very appreciated!

**Comment by PhilippC** [comment] 2019-01-08 20:47
duplicate of https://github.com/PhilippC/keepass2android/issues/68

**Closed by PhilippC** 2019-01-08 20:47 UTC
