### ISSUE TITLE
Added additional String doesn't show up on PC Version 

### ISSUE THREAD

**Issue by Shane9248** [PhilippC/keepass2android#2551] opened 2024-02-23 14:09 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I added an additional string on a Standard Entry on Mobile version but when i transferred the database to pc it doesn't show my added additional string 

![1000024001](https://github.com/PhilippC/keepass2android/assets/83491863/981a9c81-5f8d-4bc6-bb9b-459665dd8a99)

### Describe what you expected to happen:

The added additional string should show up on the pc version 

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

14

**Comment by PhilippC** [comment] 2024-02-24 08:22
please test if changes are transferred in general. e.g. try to rename an entry or add a new one. if this shows up, then the issue is related to the additional string. If not, the issue is related to how you transfer the database to the PC.

**Comment by Shane9248** [comment] 2024-02-24 09:10
> please test if changes are transferred in general. e.g. try to rename an entry or add a new one. if this shows up, then the issue is related to the additional string. If not, the issue is related to how you transfer the database to the PC.

i am sorry it does show up on the pc in the advanced section...i didn't check thoroughly as i don't have detailed knowledge about keepass so yes everything works as it should ![IMG_20240224_143519701.jpg](https://github.com/PhilippC/keepass2android/assets/83491863/b7d5e425-2b3e-4930-a3e0-0c85c6836efb)

Closing the issue

**Closed** 2024-02-24 09:11 UTC
Labels: bug
