### ISSUE TITLE
[FEAT] Dedicated OTP page like in google authentificator

### ISSUE THREAD

**Issue by soredake** [PhilippC/keepass2android#2323] opened 2023-04-25 10:51 UTC
It would be nice if keepass2android have dedicated OTP page like in google authentificator.

example:
![google auth](https://user-images.githubusercontent.com/5204968/234255171-acf49d09-d48f-46bc-a582-885409ba21a6.jpg)

**Comment by PhilippC** [comment] 2024-01-05 08:17
duplicate of #803

**Closed by PhilippC** 2024-01-05 08:17 UTC
Labels: enhancement
