### ISSUE TITLE
Feature request: support for MEGA

### ISSUE THREAD

**Issue by alpenblauwtje** [PhilippC/keepass2android#2301] opened 2023-04-08 10:53 UTC
Please add support for opening keepass databases on MEGA (mega.io). Mega is one of the few cloud storage providers that offers a native desktop client for Linux. As a Linux user I want to access my keepass database from my Linux desktop *and* Android.

Background:
Currently there are 2 alternative cloud storage providers for Linux: Dropbox and pCloud. 
Besides the fact that Dropbox ditched Linux support for years but gone back on this, the free account only allows connection from 3 devices which makes it no option anymore for people with more than 3 devices (note that a single laptop with a dual-boot OS already counts as 2...)
pCloud is the other alternative but this storage provider is not as mature as the others. For example you can't mount a VeraCrypt image that is stored in a local pCloud folder (which is no problem in a local Dropbox or Mega folder). Furthermore auto-running pCloud on Linux is cumbersome, because pCloud makes the local folder available just *after* logon which means other apps cannot use any settings at logon if you have them centrally stored in that folder. Again no issue for Dropbox and Mega.

**Comment by PhilippC** [comment] 2023-04-11 04:32
duplicate of https://github.com/PhilippC/keepass2android/issues/99

**Closed** 2023-07-22 11:47 UTC
