### ISSUE TITLE
content of db automatically and unwillingly copied

### ISSUE THREAD

**Issue by Thomas-Markus** [PhilippC/keepass2android#1096] opened 2019-12-31 12:09 UTC
If you choose an entry, the content of the field named "notes" will be copied into "Samsung Notes" without further ado.

Why is that?

Watch attached video for details.

[Don't copy me.zip](https://github.com/PhilippC/keepass2android/files/4012643/Don.t.copy.me.zip)

**Comment by PhilippC** [comment] 2020-01-06 10:53
this is because the hint on the input field is "notes" which is the same as the name of string of the current entry. 
I consider this a feature and not a bug: the KP2A keyboard is used for transferring data from the database into other apps. IF you don't want this, please use another keyboard. This kind of matching fields to strings is required to make the keyboard useful.

**Closed by PhilippC** 2020-01-06 10:53 UTC
