### ISSUE TITLE
Allow opening files from several OneDrive-accounts

### ISSUE THREAD

**Issue by Harshad-Shah** [PhilippC/keepass2android#226] opened 2018-01-28 09:30 UTC
Open a second keepass database from another OneDrive account after first is opened from a different OneDrive account. Is it possible?

**Comment by BenHFHC207** [comment] 2018-01-31 15:53
I have a similar issue, would like to add my OneDrive for Business account but unable to.  Selecting 3rd party app doesn't work as intended either, syncing back and forth doesn't seem to work.

**Comment by JanNiMey** [comment] 2018-07-23 14:46
Hi
Having met with the same issue, i wonder: has this been solved yet?

**Comment by PhilippC** [comment] 2019-10-04 19:05
This is fixed now. Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.

**Closed by PhilippC** 2019-10-04 19:05 UTC

**Comment by RonaldMeu** [comment] 2019-10-25 18:34
I changed database to Onedrive for business but if i delete a record or edit one i'll get an error message.
I can open , but i can't edit/delete/add new.

**Comment by PhilippC** [comment] 2019-10-28 08:33
@RonaldMeu what error message do you get?

**Comment by RonaldMeu** [comment] 2019-10-28 08:46
Hi, i'll get a general exception..
with message  :
Unexpected exception returned from service.
save or use the option ' sync database ' when the source is available again.

regards,

Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________
