### ISSUE TITLE
FEATURE REQUEST: Yandex disk connection

### ISSUE THREAD

**Issue by marcoqf** [PhilippC/keepass2android#1330] opened 2020-07-21 04:04 UTC
1) Please take in consideration to add Yandex Disk connection.
2) please take in consideration to create a team password manager (One database and one master password  and then user passwords. User can only copy and paste the password **** ) this will be useful to share the same computer  with your family without saving passwords in the browser) 
Thanks

**Comment by PhilippC** [comment] 2020-07-22 17:49
1.) duplicate of https://github.com/PhilippC/keepass2android/issues/137
2.) KP2A has support for "child databases". You should be able to achieve roughly what you want with those.

**Closed by PhilippC** 2020-07-22 17:49 UTC
