### ISSUE TITLE
[FEAT] Support for Passkeys from KeepassXC

### ISSUE THREAD

**Issue by wYhyzByH** [PhilippC/keepass2android#2604] opened 2024-05-18 05:47 UTC
Hi

I'd really like to use the new support for Passkeys in KeepassXC. But for that I need an Android app to support it as well.
I did not find this to be on the roadmap.

Is anyone working on that, yet?

Thanks for taking this into consideration.

KeepassXC announcement: https://keepassxc.org/blog/2024-03-10-2.7.7-released/

**Comment by Zocker1999NET** [comment] 2024-05-19 23:49
Passkey support is already discussed in #2099

**Comment by PhilippC** [comment] 2024-10-08 07:24
closing as duplicate of #2099

**Closed by PhilippC** 2024-10-08 07:24 UTC
Labels: enhancement
