### ISSUE TITLE
Does not synchronize with database on nextcloud server

### ISSUE THREAD

**Issue by boggle247** [PhilippC/keepass2android#812] opened 2019-05-06 12:03 UTC
Using Keepass2android ver. 1.07-r1 from playstore on android nougat (7.0.1)

This issue happens when I've setup the database connection via owncloud option, nextcloud, and webdav option.

Issue:
Does not synchronize to server, and shows no error that it failed. 

Reproduce:
Make a change to database from keepass, save changes. 

I verify there are no changes by inspecting the modified date of the file on my nextcloud server. 

I'm not sure how long it's been happening. I've only accidentally noticed it. Probably within the last month or two. 

Using keepassxc works, although that uses a local file downloaded via the nextcloud app and any change made the file is uploaded to the server. Aka it doesn't use webdav.

For what it's worth, webdav with my calendar on my phone syncs correctly both ways with the server. I make a test event, sync it with davx5, and on my nextcloud web app it shows the change. Change it in the web app and it reflects on my phone. Point being I believe it's not that webdav is broken with my server, but is more likely something with the app.

**Comment by ttomasini** [comment] 2019-05-06 12:08
Duplicate of #747

**Comment by florie1706** [comment] 2019-05-07 04:40
Same here. Phone is on Android 9, Nextcloud Server is 16.0.0

**Comment by mhophop** [comment] 2019-05-12 07:46
Synchronisation works for me on Samsung Galaxy Tag S2 with Android 7 and on Galaxy S4 Witz Android 5.0.1 and with Keepass2Android V1..07.r1 and Nextcloud 16.

**Comment by wolandtel** [comment] 2019-06-26 02:42
The same. MIUI 10.3.2, Android 9, keepass2android 1.07-r1.

26.06.2019 7:29:11:544 -- DatabaseSettingsActivity.OnPause
26.06.2019 7:29:11:552 -- Timeout start
26.06.2019 7:29:39:256 -- DatabaseSettingsActivity.OnStop
26.06.2019 7:29:41:924 -- DatabaseSettingsActivity.OnStart
26.06.2019 7:29:41:925 -- DatabaseSettingsActivity.OnResume
26.06.2019 7:29:41:925 --  DatabaseIsUnlocked=True
26.06.2019 7:29:41:925 -- Timeout cancel
26.06.2019 7:29:46:898 -- DatabaseSettingsActivity.OnPause
26.06.2019 7:29:46:899 -- Timeout start
26.06.2019 7:29:46:915 -- GroupActivity.OnStart
26.06.2019 7:29:46:916 -- GroupActivity.OnResume
26.06.2019 7:29:46:916 --  DatabaseIsUnlocked=True
26.06.2019 7:29:46:917 -- Timeout cancel
26.06.2019 7:29:47:348 -- DatabaseSettingsActivity.OnStop
26.06.2019 7:29:47:350 -- DatabaseSettingsActivity.OnDestroyTrue
26.06.2019 7:29:49:949 -- status message: Initializing...
26.06.2019 7:29:49:952 -- status submessage: 
26.06.2019 7:29:49:996 -- status message: Синхронизация кэшированной базы данных…
26.06.2019 7:29:49:997 -- status submessage: Загружается удалённый файл…
26.06.2019 7:29:53:837 -- status submessage: Сохранить файл…
26.06.2019 7:29:54:663 -- stream was reset: NO_ERROR
26.06.2019 7:29:54:679 -- System.Exception: stream was reset: NO_ERROR ---> Java.IO.IOException: stream was reset: NO_ERROR
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <daf82fa226e64866b6883f2960c1a0f1>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.UploadFile (System.String p0, System.Byte[] p1, System.Boolean p2) [0x00092] in <bbfdbb1fb19a4f0a8a8c95bc1465a6cb>:0 
  at keepass2android.Io.JavaFileS

**Comment by BrooklynFFM** [comment] 2019-07-19 09:02
Same error for me. Main error message seems to be:
Java.IO.IOException: stream was reset: NO_ERROR

Syncing is reported to complete successful by the application, but file is not in sync afterwards.

19.07.2019 10:56:45:603 -- status message: Initializing...
19.07.2019 10:56:45:604 -- status submessage: 
19.07.2019 10:56:45:659 -- status message: Synchronisiere gecachte Datenbank...
19.07.2019 10:56:45:661 -- status submessage: Quelldatei wird geladen ...
19.07.2019 10:56:46:94 -- status message: Speichere Datenbank...
19.07.2019 10:56:46:901 -- status submessage: Führe Änderungen zusammen...
19.07.2019 10:56:48:22 -- ReadXmlStreamed: 820ms
19.07.2019 10:56:48:130 -- status submessage: 
19.07.2019 10:56:50:429 -- Xml WriteDocument: 1986ms
19.07.2019 10:56:50:631 -- stream was reset: NO_ERROR
19.07.2019 10:56:50:644 -- couldn't save to remote https://[username]:[password]@[domain]/nextcloud/remote.php/webdav/[filename].kdbx
19.07.2019 10:56:50:648 -- System.Exception: stream was reset: NO_ERROR ---> Java.IO.IOException: stream was reset: NO_ERROR
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <daf82fa226e64866b6883f2960c1a0f1>:0 
at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
at Keepass2android.Javafilestorage.WebDavStorage.UploadFile (System.String p0, System.Byte[] p1, System.Boolean p2) [0x00092] in <bbfdbb1fb19a4f0a8a8c95bc1465a6cb>:0 
at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x0001c] in <d9555282dea14061ab4400355adad9e4>:0 
--- End of inner exception stack trace ---
at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x00036] in <d9555282dea14061ab4400355adad9e4>:0 
at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <d9555282dea14061ab4400355adad9e4>:0 
at keepass2android.Io.CachingFileStorage.TryUpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00000] in <d9555282dea14061ab4400355adad9e4>:0 
19.07.2019 10:56:53:542 -- GroupActivity.OnPause
19.07.2019 10:56:53:543 -- Timeout start
19.07.2019 10:56:53:597 -- DatabaseSettingsActivity.OnCreate
19.07.2019 10:56:53:599 -- DatabaseSettingsActivity:apptask=
19.07.2019 10:56:53:748 -- DatabaseSettingsActivity.OnStart
19.07.2019 10:56:53:750 -- DatabaseSettingsActivity.OnResume
19.07.2019 10:56:53:751 -- DatabaseIsUnlocked=True
19.07.2019 10:56:53:751 -- Timeout cancel

**Comment by boggle247** [comment] 2019-07-23 16:19
#747 #478 Potentially related.

Can we place a bounty on this bug? It's been a year and I'm about to drop Keepass and pay for something like Enpass. But I'd rather throw that money here to make this work. I've never done this before on github. What issue number should I create the bounty on? The lowest number, 478? 747 seems to have the most activity though.

**Comment by BrooklynFFM** [comment] 2019-07-28 18:49
I believe it might be related to http2.0.
I saw this issue with okhttp: https://github.com/square/okhttp/issues/4964

So I tested my server/domain with https://tools.keycdn.com/http2-test and checked that I had enabled http2.0 support. Then I changed my Apache configuration and removed the line 
`Protocols h2 http/1.1`
from my site configuration file. After restarting Apache, I re-checked and http2.0 was disabled. Then I tried again to synchronize and it worked. A second attempt to synchronize resulted in a message confirming the two files are the same.

Could anyone please try this, too, and check if it solves the problem?

**Comment by PhilippC** [comment] 2019-08-19 10:03
closing as duplicate of #747

**Closed by PhilippC** 2019-08-19 10:03 UTC
