### ISSUE TITLE
Fill with K2A popup obscures dialler numbers

### ISSUE THREAD

**Issue by charlesmcevoy** [PhilippC/keepass2android#295] opened 2018-03-11 19:49 UTC
The 'Fill with K2A' popup obscures the top line of the dial pad, as shown:
HTC10, stock dialler
![image](https://user-images.githubusercontent.com/6136396/37257698-f01385ee-2564-11e8-961b-f30f129a1302.png)

**Comment by whisdol** [comment] 2018-03-24 10:30
Also happens in the stock dialer on my OnePlus 3T. Steps to reproduce:
1. Open Dialer app and open the number pad
2. Type a number
3. Press home button
4. Reopen Dialer app

**Comment by PhilippC** [comment] 2018-03-26 09:20
duplicate of https://github.com/PhilippC/keepass2android/issues/303

**Closed by PhilippC** 2018-03-26 09:20 UTC
