### ISSUE TITLE
Edit Group name doesn't work in local database

### ISSUE THREAD

**Issue by gejojimenez** [PhilippC/keepass2android#513] opened 2018-08-21 10:51 UTC
In version 1.05e, name of a folder/group can't be changed/edited, after changing the name in the text box, and hit accept button, the group name doesn't change.
New groups/folders can be created, and new entries can be added inside them, but group name can't be changed after creation.
Samsung Galaxy A5 2017 with Android 8.0

**Comment by PhilippC** [comment] 2018-08-21 19:12
duplicate of #434

**Closed by PhilippC** 2018-08-21 19:12 UTC
