### ISSUE TITLE
Sync failed. BadRequest

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#1473] opened 2020-11-20 21:05 UTC
Steps reproduce:

![IMG_20201120_215605](https://user-images.githubusercontent.com/46166740/99849725-5bbd3e00-2b7c-11eb-8b92-a7e09b5c7819.jpg)
![IMG_20201120_215514](https://user-images.githubusercontent.com/46166740/99849737-624bb580-2b7c-11eb-8041-0b1afbe17565.jpg)
![IMG_20201120_215528](https://user-images.githubusercontent.com/46166740/99849743-6677d300-2b7c-11eb-8bb5-956c8e5d4255.jpg)
![IMG_20201120_215648](https://user-images.githubusercontent.com/46166740/99849752-68da2d00-2b7c-11eb-9f2a-725cafb7cf8c.jpg)

onedrive
Version 1.08c-r1

**Comment by PhilippC** [comment] 2020-11-21 11:29
duplicate of #1036

**Closed by PhilippC** 2020-11-21 11:29 UTC
