### ISSUE TITLE
Keepass2android force-closes on AospExtended

### ISSUE THREAD

**Issue by kr428** [PhilippC/keepass2android#476] opened 2018-07-29 10:49 UTC
Using AospExtended (Android 8.1.2, July update) on a Motorola G 2015, the app reliably force-closes after unlocking the database. Cleared data, completely reinstalled the app, even clean-flashed the ROM - no change. Known problem? How to help debugging this? kdbx file lives in a WebDAV folder, updating local file seems to work well...
Thanks,
Kristian

**Comment by kr428** [comment] 2018-07-30 06:32
Messages from the keepass2android debug log for whatever it's worth, see below. The app seems to force-close just shortly after the key icon appears in the notification area of the system.

29.07.2018 14:56:23:536 -- Creating application keepass2android.keepass2android. Version=122
29.07.2018 14:56:23:762 -- KeePass.OnCreate
29.07.2018 14:56:23:769 -- KeePass:apptask=
29.07.2018 14:56:23:777 -- Loaded task keepass2android.NullTask
29.07.2018 14:56:23:778 -- KeePass.OnCreate
29.07.2018 14:56:23:798 -- KeePass.OnStart
29.07.2018 14:56:23:798 -- KeePass.OnStart
29.07.2018 14:56:23:886 -- FileSelect.OnCreate
29.07.2018 14:56:23:887 -- FileSelect:apptask=NullTask
29.07.2018 14:56:23:898 -- Loaded task keepass2android.NullTask
29.07.2018 14:56:24:94 -- FileSelect.OnStart
29.07.2018 14:56:24:448 -- PasswordActivity.OnCreate
29.07.2018 14:56:24:449 -- PasswordActivity:apptask=
29.07.2018 14:56:24:460 -- Loaded task keepass2android.NullTask
29.07.2018 14:56:25:45 -- PasswordActivity.OnStart
29.07.2018 14:56:25:62 -- PasswordActivity.OnResume
29.07.2018 14:56:25:64 --  DatabaseIsUnlocked=False
29.07.2018 14:56:25:70 -- starting: True, Finishing: False, _performingLoad: False
29.07.2018 14:56:25:180 -- PasswordActivity.OnPause
29.07.2018 14:56:25:181 -- Pre-loading database file starting
29.07.2018 14:56:25:215 -- CFS: OpenWhenNoLocalChanges
29.07.2018 14:56:25:217 -- CFS: hashing cached version
29.07.2018 14:56:25:529 -- PasswordActivity.OnResume
29.07.2018 14:56:25:530 --  DatabaseIsUnlocked=False
29.07.2018 14:56:25:531 -- starting: False, Finishing: False, _performingLoad: False
29.07.2018 14:56:25:622 -- FileSelect.OnStop
29.07.2018 14:56:25:707 -- FileSelect.OnDestroyTrue
29.07.2018 14:56:25:714 -- KeePass.OnStop
29.07.2018 14:56:25:717 -- KeePass.OnDestroyTrue
29.07.2018 14:56:25:719 -- KeePass.OnDestroyTrue
29.07.2018 14:56:26:299 -- CFS: Files in Sync
29.07.2018 14:56:26:319 -- Pre-loading database file completed
29.07.2018 14:56:38:102 -- PasswordActivity.OnActivityResult 874348/1000
29.07.2018 14:56:38:104 -- No AppTask in OnActivityResult
29.07.2018 14:56:39:859 -- ReadXmlStreamed: 672ms
29.07.2018 14:56:40:36 -- LoadDB OK
29.07.2018 14:56:40:50 -- Starting/Updating OngoingNotificationsService. Database Unlocked
29.07.2018 14:56:40:495 -- PasswordActivity.OnPause
29.07.2018 14:56:40:503 -- Timeout start
29.07.2018 14:56:40:569 -- GroupActivity.OnCreate
29.07.2018 14:56:40:571 -- GroupActivity:apptask=
29.07.2018 14:56:40:581 -- Loaded task keepass2android.NullTask
29.07.2018 14:56:40:848 -- GroupActivity.OnStart
29.07.2018 14:56:40:856 -- GroupActivity.OnResume
29.07.2018 14:56:40:857 --  DatabaseIsUnlocked=True
29.07.2018 14:56:40:858 -- Timeout cancel
29.07.2018 14:56:40:951 -- System.NullReferenceException: Object reference not set to an instance of an object
  at keepass2android.GroupBaseActivity.UpdateFingerprintInfo () [0x00049] in <ebacd22e01b440f8a0ea06ff7babfe3f>:0 
  at keepass2android.GroupBaseActivity.OnResume () [0x00029] in <ebacd22e01b440f8a0ea06ff7babfe3f>:0 
  at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <0126298644224191a262b1817d552946>:0 
  at (wrapper dynamic-method) System.Object.55555c88-e51f-4c0b-a02a-8f7d42d1b85b(intptr,intptr)
29.07.2018 14:56:44:449 -- Creating application keepass2android.keepass2android. Version=122
29.07.2018 14:56:44:669 -- KeePass.OnCreate
29.07.2018 14:56:44:676 -- KeePass:apptask=
29.07.2018 14:56:44:680 -- KeePass.OnCreate
29.07.2018 14:56:44:700 -- KeePass.OnStart
29.07.2018 14:56:44:700 -- KeePass.OnStart
29.07.2018 14:56:44:786 -- FileSelect.OnCreate
29.07.2018 14:56:44:787 -- FileSelect:apptask=NullTask
29.07.2018 14:56:44:801 -- Loaded task keepass2android.NullTask
29.07.2018 14:56:44:995 -- FileSelect.OnStart
29.07.2018 14:56:45:345 -- PasswordActivity.OnCreate
29.07.2018 14:56:45:346 -- PasswordActivity:apptask=
29.07.2018 14:56:45:356 -- Loaded task keepass2android.NullTask
29.07.2018 14:56:45:926 -- PasswordActivity.OnStart
29.07.2018 14:56:45:943 -- PasswordActivity.OnResume
29.07.2018 14:56:45:946 --  DatabaseIsUnlocked=False
29.07.2018 14:56:45:950 -- starting: True, Finishing: False, _performingLoad: False
29.07.2018 14:56:46:51 -- PasswordActivity.OnPause
29.07.2018 14:56:46:61 -- Pre-loading database file starting
29.07.2018 14:56:46:100 -- CFS: OpenWhenNoLocalChanges
29.07.2018 14:56:46:103 -- CFS: hashing cached version
29.07.2018 14:56:46:399 -- PasswordActivity.OnResume
29.07.2018 14:56:46:400 --  DatabaseIsUnlocked=False
29.07.2018 14:56:46:401 -- starting: False, Finishing: False, _performingLoad: False
29.07.2018 14:56:46:481 -- FileSelect.OnStop
29.07.2018 14:56:46:554 -- FileSelect.OnDestroyTrue
29.07.2018 14:56:46:561 -- KeePass.OnStop
29.07.2018 14:56:46:564 -- KeePass.OnDestroyTrue
29.07.2018 14:56:46:566 -- KeePass.OnDestroyTrue
29.07.2018 14:56:48:60 -- CFS: Files in Sync
29.07.2018 14:56:48:76 -- Pre-loading database file completed
29.07.2018 14:56:48:656 -- PasswordActivity.OnPause
29.07.2018 14:56:48:688 -- AppSettingsActivity.OnCreate
29.07.2018 14:56:48:689 -- AppSettingsActivity:apptask=
29.07.2018 14:56:48:987 -- AppSettingsActivity.OnStart
29.07.2018 14:56:48:991 -- AppSettingsActivity.OnResume
29.07.2018 14:56:48:992 --  DatabaseIsUnlocked=False
29.07.2018 14:56:49:540 -- PasswordActivity.OnStop

**Comment by PhilippC** [comment] 2018-08-13 06:42
duplicate of #474

**Closed by PhilippC** 2018-08-13 06:42 UTC
