### ISSUE TITLE
Keyboard selection dialog doesn't appear after Pie update

### ISSUE THREAD

**Issue by jinno1234** [PhilippC/keepass2android#694] opened 2019-01-25 04:10 UTC
The Keyboard selection dialog doesn't appear whenever I press the notification after I updated to Pie. Is there a conflict with the new One UI?

Samsung Galaxy S9+ Android 9

**Comment by PhilippC** [comment] 2019-01-28 11:06
duplicate of #530. Note that this is closed but not yet in the beta channel release.

**Closed by PhilippC** 2019-01-28 11:06 UTC
