### ISSUE TITLE
Fingerprint doesn't work on OnePlus 5

### ISSUE THREAD

**Issue by AlexWayfer** [PhilippC/keepass2android#135] opened 2017-11-24 13:53 UTC
OnePlus 5, in both stable and beta channels.

Fingerprint doesn't work at all (it's in Home button, and I'm returning to Home by touch it).

The red bang mark near master-password field, by touch on it pop-up with "Fingerprint unlock" title and error stack trace. I can't to screenshot because of it isn't allowed by app. And there is no "send" or "copy" buttons.

Begins with:

```
Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x00d0] in <aaa7e0749da146d3871f57c8138c11ad>:0
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00089] in <aaa7e0749da146d3871f57c8138c11ad>:0
  --- End of managed Java.LangRuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
  at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
  at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
```

I tired to type, sorry. Please, make button for email to developer this stack trace (or at least copy to clipboard).

**Comment by PhilippC** [comment] 2017-11-25 18:19
thanks for your report and the effort. I am closing this as a duplicate of #37 .

**Closed by PhilippC** 2017-11-25 18:19 UTC

**Comment by AlexWayfer** [comment] 2017-11-25 18:37
Thank you, didn't found by "OnePlus". I'll quote there my report.
