### ISSUE TITLE
[QUESTION] unable to change database name

### ISSUE THREAD

**Issue by jetguat** [PhilippC/keepass2android#2556] opened 2024-02-28 15:02 UTC
**What version of Keepass2Android are you using?**
Please follow these steps to find your app version:
1. Click the **⁝** icon in the top right corner
2. Select **Settings**
3. Click **About**
4. Find the "Version" information and provide it here:
version 1.10-pre

I have evolved a database over multiple Samsung phone.  I originally created the database with the name "Samsung Note9 DB".

I have tried to change the DB name within the Setting -> Database->Database Name.   and that currently reflects the name "GalaxyS23UltraDB"

however within the GUI  only the old name is reflected .
tried to attach two screen shots to show this.  question is how do I get the current DB name to be reflected in the app?

![Screenshot_20240228_085953_Keepass2Android](https://github.com/PhilippC/keepass2android/assets/30705858/a14d6708-542e-48cc-8302-edcc7977b3a8)
![SmartSelect_20240228_085902_Keepass2Android](https://github.com/PhilippC/keepass2android/assets/30705858/d2b620d3-c368-44e9-82b8-16d831d85d7e)

**Comment by PhilippC** [comment] 2024-05-01 14:03
what you see there is the name of the root group, not the database name. Unfortunately it currently can only be modfied in external tools like KeePass2. Closing as duplicate of https://github.com/PhilippC/keepass2android/issues/1181

**Closed by PhilippC** 2024-05-01 14:03 UTC
Labels: question
