### ISSUE TITLE
Can't pick Google Drive as option

### ISSUE THREAD

**Issue by rvane** [PhilippC/keepass2android#1857] opened 2021-11-30 17:07 UTC
It is not possible to choose 'Google Drive' when first starting the app (or after deleting all the data).
Google throws the message: 'This app is blocked - This app tried to access sensitive info in you Google account. To keep your account safe, Google blocked this access'.

Navigating to Google Drive via 'System file picker' does not show the essential option 'Computers', where the KeePass database file is to be found (it's stored on a folder on my computer and this folder has been added using the Google Drive-app on the pc. Only 'My Drive', 'Shared with me' and 'Starred' are listed.
![1-select-the-storage-type](https://user-images.githubusercontent.com/27134869/144093822-f88de40c-d748-49b6-940f-dd5de4924d00.jpg)
![2-this-app-is-blocked](https://user-images.githubusercontent.com/27134869/144093824-a14066b5-ec8a-415a-ad2d-7d6fde62b0c8.jpg)
![3-drive](https://user-images.githubusercontent.com/27134869/144093825-61326520-62f4-46a1-a1a6-c3b0b6a93203.jpg)

**Comment by PhilippC** [comment] 2021-12-01 16:00
duplicate of https://github.com/PhilippC/keepass2android/issues/1833

**Closed by PhilippC** 2021-12-01 16:00 UTC
