### ISSUE TITLE
Unable to use KP2A Keyboard to enter TOTP

### ISSUE THREAD

**Issue by KodiakIT** [PhilippC/keepass2android#821] opened 2019-05-13 14:46 UTC
As stated in title, attempting to switch to KP2A keyboard from AOSP keyboard on LineageOS in multiple apps results in the numpad from the AOSP keyboard simply re-appearing instead of allowing me to cycle through stored fields to input (e.g. name, password, TOTP, other attributes) as I was previously able to on previous LOS versions/stock Oreo(/Pie too I think?)

**Comment by theolike** [comment] 2019-05-17 17:33
Probably a duplicate of #799.

**Comment by PhilippC** [comment] 2019-08-05 18:15
closing as duplicate

**Closed by PhilippC** 2019-08-05 18:15 UTC
