### ISSUE TITLE
Suggestion: QuickUnlock timeout

### ISSUE THREAD

**Issue by arden13** [PhilippC/keepass2android#310] opened 2018-03-22 16:43 UTC
I think it would be great if I could set a timeout feature for QuickUnlock. That way if I leave it open overnight or after 6 hours or whatever I have to input my master password to gain access. 

I apologise if this is already a feature and I can't find it.

**Comment by Wh1rledPeas** [comment] 2018-03-29 11:47
I just went through the entire app settings and can't find this either. I think it would be nice to have a setting such as this, so after a particular amount of time quick unlock expires and you have to reenter the master password.

The only setting that currently exist, that I can find any way, is the time out for the quick unlock itself. Which defines the amount of time the app remains unlocked before asking for the quick unlock password again.

**Comment by NumbGnat** [comment] 2018-04-09 20:29
@binarious Go to...

Settings -> Application -> Security -> Application Timeout

**Comment by arden13** [comment] 2018-04-09 20:36
That doesn't solve the QuickUnlock issue. It just locks the database.

**Comment by NumbGnat** [comment] 2018-04-16 21:48
@binarious You are correct. This is a duplicate of Issue #53, created by @Alan-Smith.

Regarding your particular issue, knowing Android the way I do, there are a number things that might affect how it shuts down. I personally don't allow battery optimization on many of my apps that I expect notifications from or that I expect to provide their automatic functionality from time to time in the background. Things like messenger apps, virus protection, etc.

I also make sure that the status bar icon remains for as long as the database is open. That is another thing that can affect weather Android shuts the app down or not.

I'm not sure if there's something keepass2android can do to detect weather it is currently included or excluded from battery optimization and warn the user, or if there's something in the applications manifest that it can indicate to the Android system weather battery optimization can adversely affect the application.

Either way... This seems like a discussion for a different issue all together. I would suggest that you create one if you think it's needed. Battery optimization has been discussed in a couple of other issues on the site. All of which have been closed.

**Comment by binarious** [comment] 2018-04-17 07:28
I wasn't hijacking. I thought I was running into a predefined timeout I'd like to be able to configure. Turned out not to be the case. Anyways, @arden13, this issue can be closed as being a duplicate.

**Comment by PhilippC** [comment] 2019-08-05 04:49
I agree this is a duplicate of #53

**Closed by PhilippC** 2019-08-05 04:49 UTC

**Comment by Future-aspen** [comment] 2025-02-03 21:19
I confronted that challenge and identified a solution https://stackdev.space/questions/what-could-be-causing-my-android-app-to-unexpectedly-close-overnight
