### ISSUE TITLE
[FeatureReq] Custom reordering "Additional string"

### ISSUE THREAD

**Issue by harbing3r1** [PhilippC/keepass2android#865] opened 2019-07-08 14:22 UTC
Would it be possible to add option to reorder the "additional string" in database entries? 
That would be great when there are many of them and one would like to have important one up. 

Maybe a drag and reorder kind of function would be perfect (or simply a input a number designating its location)

Thanks dev!

**Comment by ouzowtf** [comment] 2019-07-08 14:26
Duplicate of [#352](https://github.com/PhilippC/keepass2android/issues/352)

**Closed** 2019-08-15 02:54 UTC
