### ISSUE TITLE
Please add support for adding TOTP using the camera

### ISSUE THREAD

**Issue by saudiqbal** [PhilippC/keepass2android#1575] opened 2021-02-17 21:21 UTC
Please add support for adding TOTP using the app with the camera.

**Comment by PhilippC** [comment] 2021-02-18 14:27
how would this work? Which service would provide visual data for this?

**Comment by saudiqbal** [comment] 2021-02-18 17:14
What I mean is scan the QR code with the camera and add the code in the TOTP field.

**Comment by PhilippC** [comment] 2021-02-19 06:11
where can I find such a QR code?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2021-02-19 12:18
https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example

![Totp qrcode](https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example)

**Comment by saudiqbal** [comment] 2021-02-19 21:15
> [https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example](https://www.google.com/chart?chs=200x200&chld=M%7C0&cht=qr&chl=otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example)
> 
> ![Totp qrcode](https://camo.githubusercontent.com/3f1b00e2c9632b9e87033bcf4b7e6614b0faae5e57d286578aed5808263de1e4/68747470733a2f2f7777772e676f6f676c652e636f6d2f63686172743f6368733d323030783230302663686c643d4d25374330266368743d71722663686c3d6f7470617574683a2f2f746f74702f4578616d706c653a616c69636540676f6f676c652e636f6d3f7365637265743d4a425357593344504548504b33505850266973737565723d4578616d706c65)

This is exactly what I meant.

**Comment by PhilippC** [comment] 2021-02-22 10:27
ok I see. just out of interest - which tools or services are generating these QR codes?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2021-02-22 10:52
Came across many from popular sites. Always had to extract secrect of qrcode and enter into keepass manually.

> just out of interest - which tools or services are generating these QR codes?

You can try it with your Github:

![image](https://user-images.githubusercontent.com/46166740/108698289-41408b00-7504-11eb-97e6-073604a314c2.png)

Mozilla for example:
![image](https://user-images.githubusercontent.com/46166740/108696947-8237a000-7502-11eb-8974-79b11a2ff37b.png)


![image](https://user-images.githubusercontent.com/46166740/108697144-c165f100-7502-11eb-879f-269b6ea390d9.png)

Or discord:
![image](https://user-images.githubusercontent.com/46166740/108697929-c6777000-7503-11eb-8769-f319cf499b47.png)

and so much more big sites

**Comment by saudiqbal** [comment] 2021-03-03 16:58
Right now I have to go to KeepassXC and add the code there.

**Comment by saudiqbal** [comment] 2021-03-04 21:33
This request is similar https://github.com/PhilippC/keepass2android/issues/770

**Comment by WebworkrNet** [comment] 2021-08-12 15:46
Duplicate of #623

**Closed** 2022-01-15 19:11 UTC
