### ISSUE TITLE
Android App crashes on Chromebook 

### ISSUE THREAD

**Issue by jacobacci** [PhilippC/keepass2android#2611] opened 2024-06-06 12:24 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

I installed keepass2android on my new Acer Chromebook Plus 514 (Ryzen 3).
When I try to open a keepass database file which is on my Synology NAS (across my home LAN), the app crashes.
On my Samsung A35 phone, this works fine

### Describe what you expected to happen:

I would expect the app to load the database, as it does on the Samsung A35

### What version of Keepass2Android are you using?

1.10-pre

### Which version of Android are you on?

ChromeOS 125.0.6422.140

**Comment by MrSellerie** [comment] 2024-08-06 18:54
Please have a look in issue #2520

**Comment by PhilippC** [comment] 2024-09-30 09:52
closing as duplicate of #2520

**Closed by PhilippC** 2024-09-30 09:52 UTC
Labels: bug
