### ISSUE TITLE
Unable to log in to Pcloud after account been moved to new data region

### ISSUE THREAD

**Issue by AxelSat** [PhilippC/keepass2android#1420] opened 2020-09-22 09:11 UTC
Hi Phillip,
On the 16th of September 2020, Pcloud have moved my account to a new data region.
Since then, I'm unable to open the Database anymore.
The app remain on the login access, shown below

![Screenshot_20200922-105822_Keepass2Android](https://user-images.githubusercontent.com/11719714/93862959-281c7f80-fcc3-11ea-9e50-6054292bcb4c.jpg)

Thank you

**Comment by PhilippC** [comment] 2020-09-28 07:30
I guess this is a duplicate of https://github.com/PhilippC/keepass2android/issues/1257

**Closed by PhilippC** 2020-09-28 07:30 UTC
