### ISSUE TITLE
Samsung DEX Support

### ISSUE THREAD

**Issue by johannstieger** [PhilippC/keepass2android#1954] opened 2022-03-27 09:42 UTC
Please can you add Samsung DEX Support so I can open KeePass on an external attached display on my Samsung Galaxy Smartphone (maybe enable-able r configurable in the settings)

Now I get an error that this is not allowed.

Best regards, Johann

**Comment by PhilippC** [comment] 2022-03-28 06:41
duplicate of https://github.com/PhilippC/keepass2android/issues/625

**Closed by PhilippC** 2022-03-28 06:41 UTC
