### ISSUE TITLE
Long passwords don't wrap

### ISSUE THREAD

**Issue by mlda065** [PhilippC/keepass2android#230] opened 2018-01-30 04:15 UTC
# Steps to reproduce

1. Create an entry. Use a very long password (>30 chars)
2. Save
3. Open that entry to view it (phone in portrait mode)
4. Click the eyeball symbol to make the password visible

# Expected results

The password is too long to fit on one line, so the app should wrap that text, to spread it over multiple lines. You should be able to see all characters of the password.

# Actual results

The first ~25 characters of the password are visible. The field does not wrap onto a 2nd line. I cannot see the whole password

**Comment by Karreg** [comment] 2018-01-30 05:56
As a workaround, I switch to landscape mode. Fortunately, my passwords are short enough to be displayed in landscape mode.

**Comment by mlda065** [comment] 2018-01-30 10:40
Yeah, landscape is the workaround I'm using now. I'd just like to not have to bother with that. (You have to click the eyeball symbol again)

This is a low priority issue of course, but I hope it might be easy to fix.

**Comment by PhilippC** [comment] 2018-02-06 05:37
duplicate of #96

**Closed by PhilippC** 2018-02-06 05:37 UTC
