### ISSUE TITLE
Support for Pixel 4's new Face Unlock feature

### ISSUE THREAD

**Issue by SkepticalBit** [PhilippC/keepass2android#1013] opened 2019-10-27 20:23 UTC
One thing I was fond of was the fingerprint unlock. Now that I use a Pixel 4 and with the fingerprint print reader gone, and with more phones probably following suit, it would be quite nice to be able to unlock the database using the Face Unlock API.

**Comment by elfrinjo** [comment] 2019-10-27 21:02
I'd lile to have an option to enable faceunlock only for quickunlock and not for the "mainunlock"

**Comment by Javier-Giral** [comment] 2019-10-29 16:51
Yes please. Once used to unlock with fingerprint, going back to keyboard is a big hassle.

**Comment by PhilippC** [comment] 2019-10-30 03:21
duplicate of #795 
Please note that with QuickUnlock enabled, you shouldn't have to type your full masterpassword too often (until face unlock is supported)

**Comment by Javier-Giral** [comment] 2019-10-30 09:37
Sure, in fact I use that method on my table, which does not have fingerprint reader. Thanks for pointing to the right issue #

**Closed** 2019-10-30 20:30 UTC
