### ISSUE TITLE
Enhancement - Adaptable Icon Support for 8.x

### ISSUE THREAD

**Issue by thakyZ** [PhilippC/keepass2android#214] opened 2018-01-16 21:18 UTC
I would like some kind of Adaptable icon support for 8.x. With my current launcher, Nova Launcher, the apps that do not support adaptable icons are shown as the full icon in a smaller image, and that is how I want it. Now I do want there still to be support for this. Because I am sure I am not I am not the only one. But I don't want you to rush to get this done fast. I understand it may take a while to be implemented. Thank you!

**Comment by PhilippC** [comment] 2018-01-17 04:26
duplicate of #204

**Closed by PhilippC** 2018-01-17 04:26 UTC
