### ISSUE TITLE
Keep prompting to give permission from onedrive

### ISSUE THREAD

**Issue by watoan** [PhilippC/keepass2android#1074] opened 2019-12-11 09:23 UTC
I am running 1.08-pre3 on my Oneplus 6T with Android 10.0 (official stable)
My database kdbx is stored in onedrive folder, the first time I open Keepass2Android I linked the kdbx file and gave permission to Keepass2Android, close the database and reopen has no issue.

However, on the next day I open Keepass2Android again, and enter the password, it prompted me to give permission again, this is annoying, this happens randomly, sometimes I face this within the same day.

I had no issue with Android 9 before, please help, thanks.

**Comment by PhilippC** [comment] 2019-12-12 05:17
duplicate of https://github.com/PhilippC/keepass2android/issues/1038

**Closed by PhilippC** 2019-12-12 05:17 UTC
