### ISSUE TITLE
[feature request] limit the number of false login tries

### ISSUE THREAD

**Issue by wuzi42** [PhilippC/keepass2android#1384] opened 2020-08-24 11:44 UTC
Hi, thank you for keepass android!
What I am missing is a counter for wrong password inputs. Wouldn't it be fine to close the input or close the app after a limited number of tries?

Thanks

**Comment by techvanity** [comment] 2020-09-16 01:56
I do not think it is needed. Keepass files are stored offline. Even if one app implements such a protection, the attacker can try to open the database using other keepass compatible apps (there are [too many](https://keepass.info/download.html)).

**Comment by PhilippC** [comment] 2020-09-16 19:13
closing as duplicate of https://github.com/PhilippC/keepass2android/issues/511

**Closed by PhilippC** 2020-09-16 19:13 UTC
