### ISSUE TITLE
Startup crash on Samsung Galaxy Tab S4/S6 DeX mode

### ISSUE THREAD

**Issue by solarelf** [PhilippC/keepass2android#1058] opened 2019-11-27 18:22 UTC
On startup, any build crashes with message “This app cannot run in DeX, please try tablet mode”. I understand the issue is not looking as on the top of priority but could you please add it on the list to fix the app manifest to allow KP2A for Samsung DeX users where it is HIGHLY appreciated?

Thank you!

P.S. Works for OneUI 1.1 (ordinary tablet) shell. From my experience in porting to DeX, the app manifest must be updated to allow KP2A to start.

**Comment by PhilippC** [comment] 2019-11-30 08:58
duplicate of https://github.com/PhilippC/keepass2android/issues/625

**Closed by PhilippC** 2019-11-30 08:58 UTC
