### ISSUE TITLE
Using biometric unlock

### ISSUE THREAD

**Issue by Paintman** [PhilippC/keepass2android#1409] opened 2020-09-17 10:57 UTC
I have selected full biometric unlock ( also similar with quickunlock ). When I attempt to lock the database, why am presented with a fingerprint unlock request, which seems to disable the normal operation of the 3 navigation buttons? Is this desired behaviour?

**Comment by PhilippC** [comment] 2020-10-12 08:09
duplicate of https://github.com/PhilippC/keepass2android/issues/1373

**Closed by PhilippC** 2020-10-12 08:09 UTC
