### ISSUE TITLE
I cannot copy user or psw from notification bar.

### ISSUE THREAD

**Issue by romanomauro** [PhilippC/keepass2android#218] opened 2018-01-21 13:26 UTC
Hi, with my new Huawei P10 lite I can't copy user or psw from the notification panel. When I click, as in the past, the panel close but the psw or user is not in memory.
Can you verify? Thank you.

**Comment by PhilippC** [comment] 2018-01-22 09:55
duplicate of #149

**Closed by PhilippC** 2018-01-22 09:55 UTC
