### ISSUE TITLE
Feature request: add support to S3

### ISSUE THREAD

**Issue by stratozero** [PhilippC/keepass2android#1224] opened 2020-04-22 06:18 UTC
With Keepass2 on Windows I share my database between different PCs using a dedicated S3 bucket, but from the app I can't synchronize it. Can you please add support to S3?
Thanks

**Comment by PhilippC** [comment] 2020-05-01 18:33
duplicate of https://github.com/PhilippC/keepass2android/issues/661

**Closed by PhilippC** 2020-05-01 18:33 UTC
