### ISSUE TITLE
Unable to access the database (Error - Operation is not supported on this platform)

### ISSUE THREAD

**Issue by Akhilesh-T** [PhilippC/keepass2android#1685] opened 2021-05-18 08:44 UTC
Hi,

I updated to the latest beta version **1.09a-r0**, but now I'm unable to open the database.

Check out this image: 

<img width="318" alt="R6TRyJF6TV" src="https://user-images.githubusercontent.com/80357467/118620570-3fc0ef00-b7e3-11eb-9fd8-baf979576278.png">

**Comment by derflasher** [comment] 2021-05-18 08:46
Same problem here!

**Comment by roedel1** [comment] 2021-05-18 09:41
duplicate of #1679

**Comment by mannvomdeich** [comment] 2021-05-18 14:33
Duplicate of #

Thanks for your help!

**Comment by PhilippC** [comment] 2021-05-18 18:25
closing as duplicate of #1679

**Closed by PhilippC** 2021-05-18 18:25 UTC
