### ISSUE TITLE
Keepass crashes on Android 9 (samsung s9)

### ISSUE THREAD

**Issue by Afrit123** [PhilippC/keepass2android#712] opened 2019-02-07 17:08 UTC
Hello,

Since I updated my Samsung S9 to Android 9, I can't use Keepass anymore. I'm using version 1.06f.

What I do is I change my keyboard to the keepass keyboard. Then I click on the lock icon to select an entry. I click on "Select entry". After that I fill in my master password. I go to the entry I want to retrieve the password from and click on it.
The first time I do that, I get redirected to the login page again and I get the message that the source file and cache are synchronised. I fill in my master password again and select the entry again.
After that it keeps crashing. I get the message "Keepass2Android keeps stopping".

I've just figured out this only happens when I have an input box selected and the keyboard appears. When I open the app from my apps menu and go to the entry, everything is fine.

Can anyone help me? I've attached the log file. I can see there's an exception. 
[log.txt](https://github.com/PhilippC/keepass2android/files/2841976/log.txt)

2/7/2019 6:12:07 PM:758 -- Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putString(java.lang.String, java.lang.String)' on a null object reference
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Android.Views.InputMethods.InputMethodManager.ToggleSoftInput (Android.Views.InputMethods.ShowFlags showFlags, Android.Views.InputMethods.HideSoftInputFlags hideFlags) [0x00035] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at keepass2android.CopyToClipboardService.ActivateKp2aKeyboard () [0x0004a] in <7afcc631c65a49968e148310b528842e>:0 
  at keepass2android.CopyToClipboardService.DisplayAccessNotifications (keepass2android.PwEntryOutput entry, System.Boolean closeAfterCreate, System.String searchUrl) [0x001d5] in <7afcc631c65a49968e148310b528842e>:0 
  at keepass2android.CopyToClipboardService.OnStartCommand (Android.Content.Intent intent, Android.App.StartCommandFlags flags, System.Int32 startId) [0x00126] in <7afcc631c65a49968e148310b528842e>:0 
  at Android.App.Service.n_OnStartCommand_Landroid_content_Intent_II (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_intent, System.Int32 native_flags, System.Int32 startId) [0x0000f] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at (wrapper dynamic-method) System.Object.d892eae4-bc84-4b2e-8060-90f82e603e1a(intptr,intptr,intptr,int,int)
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putString(java.lang.String, java.lang.String)' on a null object reference

Kind regards,
Afrit123

**Comment by tiwag** [comment] 2019-02-07 19:11
Same problem with Galaxy Note 9

**Comment by DesHorsley** [comment] 2019-02-16 12:52
Very similar on my note 9, seems to crash when searching for an account after opening KeePass via the keyboard.

**Comment by merlinschumacher** [comment] 2019-02-23 01:30
Also happens on the S8 with the P Update.

**Comment by mabachel** [comment] 2019-02-27 08:17
> https://github.com/PhilippC/keepass2android/issues/564#issuecomment-467765987#

**Comment by cybermcm** [comment] 2019-03-04 20:51
I can confirm it with a Samsung S9 with Android 9 (exactly like the original post entry).

**Comment by ns740** [comment] 2019-03-05 07:25
same problem here with Samsung Note 8, Android 9, Keepass2Android 1.06f

**Comment by DevoGH** [comment] 2019-03-06 18:19
Same problem with Samsung Note 9 (model SM-N960U and Android 9) and Keepass2Android (v1.06f)

**Comment by gpion** [comment] 2019-03-07 21:50
That's a big problem for me
I was in the beta channel, reverted because of this bug but still facing it

**Comment by PhilippC** [comment] 2019-03-10 19:21
I just ordered a recent Samsung device so I will hopefully be able to test and fix this soon...

**Comment by JeffSchre** [comment] 2019-03-13 13:53
Viable workaround for those that are experiencing this issue....until the keyboard issue is addressed. 

After having this issue show up for me also on my S9 after an OTA OS push from ATT.  The AppCrash occurs when using the Keypass2Android Keyboard to select a database entry all other application functions seem to work fine.

Looking for an alternative method for password prefill (other than opening the app and "copying" the password to clipboard and hoping the site I'm on allows the Paste function) I installed the AutoFill-Plugin (Accessibility Service)....after installing the plugin and enabling it in Keepass2Andriod I am able to leave my "Default Keyboard" (Swiftkey) turned on and tap the Keypass2Andriod AutoFill notification to prefill passwords.

**Comment by chi2048** [comment] 2019-03-15 10:53
For me it has exclusively to do with KeePass2Android's keyboard. Every other keyboard works.

**Comment by PhilippC** [comment] 2019-03-18 04:54
could you please test if this is fixed in 1.07-pre6 which I have just published on https://play.google.com/apps/testing/keepass2android.keepass2android?

**Comment by ns740** [comment] 2019-03-18 05:46
Using 1.07-pre5 I think I still have the (a?) problem

I’ll try to describe the precise use case:


  1.  I have several “*.outlook.com” entries in the database (which is unlocked)
  2.  I have the keepass2andriod keyboard enabled
  3.  In the browser (firefox) I navigate to the outlook.com page and click “sign in”
  4.  In the “email …” field, I click the “keypass droid” key (to the left of the spacebar)
  5.  I choose “select entry” - the database list displays (correctly)
  6.  I click the “search” magnifier button (to search for the entry I want to use)
  7.  Keypass takes me back to the “unlock database screen” and I need to reenter the password

Please let me know if you need anything else

Thanks for looking into this
On 18 Mar 2019 11:54 +0700, PhilippC <notifications@github.com>, wrote:

could you please test if this is fixed in 1.07-pre6 which I have just published on https://play.google.com/apps/testing/keepass2android.keepass2android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fapps%2Ftesting%2Fkeepass2android.keepass2android&data=02%7C01%7C%7Ce6cb3c42648b4dbb8cec08d6ab5dc0dc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636884816490224154&sdata=ieIr7RsIbM4EghCz6F1xKsBASRL1xtXA7VQaJaWmwuI%3D&reserved=0>?

**Comment by mabachel** [comment] 2019-03-18 06:21
Hi,
using Keepass2Android 1.07-pre6 with ykDroid 1.1.1 (@pp3345 ) I'm not able to open a database generated by KeePassXC 2.3.4 for Linux secured with Password an Callange-Response (YubiKey 5 NFC Slot 2).
See the log: [K2A1.07-pre6.txt](https://github.com/PhilippC/keepass2android/files/2976592/K2A1.07-pre6.txt)

**Comment by cybermcm** [comment] 2019-03-18 07:09
Not working for me either (used the link and got 1.07-pre5 (Settings->About))
If I select an entry from the database (with keepass2android keyboard) the app crashes...

**Comment by PhilippC** [comment] 2019-03-18 07:12
@mabachel did that ever work before?

**Comment by mabachel** [comment] 2019-03-18 08:09
It worked on K2A 1.06 on my Nexus 5 running LineageOS 14.1 (Android Nougat 7.1.2) with a YubiKey NEO. Same database.

**Comment by PereFouras007** [comment] 2019-03-18 08:11
hi,

A relatively useable and simple workaround I find to avoid the crash of the app when searching for an entry using app keyboard is to open and close a group directly when opening the DB and before doing the search.
sample :
- have to select an entry
- select the app kb 
- click on app icon to select an entry
- open or unlock the db if not already done
- at this point I have all the groups I create on the display.
- open one group (ie Other) then go back to main page.
- enter my search criteria on the top of screen
- select the right entry from the showed list.

the app didn't crash and i can then use the app kb with the selected entry fields to complete the requested informations.

hope these info can help.

**Comment by PhilippC** [comment] 2019-03-18 08:12
@mabachel can you test again with the NEO instead of the Yubikey 5? They have changes in NDEF interface. (I actually made changes to support Yubikey 5 for OTP/static password in KP2A, but the error in your log shows an issue with ykdroid which might not support Yubikey 5 yet -  I don't know)

**Comment by PhilippC** [comment] 2019-03-18 08:13
@cybermcm it may take a few hours until all devices are updated (potentially you can get the update faster if you manually click update in the Play store app). Please check again after the update has been installed.

**Comment by mabachel** [comment] 2019-03-18 08:17
sry.. I can't test since the NFC capability of my YubiKey NEO is not functioning anymore and I don't have a USB-C OtG cable on hand. :cry:

**Comment by cybermcm** [comment] 2019-03-18 10:09
@PhilippC: I've now upgraded to 1.07-pre6, error still remains.
I can confirm workaround from @PereFouras007, if I open a group -> go back -> search -> It's working (with pre6)

**Comment by mr-bolle** [comment] 2019-03-18 10:23
@PhilippC with the 1.07-pre6 i can successfully autofill the account to a Webpage. Before it often crashes, with my Samsung Note 9 - Android 9.

*Note: after updating the application, i force closed the application*

**Comment by ns740** [comment] 2019-03-18 10:50
@PhilippC confirming:  with 1.07-pre6 I still have the problem as reported for 1.07-pre5 here:

https://github.com/PhilippC/keepass2android/issues/712#issuecomment-473777984

... after choosing "Select Entry", then pressing the magnifier search button, i'm reprompted to unlock

**Comment by JeffSchre** [comment] 2019-03-18 16:41
@PhilippC - Testing KP2A Keyboard post 1.07-pre6 installation...app no longer crashes, however after selecting an entry in the Database it throws a "pseudo-error": "Could not open dialog to select input method.  Please activate keyboard manually", calling it a "pseudo-error" as the User/Password buttons do work to populate the Username/Password from the selected Database entry.

Process used for testing:
Open Chrome Browser and navigate to website requiring credentials
Switch to KP2A Keyboard
Tap the Lock
Tap Select Entry
Select the Entry I want from Database.....it is after this selection where the "pseudo-error" referenced above is thrown.

**Comment by ns740** [comment] 2019-03-20 23:29
@PhilippC 1.07-pre8 is working correctly for me now (Samsung Note 8, Android 9).    
Select entry does not reprompt to unlock again as in this report.  
https://github.com/PhilippC/keepass2android/issues/712#issuecomment-473777984
:+1:

**Comment by DesHorsley** [comment] 2019-03-21 01:09
@PhilippC resolved on my Note 9 too, thanks for the update

**Closed** 2019-03-21 03:52 UTC
Labels: samsung-android-9

**Comment by cybermcm** [comment] 2019-03-21 06:56
Thank you!

**Comment by mabachel** [comment] 2019-03-21 12:40
With 1.07-pre8 I still cannot unlock my database. Log is attached

[pre8.txt](https://github.com/PhilippC/keepass2android/files/2992025/pre8.txt)

My configuration again:
Using Keepass2Android 1.07-pre8 with ykDroid 1.1.1 (@pp3345 ) I'm not able to open a database generated by KeePassXC 2.3.4 for Linux secured with Password an Callange-Response (YubiKey 5 NFC Slot 2). I'm running AOSPExtended 6.4 (Android Pie with March Security Patch) on a Nexus 5X.

@PhilippC Shall I open another bug?

**Comment by PhilippC** [comment] 2019-03-22 04:01
@mabachel yes, and please open it on https://github.com/pp3345/ykDroid

**Comment by mabachel** [comment] 2019-03-23 12:26
https://github.com/pp3345/ykDroid/issues/10
