### ISSUE TITLE
[Feature request] Auto open last db

### ISSUE THREAD

**Issue by aeilkema** [PhilippC/keepass2android#223] opened 2018-01-24 14:52 UTC
Whould like to have an option like "auto open last used db".

I have 1 db, now i have to select db "open recent db" and then authorize with fingerprint.
If the last used DB opened by default, i whould only have to use fingerprint.

Makes everything just a little faster.

Thx, keep up the good work!

**Comment by PhilippC** [comment] 2018-02-04 18:41
duplicate of #216

**Closed by PhilippC** 2018-02-04 18:41 UTC
