### ISSUE TITLE
Support for face authentication to open storage file.

### ISSUE THREAD

**Issue by falkerson** [PhilippC/keepass2android#1148] opened 2020-02-09 10:36 UTC
Currently application support unlock by fingerprint which is very useful but some new devices (like Pixel 4) doesn't support fingerprint at all. It would be nice to have support for face authentication in such case.

**Comment by PhilippC** [comment] 2020-02-10 10:32
duplicate of https://github.com/PhilippC/keepass2android/issues/795

**Closed by PhilippC** 2020-02-10 10:32 UTC
