### ISSUE TITLE
Fingerprint not working on Pixel 2

### ISSUE THREAD

**Issue by poblabs** [PhilippC/keepass2android#62] opened 2017-10-22 14:26 UTC
Hi there, I had a Pixel 1 and everything worked great - even on Android 8. 

I got my Pixel 2 yesterday and the fingerprint portion isn't working within your app. I get a red exclamation error, and when I tap it I get the picture below. The app won't let me take a screenshot, so I used my Pixel 1 to capture the error on screen. 

Let me know how else I can help debug?

Edit: I removed something that looked important within the screenshot. Not sure if it is or not, so erring on the side of caution. 

<img src="https://i.imgur.com/e8oDk1v.png">

**Comment by PhilippC** [comment] 2017-10-23 08:32
duplicate of #37.

**Closed by PhilippC** 2017-10-23 08:32 UTC
