### ISSUE TITLE
Make old account info behind latest account in one entry

### ISSUE THREAD

**Issue by Edfgdz** [PhilippC/keepass2android#1836] opened 2021-11-11 11:07 UTC
Sometimes user would change their account password or username and make old ones not used anymore. 

For some reason user may don't want to delete those old account info directly because maybe those info would be useful in future. 

So is it possible to let user could make those old username or password stored behind latest account info to make them not deleted?

**Comment by PhilippC** [comment] 2021-11-11 19:07
duplicate of #298

**Closed by PhilippC** 2021-11-11 19:07 UTC
