### ISSUE TITLE
Can't synch from Android to OneDrive

### ISSUE THREAD

**Issue by abrush61** [PhilippC/keepass2android#1513] opened 2020-12-23 14:52 UTC
Last couple days, any update on Android is met with error in log below (Microsoft.Graph.ServiceException: Code: BadRequest
Message: The maximum request length supported is 4MB.).  Windows version still working fine.

Database is stored on OneDrive (O365).  That has not changed, used to work fine.  Database is about 4.1 Mb in size, does contain some attachments.  No new attachments in this timeframe.  Android 11 Build RQ1A.201205.003

12/23/2020 9:28:10 AM:813 -- status message: Saving database…
12/23/2020 9:28:10 AM:815 -- status submessage: Checking target file for changes…
12/23/2020 9:28:10 AM:817 -- getPathItem for onedrive2_myfiles://e78da0e0-eb58-4d9c-87a1-3e537fc6f0c3.9ffe4f04-2ddd-4626-b91c-a1f436adab77\abrush%40tegam.com\me\me\me\01PIVFJJO5AAGGDTQMDVEZ2IFYZ3KQRVGB%3AQWERTY%2F01PIVFJJIUJLOO5YBPINAIR2WDU6QJU3SQ%3ADatabase%2BActive%2B20201223.kdbx\b!GjqktM8UD0qj15c7lWxM8-fqd75qvp9AifzJ65m3laUvw8fdIrk-Q4nBnO7qJ-Ah?305
12/23/2020 9:28:48 AM:431 -- status submessage: Merging changes…
12/23/2020 9:28:48 AM:433 -- getPathItem for onedrive2_myfiles://e78da0e0-eb58-4d9c-87a1-3e537fc6f0c3.9ffe4f04-2ddd-4626-b91c-a1f436adab77\abrush%40tegam.com\me\me\me\01PIVFJJO5AAGGDTQMDVEZ2IFYZ3KQRVGB%3AQWERTY%2F01PIVFJJIUJLOO5YBPINAIR2WDU6QJU3SQ%3ADatabase%2BActive%2B20201223.kdbx\b!GjqktM8UD0qj15c7lWxM8-fqd75qvp9AifzJ65m3laUvw8fdIrk-Q4nBnO7qJ-Ah?305
12/23/2020 9:28:51 AM:57 -- ReadXmlStreamed: 1088ms
12/23/2020 9:28:51 AM:135 -- status submessage: 
12/23/2020 9:28:52 AM:574 -- Xml WriteDocument: 1431ms
12/23/2020 9:28:52 AM:763 -- getPathItem for onedrive2_myfiles://e78da0e0-eb58-4d9c-87a1-3e537fc6f0c3.9ffe4f04-2ddd-4626-b91c-a1f436adab77\abrush%40tegam.com\me\me\me\01PIVFJJO5AAGGDTQMDVEZ2IFYZ3KQRVGB%3AQWERTY%2F01PIVFJJIUJLOO5YBPINAIR2WDU6QJU3SQ%3ADatabase%2BActive%2B20201223.kdbx\b!GjqktM8UD0qj15c7lWxM8-fqd75qvp9AifzJ65m3laUvw8fdIrk-Q4nBnO7qJ-Ah?305
12/23/2020 9:28:53 AM:74 -- getPathItem for onedrive2_myfiles://e78da0e0-eb58-4d9c-87a1-3e537fc6f0c3.9ffe4f04-2ddd-4626-b91c-a1f436adab77\abrush%40tegam.com\me\me\me\01PIVFJJO5AAGGDTQMDVEZ2IFYZ3KQRVGB%3AQWERTY%2F01PIVFJJIUJLOO5YBPINAIR2WDU6QJU3SQ%3ADatabase%2BActive%2B20201223.kdbx\b!GjqktM8UD0qj15c7lWxM8-fqd75qvp9AifzJ65m3laUvw8fdIrk-Q4nBnO7qJ-Ah?305
12/23/2020 9:28:53 AM:75 -- Path share is me
12/23/2020 9:28:53 AM:75 -- No special folder. Use drive root.
12/23/2020 9:28:53 AM:76 -- LocalPath = QWERTY/Database Active 20201223.kdbx
12/23/2020 9:28:53 AM:76 -- couldn't save to remote onedrive2_myfiles://e78da0e0-eb58-4d9c-87a1-3e537fc6f0c3.9ffe4f04-2ddd-4626-b91c-a1f436adab77\abrush%40tegam.com\me\me\me\01PIVFJJO5AAGGDTQMDVEZ2IFYZ3KQRVGB%3AQWERTY%2F01PIVFJJIUJLOO5YBPINAIR2WDU6QJU3SQ%3ADatabase%2BActive%2B20201223.kdbx\b!GjqktM8UD0qj15c7lWxM8-fqd75qvp9AifzJ65m3laUvw8fdIrk-Q4nBnO7qJ-Ah?305
12/23/2020 9:28:53 AM:79 -- Status Code: RequestEntityTooLarge
Microsoft.Graph.ServiceException: Code: BadRequest
Message: The maximum request length supported is 4MB.
Inner error:
	AdditionalData:
	date: 2020-12-23T14:28:52
	request-id: 8a86a15f-a46d-484d-9492-4368f192ff94
	client-request-id: 8a86a15f-a46d-484d-9492-4368f192ff94

  at Microsoft.Graph.HttpProvider.SendAsync (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x00374] in <57852a5918944a669d8860b34ce4a887>:0 
  at Microsoft.Graph.BaseRequest.SendRequestAsync (System.Object serializableObject, System.Threading.CancellationToken cancellationToken, System.Net.Http.HttpCompletionOption completionOption) [0x001c6] in <57852a5918944a669d8860b34ce4a887>:0 
  at Microsoft.Graph.BaseRequest.SendAsync[T] (System.Object serializableObject, System.Threading.CancellationToken cancellationToken, System.Net.Http.HttpCompletionOption completionOption) [0x0008b] in <57852a5918944a669d8860b34ce4a887>:0 
  at keepass2android.Io.OneDrive2FileStorage`1[OneDrive2PrefixContainerType].UploadFile (System.String path, System.IO.MemoryStream stream) [0x00051] in <d0bf64c0589048ecb8c19cb8be709fcc>:0 
  at keepass2android.Io.OneDrive2FileStorage`1+OneDrive2FileStorageWriteTransaction[OneDrive2PrefixContainerType].CommitWrite () [0x0001c] in <d0bf64c0589048ecb8c19cb8be709fcc>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <d0bf64c0589048ecb8c19cb8be709fcc>:0 
  at keepass2android.Io.CachingFileStorage.TryUpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00000] in <d0bf64c0589048ecb8c19cb8be709fcc>:0 
12/23/2020 9:28:53 AM:154 -- EntryEditActivity.OnPause

**Comment by PhilippC** [comment] 2020-12-28 11:22
duplicate of https://github.com/PhilippC/keepass2android/issues/1036

**Closed by PhilippC** 2020-12-28 11:22 UTC
