### ISSUE TITLE
Unable to unlock using fingerprint on Android 10

### ISSUE THREAD

**Issue by TheMadRuffian** [PhilippC/keepass2android#961] opened 2019-09-23 09:04 UTC
Tried configuring fingerprint unlock but it would show the option to unlock.

Device: Mi A1
Android version: 10
Rooted: Yes
App version:  1.07b-pre1

**Comment by PhilippC** [comment] 2019-09-24 02:18
is this a duplicate of https://github.com/PhilippC/keepass2android/issues/934 or do you mean something else?

**Comment by TheMadRuffian** [comment] 2019-09-24 06:58
No, it was not the same issue. But I made a mistake in configuring the database. Now everything is working properly. Kindly mark this issue "irrelevant" or delete it.

**Closed** 2019-09-29 07:41 UTC
