### ISSUE TITLE
User key on one line keyboard submits form

### ISSUE THREAD

**Issue by noorez** [PhilippC/keepass2android#151] opened 2017-12-05 15:02 UTC
Pressing the user key fills in the user name but it is also submitting the html form with no password. This does not happen though when clicking the password button. Causing issues as sites lockout the user name when too many of these bad attempts are made.

Current workaround is to fill in the password first

**Comment by PhilippC** [comment] 2017-12-06 03:44
duplicate of #89

**Closed by PhilippC** 2017-12-06 03:44 UTC
