### ISSUE TITLE
Select entry dialog does not display options on Android Pie devices

### ISSUE THREAD

**Issue by dymmeh** [PhilippC/keepass2android#528] opened 2018-08-29 18:40 UTC
Tested on a Pixel and emulator running 9.0

To reproduce

1. Open the kp2a keyboard
2. Pick the button to select a password entry
3. The Select Entry dialog pops up with no options aside from cancel
4. I'm still able to click on the options despite them not showing

![kp2a](https://user-images.githubusercontent.com/36926971/44807523-c8ad1d80-ab97-11e8-9f6b-c4bdfd17319c.gif)

**Comment by PhilippC** [comment] 2018-08-30 02:37
duplicate of #377

**Closed by PhilippC** 2018-08-30 02:37 UTC
