### ISSUE TITLE
https webdav

### ISSUE THREAD

**Issue by yangqingming** [PhilippC/keepass2android#1073] opened 2019-12-11 04:26 UTC
2019/12/11 12:21:08:775 -- DatabaseSettingsActivity.OnPause
2019/12/11 12:21:08:778 -- Timeout start
2019/12/11 12:21:10:378 -- DatabaseSettingsActivity.OnResume
2019/12/11 12:21:10:378 --  DatabaseIsUnlocked=True
2019/12/11 12:21:10:379 -- Timeout cancel
2019/12/11 12:21:13:126 -- DatabaseSettingsActivity.OnPause
2019/12/11 12:21:13:127 -- Timeout start
2019/12/11 12:21:13:154 -- GroupActivity.OnStart
2019/12/11 12:21:13:155 -- GroupActivity.OnResume
2019/12/11 12:21:13:156 --  DatabaseIsUnlocked=True
2019/12/11 12:21:13:156 -- Timeout cancel
2019/12/11 12:21:13:625 -- DatabaseSettingsActivity.OnStop
2019/12/11 12:21:13:626 -- DatabaseSettingsActivity.OnDestroyTrue
2019/12/11 12:21:17:285 -- status message: Initializing...
2019/12/11 12:21:17:286 -- status submessage: 
2019/12/11 12:21:17:324 -- status message: 同步缓存的数据库...
2019/12/11 12:21:17:325 -- status submessage: Loading source file…
2019/12/11 12:21:17:906 -- status submessage: Save file…
2019/12/11 12:21:18:56 -- stream was reset: NO_ERROR
2019/12/11 12:21:18:63 -- System.Exception: stream was reset: NO_ERROR ---> Java.IO.IOException: stream was reset: NO_ERROR
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <c8df2d9fc23e4c3e930589657120c656>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <c8df2d9fc23e4c3e930589657120c656>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.UploadFile (System.String path, System.Byte[] data, System.Boolean writeTransactional) [0x00059] in <179ff4a67460447fb7808ff0236d35d7>:0 
  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x0001c] in <3169fd143f40409586dc88385b819b66>:0 
   --- End of inner exception stack trace ---
  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x00036] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction) [0x00018] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.SynchronizeCachedDatabase.Run () [0x00178] in <3169fd143f40409586dc88385b819b66>:0 
2019/12/11 12:21:22:256 -- status message: Initializing...
2019/12/11 12:21:22:257 -- status submessage: 
2019/12/11 12:21:22:293 -- status message: 同步缓存的数据库...
2019/12/11 12:21:22:294 -- status submessage: Loading source file…
2019/12/11 12:21:22:459 -- stream was reset: PROTOCOL_ERROR
2019/12/11 12:21:22:460 -- System.Exception: stream was reset: PROTOCOL_ERROR ---> Java.IO.IOException: stream was reset: PROTOCOL_ERROR
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <c8df2d9fc23e4c3e930589657120c656>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <c8df2d9fc23e4c3e930589657120c656>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <179ff4a67460447fb7808ff0236d35d7>:0 
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <3169fd143f40409586dc88385b819b66>:0 
   --- End of inner exception stack trace ---
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0002b] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.GetRemoteDataAndHash (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& hash) [0x00006] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.SynchronizeCachedDatabase.Run () [0x0005b] in <3169fd143f40409586dc88385b819b66>:0 
2019/12/11 12:21:27:234 -- GroupActivity.OnPause
2019/12/11 12:21:27:235 -- Timeout start
2019/12/11 12:21:27:251 -- DatabaseSettingsActivity.OnCreate
2019/12/11 12:21:27:252 -- DatabaseSettingsActivity:apptask=
2019/12/11 12:21:27:282 -- DatabaseSettingsActivity.OnStart
2019/12/11 12:21:27:282 -- DatabaseSettingsActivity.OnResume
2019/12/11 12:21:27:282 --  DatabaseIsUnlocked=True
2019/12/11 12:21:27:283 -- Timeout cancel
2019/12/11 12:21:27:733 -- GroupActivity.OnStop

**Comment by PhilippC** [comment] 2019-12-12 05:13
duplicate of https://github.com/PhilippC/keepass2android/issues/747 
If you can disable HTTP/2, this is the current workaround until OkHttp is fixed.

**Closed by PhilippC** 2019-12-12 05:13 UTC
