### ISSUE TITLE
Authentication Error with pcloud

### ISSUE THREAD

**Issue by Lars-KIM** [PhilippC/keepass2android#1355] opened 2020-08-06 12:03 UTC
Hello,
can't access my pcloud account as storage for kbdx file as the authentication attempt goes in endless loop.

Try to setup KP2A on a new Samsung Galaxy A41 with 

- Android 10 (Patch level June 2020), 

- Keepass2Android Version 1.07b-r0, 

- pcloud Version 2.9.1. 

On attempt to open pcloud location i insert my credentials and KP2A tries endlessly to access pcloud. Access to my account via pcloud app is possible on A41, as is the usage of KP2A with pcloud on two other devices.

Expected behavior is successfull access of pcloud share or an time out error.

**Comment by majjhima** [comment] 2020-08-24 20:13
I believe this is a duplicate of #1257 

I just upgraded my phone and with the Samsung Smart Switch it managed to copy my pre-existing configuration over so I can still authenticate with pcloud using keepass2android, but my son wasn't able to setup a new connection on his phone.

**Comment by PhilippC** [comment] 2020-10-05 08:57
duplicate of #1257

**Closed by PhilippC** 2020-10-05 08:57 UTC
