### ISSUE TITLE
Publish app to F-Droid

### ISSUE THREAD

**Issue by scollovati** [PhilippC/keepass2android#1000] opened 2019-10-21 19:32 UTC
Why don't you publish also your app on F-Droid catalogue? 
https://f-droid.org/ I's a nice place for FOSS applications.

**Comment by PhilippC** [comment] 2019-10-21 21:18
duplicate of https://github.com/PhilippC/keepass2android/issues/38

**Closed by PhilippC** 2019-10-21 21:18 UTC
