### ISSUE TITLE
Keepass2Android will not show updates to database made with KeepassXC

### ISSUE THREAD

**Issue by GavinDuley** [PhilippC/keepass2android#1143] opened 2020-02-05 01:36 UTC
I am using Keepass2Android on Android with Android 9.1.0, with a kdbx file saved on Google Drive. Keepass2Android does not show recent updates made using KeePassXC (Windows/Linux) or Strongbox (iOS). The version on Google Drive shows that it has been updated recently, so clearly Keepass2Android is relying on an old, cached version. If I try to get Keepass2Android to update the database it says (filename).kdbx "is trashed". It clearly is **not**, since it can be opened with KeePassXC and Strongbox. Saving the database with a new file name in KeePassXC results in a file that Keepass2Android can open, oddly.

**Comment by PhilippC** [comment] 2020-02-10 08:20
This sounds a lot like a duplicate of https://github.com/PhilippC/keepass2android/issues/882
Bottomline: your GDrive sync on your PC does not update the file correctly, instead it moves the file to trash and creates a new file on the same location. KP2A cannot rely on file location because you can have two files with the same name in the same folder in GDrive. Files are identified by an ID and that should not change. Please see the linked issue on how to resolve this on PC side.

**Closed by PhilippC** 2020-02-10 08:20 UTC

**Comment by GavinDuley** [comment] 2020-02-10 12:14
Hi Philipp, 
Thanks for the response. It does look to be the same as #882. This is a rather bizarre error, but seems to be a fault with GDrive rather than with KP2A. I'll try out the suggestions in #882. 
Thanks again,
gavin,
