### ISSUE TITLE
Regression:  can't select file from third party app anymore (for example, for the keyfile)

### ISSUE THREAD

**Issue by gbesacier** [PhilippC/keepass2android#78] opened 2017-10-26 22:47 UTC
When you use a keyfile and click the "change location" button to select it, you have a choice of several storage options. The first one is "system file selector" and the last one "third party app". In KP2A 1.01 and lower, the screen these options open look the same but the "third party app" one has more items in the hamburger menu (including all the file managers installed on the device). In KP2A 1.02, the two options "system file selector" and "third party app" are completely identical and you can no longer use any third party app to receive the key.

Reverting to version 1.01 brings back the third party apps in the "third party app" screen.

**Comment by PhilippC** [comment] 2017-10-29 05:07
duplicate of #77

**Closed by PhilippC** 2017-10-29 05:07 UTC
