### ISSUE TITLE
Unable to export to onedrive with keepass2android

### ISSUE THREAD

**Issue by thim19200** [PhilippC/keepass2android#1129] opened 2020-01-24 13:27 UTC
Export to onedrive always fails.
Message says "cannot export empty file".
The database is not empty: it can be exported to Google drive correctly.

**Comment by PhilippC** [comment] 2020-02-04 00:55
duplicate of https://github.com/PhilippC/keepass2android/issues/1053

**Closed by PhilippC** 2020-02-04 00:55 UTC
