### ISSUE TITLE
Database in OneDrive login issue

### ISSUE THREAD

**Issue by exlixx** [PhilippC/keepass2android#1495] opened 2020-12-07 12:29 UTC
My Keepass2android database is kept in OneDrive.

When I access this database, after passing the Keepass login steps, a Microsoft login screen would then pop up, asking for sign in.

I just need to press the "X" to close off this MS Onedrive sign in screen without affecting anything and continue with the keepass app...

This doesn't happen all the time, maybe around 70% of the access.

This "extra" step is just annoying... Is there anyway to disable it?

Thanks for advice.

**Comment by PhilippC** [comment] 2020-12-14 11:10
closing as duplicate of #1038

**Comment by towadroid** [comment] 2021-02-19 07:08
Suggest to close, as #1038 was closed via https://github.com/PhilippC/keepass2android/commit/15d3492ae37fc18c8fd38994f5f13154de53286d.

**Closed** 2021-02-19 10:20 UTC
