### ISSUE TITLE
Biometric 

### ISSUE THREAD

**Issue by gadget-dh** [PhilippC/keepass2android#2655] opened 2024-08-29 05:21 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

[BUG] ive just setup a new phone... galaxy A54. This prog release does not offer biometric unlock.

### Describe what you expected to happen:

Biometric unlock

### What version of Keepass2Android are you using?

1.11-r0

### Which version of Android are you on?

14

**Comment by JusticeWatch** [comment] 2024-09-15 05:51
This is also occurring on my Moto G Stylus 5G 2024
This may have to do with the new style of fingerprint scanner on the latest devices located behind the screen; it worked fine on my Pixel 2 XL and Pixel 3a, which have backside fingerprint scanners.

Moto G Stylus 5G 2024
App ver: 1.10-pre
Android: 14
Android build: U2UBS34.44-57-6

Pixel 2 XL
App ver: 1.10-pre
Android: 11
Android build: RP1A.201005.004.A1

Pixel 3A
Android: 12

**Comment by gadget-dh** [comment] 2024-09-15 16:55
Thanks for the feedback. I got it working.

Looks like when I copied all the apps to the new phone (samsung migration
tool), the biometric function was turned off, and the app did not ask me if
I wanted to use that the first time I logged in. Which is what I expected.
As I recall, I had to go deep into the settings to find it.

Doug

**Comment by JusticeWatch** [comment] 2024-09-16 07:32
Excellent, I got it to work as well.

I did not do direct migration; I configured my new device from factory without transferring data via Android's migration tool, so this must have something to do with the database settings. Under Settings > Database > Biometric Unlock, I recall having it set to "Enable Biometric Unlock for QuickUnlock" probably as I did on my previous device. I tried changing this to "Enable full Biometric Unlock", but this did not fix the issue.

What did fix the issue is disabling biometric unlock. Then after hitting back to the Password menu, I saw a notification on the bottom saying something like "Keepass2Andoid has detected biometric scanner on this device, would you like to enable biometric unlock?" and I tapped Yes, scanned my fingerprint, and now the thing works perfectly when I lock and reopen the database.

Also worth noting that all devices were accessing the same remote database file.

**Closed** 2024-09-23 06:37 UTC
Labels: bug
