### ISSUE TITLE
Android Pie: Dialog not appearing properly

### ISSUE THREAD

**Issue by wirecuttr** [PhilippC/keepass2android#505] opened 2018-08-15 03:45 UTC
There is an issue with Android Pie. When pressing the keyboard button that looks like the app icon a dialog appears on the screen, but only the lower portion of the dialog is visible with a Cancel link. Tapping in the above portion where the dialog should appear does progress to the app quick unlock page ok, but I have no idea what the dialog actually says since it's not visible.

**Comment by PhilippC** [comment] 2018-08-15 04:50
duplicate of #377

**Closed by PhilippC** 2018-08-15 04:50 UTC
