### ISSUE TITLE
pCloud Sync not possible

### ISSUE THREAD

**Issue by DiggiMorris** [PhilippC/keepass2android#1522] opened 2021-01-03 22:32 UTC
I cannot login to pCloud. After giving my password I end in an infinite waiting loop. Any ideas?

**Comment by edrik** [comment] 2021-01-11 16:57
Fix should be on the way https://github.com/PhilippC/keepass2android/issues/1257#issuecomment-756560276

**Comment by PhilippC** [comment] 2021-01-12 15:02
duplicate of #1257

**Closed by PhilippC** 2021-01-12 15:02 UTC
