### ISSUE TITLE
Get a toast in Android using Firefox 

### ISSUE THREAD

**Issue by flowercow** [PhilippC/keepass2android#675] opened 2019-01-11 07:20 UTC
I get a toast when selecting the login field: 
"Found multiple web domains: valid=xxx, child=xxx".

most like this "https://bugzilla.mozilla.org/show_bug.cgi?id=1352011#c14"

basic info:  Firefox 64.0.2 in Android 9.0

After i upgraded my Firefox to 64.0.2, this problem occurred. If i close auto fill function in Android, or use google auto fill instead keepass2andriod, no toast appears.

**Comment by flowercow** [comment] 2019-01-11 07:55
even after i upgrade keepass2android to beta version, i still get such toast.

**Comment by Small-Ku** [comment] 2019-01-11 08:34
This issue might be the same issue with #592 ?

**Comment by flowercow** [comment] 2019-01-11 08:50
> This issue might be the same issue in #592 ?
Maybe the same issue.
I am using firefox 64.0.2 not firefox focus.
PhilippC has close issue #592 by this change
"https://github.com/PhilippC/keepass2android/commit/e2e7666c4ff77b70d412ca0599d5f6de495410e8" 
I think this should be fixed in the version 1.07, but i have upgraded to the beta version and no effect.

**Comment by kezmdor** [comment] 2019-01-11 09:01
I have the same issue.
Google Pixel 2 XL
Android 9
Firefox 64.0.1

**Comment by Small-Ku** [comment] 2019-01-11 09:21
> 
> 
> > This issue might be the same issue in #592 ?
> Maybe the same issue.
> I am using firefox 64.0.2 not firefox focus.
> PhilippC has close issue #592 by this change
> "[e2e7666](https://github.com/PhilippC/keepass2android/commit/e2e7666c4ff77b70d412ca0599d5f6de495410e8)"
> I think this should be fixed in the version 1.07, but i have upgraded to the beta version and no effect.

That fix was committed after 1.07pre3 released.
1.07pre3 releasing: 9 Dec, 2018
Fix: 10 Dec, 2018

**Comment by flowercow** [comment] 2019-01-11 14:11
i don't know whether the problem was fixed or not in beta version.

**Comment by gabrielambuehl** [comment] 2019-01-12 17:54
Still seeing this in beta3. Also others confirmed it in #562.

**Comment by ouzowtf** [comment] 2019-01-12 21:48
The reason for why is not fixed in 1.07pre3 is already written in this thread...

**Comment by zoltanmaric** [comment] 2019-04-11 16:09
I'm still having this issue in Firefox Focus on Xiaomi Mi A2 with Android 9

**Comment by Small-Ku** [comment] 2019-04-12 13:39
> 
> 
> I'm still having this issue in Firefox Focus on Xiaomi Mi A2 with Android 9

Which version of Keepass2Android you are using?

**Comment by zoltanmaric** [comment] 2019-04-13 07:45
Sorry, I didn't realize that this was only fixed in the current beta release (1.07) I signed up for the beta program, and installed the latest beta and now it works great. Thanks!

**Comment by PhilippC** [comment] 2019-04-13 07:50
fixed in 1.07

**Closed by PhilippC** 2019-04-13 07:50 UTC
