### ISSUE TITLE
Focus search field after choosing "Select entry" 

### ISSUE THREAD

**Issue by zeraien** [PhilippC/keepass2android#926] opened 2019-08-23 19:18 UTC
When using k2a keyboard, when you need to manually select entry or you choose "Select entry" which opens k2a app, but at this point the search field is not focused, even if you have the option set to automatically focus the search field when starting the app.

steps:
0. set "Activate search field on start" setting
1. activate k2a keyboard
2. press k2a button
3. choose "Select entry"
4. expect search field to be focused and keyboard to show.

**Comment by PhilippC** [comment] 2019-08-27 02:13
I suspect this is a duplicate of https://github.com/PhilippC/keepass2android/issues/858 (please re-open if not)

**Closed by PhilippC** 2019-08-27 02:13 UTC
