### ISSUE TITLE
Add mnemonics to generator

### ISSUE THREAD

**Issue by stp-ip** [PhilippC/keepass2android#640] opened 2018-12-15 23:49 UTC
Even so a password generator makes it more unlikely to type passwords manually or remember them. An option to use mnemonics/passhprases would be great.

Could be using a custom word list or one that is widely used such as [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) or [slip39](https://github.com/satoshilabs/slips/blob/master/slip-0039/wordlist.txt).

Just an idea. Thanks for providing keepass2android.

**Comment by PhilippC** [comment] 2018-12-16 19:45
duplicate of #284

**Closed by PhilippC** 2018-12-16 19:45 UTC
