### ISSUE TITLE
keepass2Android can't work well with firefox 84.1.4

### ISSUE THREAD

**Issue by flowercow** [PhilippC/keepass2android#1535] opened 2021-01-12 04:40 UTC
after upgrade firefox to 84.1.4, keepass2android can not work well. when type the autofill button, user and passwd area are blank.

emui11 based on android 10

**Comment by PhilippC** [comment] 2021-01-12 05:54
duplicate of #1399

**Closed by PhilippC** 2021-01-12 05:54 UTC
