### ISSUE TITLE
Dropbox sync changes filename

### ISSUE THREAD

**Issue by alfonder** [PhilippC/keepass2android#1632] opened 2021-03-31 17:08 UTC
The problem is syncing between different platforms via Dropbox. 
When I open with KP2A a DB named e.g. MyPasswords.kdbx then on next save it becomes renamed to mypasswords.kdbx and DropBox reports about letter-case conflict.
So synchronization gets broken.

**Comment by PhilippC** [comment] 2021-04-09 09:12
duplicate of https://github.com/PhilippC/keepass2android/issues/898

**Closed by PhilippC** 2021-04-09 09:12 UTC
