### ISSUE TITLE
ChromeOs v.97 endless parsing database

### ISSUE THREAD

**Issue by giopas** [PhilippC/keepass2android#1868] opened 2021-12-16 20:27 UTC
I am using Keepass2Android v. 1.09b-r1 on my ChromeOS.

Until now I had no particular issues (app design on big screen aside). But probably since I upgraded to v. 97 of the ChromeOS the database, even if it appears to synchronize correctly, does not open ans I have the endless spinning dialog box: "Working... loading database...(Parsing database...)."

I am not sure if this is related to the ChromeOS version or to the app, so I am reporting it here.

**Comment by DesplaG** [comment] 2021-12-25 20:01
In case it can help, I went trough the same trouble with v 1.09 and ChromeOS Version 96.0.4664.111 (Official Build) (64-bit) and a database on OneDrive.

I uninstalled Keepass2Android
Reinstalled Keepass2Android from the PlayStore
Opened a database from: OneDrive
Entered credentials to OneDrive + 2nd FA
Entered the database master password
... Then it works

Maybe some issue related to OneDrive folders permissions !?

Hoping it can do it for you as well,

**Comment by waaweech** [comment] 2022-01-27 01:25
@giopas - I've the same issue and have opened https://github.com/PhilippC/keepass2android/issues/1884.

See my workaround (minimizing/maximizing window) in https://github.com/PhilippC/keepass2android/issues/1884. It works for me.

**Comment by DesplaG** [comment] 2022-01-27 14:55
@waaweech Thanks for sharing. I have successfully tested the minimize/maximize workaround. I had to do this 3 times before it opened, but it did.

I will continue to follow on  [#1884](https://github.com/PhilippC/keepass2android/issues/1884).

Thanks

**Comment by waaweech** [comment] 2022-01-27 15:07
> @waaweech Thanks for sharing. I have successfully tested the minimize/maximize workaround. I had to do this 3 times before it opened, but it did.
> 
> I will continue to follow on [#1884](https://github.com/PhilippC/keepass2android/issues/1884).
> 
> Thanks

@DesplaG - You are welcome. I usually wait for a few seconds before min/maxing the window. You may want to wait a few seconds more.

**Comment by PhilippC** [comment] 2022-01-31 08:24
Closing this is duplicate of #1884 (even though it was opened earlier)

**Closed by PhilippC** 2022-01-31 08:24 UTC
