### ISSUE TITLE
Failed saving main database to OneDrive

### ISSUE THREAD

**Issue by lostgit** [PhilippC/keepass2android#1158] opened 2020-02-21 05:18 UTC
Affected versions: the latest beta as well as the official release. 

I have a main db with a child db, both in the same OneDrive personal account. The main db always fails to save. The child db, on the other hand, always saves successfully. I noticed that the URLs are different, even though they are on the same account. The main db cannot be saved regardless of the OneDrive file-open options (All files & Shared, My Files, KeePass App Folder).

The main DB failed to save with either of these URLs:
`onedrive2_full://myaccount@tld.com/me/main.kdbx
onedrive2_myfiles://myaccount@tld.com/me/main.kdbx
onedrive2_appfolder://myaccount@tld.com/me/main.kdbx
`

The child DB always saves with this simpler URL as configured in the main DB:
`onedrive:///foldername/child.kdbx`

- We can rule out  #1038  or any authentication or connection caching issue because the child DB successfully saves using the same OneDrive connection (to forget login, I can purge the cached authentication/connection by logging out of OneDrive on Chrome).
- We can also rule out any issue with the main DB file, because that db can be saved to Google Drive without issues.  

Below is the log:
```
2/20/2020 10:57:22 PM:879 --  DatabaseIsUnlocked=True
2/20/2020 10:57:22 PM:880 -- Timeout cancel
2/20/2020 10:57:23 PM:83 -- GroupActivity.OnStop
2/20/2020 10:57:29 PM:496 -- status message: Initializing...
2/20/2020 10:57:29 PM:497 -- status submessage: 
2/20/2020 10:57:29 PM:519 -- status message: Saving database…
2/20/2020 10:57:29 PM:520 -- status submessage: Checking target file for changes…
2/20/2020 10:57:33 PM:780 -- status submessage: 
2/20/2020 10:57:35 PM:992 -- Xml WriteDocument: 1998ms
2/20/2020 10:57:37 PM:549 -- couldn't save to remote onedrive2_myfiles://00000000-0000-0000-cba1-02813380b745.9188040d-6c67-4c5b-b112-36a304b66dad\lostgit%40tld.com\me\me\me\CBA102813380B745!17260%3AKeePass%2FCBA102813380B745!17264%3main.kdbx\cba102813380b745?230
2/20/2020 10:57:37 PM:550 -- Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
  at Microsoft.Graph.HttpProvider+<SendAsync>d__18.MoveNext () [0x001e4] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Graph.BaseRequest+<SendRequestAsync>d__35.MoveNext () [0x001c6] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Graph.BaseRequest+<SendAsync>d__31`1[T].MoveNext () [0x0008b] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at keepass2android.Io.OneDrive2FileStorage`1[OneDrive2PrefixContainerType].UploadFile (System.String path, System.IO.MemoryStream stream) [0x0003b] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.OneDrive2FileStorage`1+OneDrive2FileStorageWriteTransaction[OneDrive2PrefixContainerType].CommitWrite () [0x0001c] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.TryUpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00000] in <3169fd143f40409586dc88385b819b66>:0 
2/20/2020 10:57:37 PM:582 -- Starting/Updating OngoingNotificationsService. Database Unlocked
2/21/2020 12:10:58 AM:641 -- status message: Initializing...
2/21/2020 12:10:58 AM:641 -- status submessage: 
2/21/2020 12:10:58 AM:681 -- status message: Synchronizing cached database…
2/21/2020 12:10:58 AM:684 -- status submessage: Loading source file…
2/21/2020 12:11:01 AM:721 -- status submessage: Save file…
2/21/2020 12:11:03 AM:211 -- Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
  at Microsoft.Graph.HttpProvider+<SendAsync>d__18.MoveNext () [0x001e4] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Graph.BaseRequest+<SendRequestAsync>d__35.MoveNext () [0x001c6] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Graph.BaseRequest+<SendAsync>d__31`1[T].MoveNext () [0x0008b] in <6e1866892f3346e7ba899a6dc936762c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at keepass2android.Io.OneDrive2FileStorage`1[OneDrive2PrefixContainerType].UploadFile (System.String path, System.IO.MemoryStream stream) [0x0003b] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.OneDrive2FileStorage`1+OneDrive2FileStorageWriteTransaction[OneDrive2PrefixContainerType].CommitWrite () [0x0001c] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction) [0x00018] in <3169fd143f40409586dc88385b819b66>:0 
  at keepass2android.SynchronizeCachedDatabase.Run () [0x00178] in <3169fd143f40409586dc88385b819b66>:0 
```

**Comment by PhilippC** [comment] 2020-02-23 06:43
is it possible that this file is ~10MB or more? This would explain this behavior and is currently a known issue (the MS Grap API requires special steps to upload large files)

**Comment by lostgit** [comment] 2020-02-26 04:19
@PhilippC, the file is 6.5 MB
1. I deleted some entries to reduce the size to 5.3 MB and still had some issues. 
2. I deleted more entries to reduced the size to 3.6 MB and was able to save.

Seems like the MS Grap API limit, without the special steps, is between 3.6 and 5.3 MB, which is very unfortunate as this is not "big" at all.  

However, my file has hovered around 6.5MB for a while without issue before. Is K2A using new MS Grap API?

**Comment by PhilippC** [comment] 2020-03-02 09:35
interesting. According to https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0, the limit is 10MB.
The old implementation was using the OneDrive SDK which seemed to handle this better. Closing this as duplicate of https://github.com/PhilippC/keepass2android/issues/1036

**Closed by PhilippC** 2020-03-02 09:35 UTC
