### ISSUE TITLE
Auto-fill Is Triggered In Google Translate

### ISSUE THREAD

**Issue by gloomy-ghost** [PhilippC/keepass2android#262] opened 2018-02-21 05:11 UTC
![img_20180221_180908_740](https://user-images.githubusercontent.com/13086421/36464025-56bf9f94-1732-11e8-8492-4bc2b3c2b83b.jpg)
Apparently this is not a place where we want to fill in passwords... How did the text field be detected as a password field?

**Comment by Mysticodex** [comment] 2018-02-23 08:30
I have the same issue, but in a Reddit app (not web based) called Baconreader.

**Comment by alxkrylov** [comment] 2018-02-24 18:12
Upvoting. The same issue in my GT.

**Comment by PhilippC** [comment] 2018-03-26 18:22
fixed, duplicate of #303 (or vice versa)

**Closed by PhilippC** 2018-03-26 18:22 UTC
