### ISSUE TITLE
[BUG] no installation on Chromebook v119

### ISSUE THREAD

**Issue by MrSellerie** [PhilippC/keepass2android#2487] opened 2023-12-31 18:34 UTC
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

The app is still not listed in Google Play Store on Chromebook Google Coral. i see only the translated message:
"Keepass2Android by Philipp Crocoll (Croco Apps) is not available on this device."

I have read the issuses #2316 #2448 and #2465 but i see no progress since a month.

### What version of Keepass2Android are you using?

Version 1.09c-r0

### Which version of Android are you on?

Android 9

**Comment by PhilippC** [comment] 2024-01-09 04:59
duplicate of #2316

**Closed by PhilippC** 2024-01-09 04:59 UTC
Labels: bug
