### ISSUE TITLE
Keyboard no longer works on Android 9

### ISSUE THREAD

**Issue by Schvenn** [PhilippC/keepass2android#508] opened 2018-08-15 21:10 UTC
I upgraded to Android pie yesterday and now the keyboard button to the left of the spacebar doesn't provide any options.
Pixel XL 2

**Comment by schrauger** [comment] 2018-08-16 19:55
I'm having the same problem, only after upgrading to Android pie.
The Essential Phone

**Comment by Schvenn** [comment] 2018-08-17 06:37
Odd, I would suspect that the keyboard would require the need to display over other apps, because that would likely fix this problem, but it doesn't require that permission.

**Comment by PhilippC** [comment] 2018-08-18 04:59
duplicate of #377

**Closed by PhilippC** 2018-08-18 04:59 UTC
