### ISSUE TITLE
keyboard modals are cutoff (Android P)

### ISSUE THREAD

**Issue by eleith** [PhilippC/keepass2android#377] opened 2018-05-14 02:55 UTC
1) on Android P beta
2) go to any webpage in chrome 
3) switch to keepass2android keyboard
4) press logo button to open up "select entry" modal
5) modal doesn't render. seems cutoff.
6) even with mini keyboard once an entry is selected, the logo button leads to a cutoff modal

not sure if this is an Android bug or keepass2android, however I haven't seen this bug on other apps yet...

**Comment by RailsRoyale** [comment] 2018-07-15 16:55
Can confirm that this happens on Android P on my Pixel 1. Quite frustrating.

**Comment by AviKav** [comment] 2018-08-02 00:10
Confirmed on PH-1 on Beta 4

**Comment by et304383** [comment] 2018-08-18 13:30
Damn. This is a pretty serious issue affecting everyone on Android Pie.

**Comment by Topher2014** [comment] 2018-08-20 01:11
Same issue on PH-1 running Android 9. Glad I'm not the only one, hope it's addressed in update. That feature made it not only safer but so much faster.

**Comment by PhilippC** [comment] 2018-08-21 18:47
I am currently publishing 1.06b to the beta channel (https://play.google.com/apps/testing/keepass2android.keepass2android). Please let me know if this fixes the issue for you.

**Comment by eleith** [comment] 2018-08-22 03:37
confirmed. thanks @PhilippC. :clap:

**Comment by AviKav** [comment] 2018-08-22 04:17
Chrome:

It seems that when the new dialog is used, any selected field need to be reselected. This results prevents TOTP input via K2A keyboard.

Note: Visually, the field appears to be selected.

Chrome 68.0.3440.91

Android 9.0.0; PH-1 Build/PPR1.180610.091

**Comment by solikeumyeah** [comment] 2018-08-23 12:34
I can confirm what AviKav said. The reported issue is fixed, but breaks inputting custom strings from the K2A menu into form fields in Chrome. It works in the address bar.

**Comment by PhilippC** [comment] 2018-08-27 10:15
I have changed the way additional fields are entered: Instead of using the dialog, click the new ">" button which changes the user/password buttons. Please let me know if this implementation is ok for you. It should not cause issues with inputting any longer.

**Comment by PhilippC** [comment] 2018-08-27 10:16
it's in the 1.06c which is now in beta.

**Comment by solikeumyeah** [comment] 2018-08-28 21:01
I'm testing the fix with 1.06d. The new ">" button fixes the field input issue in Chrome. There are several usability issues, however.

- The first item in the keyboard menu is now "Search for entry with %1$s", which just goes to the K2A main screen, not matching any entry.
![image](https://user-images.githubusercontent.com/9821269/44750153-ff634380-ab57-11e8-906a-7aa1bb353ef7.png)

- The second item is "Open the keyboard
Touch any text field." (with a line feed). It's not clear from the label what this would do. Tapping it does what I expected the _other_ item to do; switches to K2A to match an entry, then back to the current app.

-At this point the keyboard menu remains open, requiring the user to hit "Cancel" after matching an entry.

- The text input field of the current app loses focus at this time, hiding the keyboard, and requiring the user to tap the input field again.

- The text on the new keyboard entry buttons may extend outside the button geometry and overlap other keyboard buttons.
![image](https://user-images.githubusercontent.com/9821269/44750542-050d5900-ab59-11e8-9e48-b9f435720095.png)

- The first item in the keyboard menu is now "Close the keyboard
Press the Back key." (with a line feed). It's not clear from the label what this would do. Tapping it just opens the K2A main screen.
![image](https://user-images.githubusercontent.com/9821269/44750402-9f20d180-ab58-11e8-9e69-a9190dd1877c.png)

**Comment by PhilippC** [comment] 2018-08-30 02:16
@solikeumyeah sorry for the trouble, most of the issues seem to be caused by a broken build of the app. Sorry that I didn't test this earlier. (1.06d was just a minor code change to 1.06c, but the broken build has changed much more.)

> At this point the keyboard menu remains open, requiring the user to hit "Cancel" after matching an entry.

I can't reproduce. Please check if this still happens with 1.06e.

> The text input field of the current app loses focus at this time, hiding the keyboard, and requiring the user to tap the input field again.

Unfortunately this seems hardly avoidable: https://stackoverflow.com/questions/51906586/display-dialog-from-input-method-service-in-android-9-android-pie?noredirect=1#comment90917249_51906586

> The text on the new keyboard entry buttons may extend outside the button geometry and overlap other keyboard buttons

I think this should be less of a problem in 1.06e when the strings are correct. In my tests it does not look very nice but isn't a big deal. 

Please let me know what you think about 1.06e.

**Comment by solikeumyeah** [comment] 2018-08-30 13:08
> I can't reproduce. Please check if this still happens with 1.06e.

Fixed in 1.06e.

> I think this should be less of a problem in 1.06e when the strings are correct. In my tests it does not look very nice but isn't a big deal.

I have some custom strings that are around 16 characters and the experience is pretty bad - it's impossible to tell which button the text belongs to. May I suggest truncating the text at 8 characters? I think this tweak would make this method release-worthy.

**Comment by DDoSolitary** [comment] 2018-09-02 08:45
I got a problem after the recent upgrades. When typing an entry with a empty username field, the username button on the keyboard types the password and the password button types the entry name.

**Comment by PhilippC** [comment] 2018-09-08 04:57
@ConorIA I cannot reproduce this. Are you sure you are running 1.06e? Can you write detailed steps how you change entries?

**Comment by PhilippC** [comment] 2018-09-08 05:04
@ConorIA ok, I just found a way to reproduce: 
* Open an entry
* open keyboard, change buttons by clicking >
* Switch to ABC mode
* close keyboard by leaving input view
* switch entry
* open keyboard again

**Comment by DDoSolitary** [comment] 2018-09-11 05:59
It seems that my problem is fixed after the latest update. Thanks.

**Closed** 2018-09-21 03:48 UTC
