### ISSUE TITLE
Feature request: Google Drive - Allow accessing of "Shared with me" directory or allow opening of Google Drive shortcuts (of keepass databases)

### ISSUE THREAD

**Issue by wlwda** [PhilippC/keepass2android#1562] opened 2021-02-06 07:55 UTC
Google Drive removed the "Add to Drive" and instead replaced it with "Add Shortcut to Drive" which is a shortcut link that keepass2android can't open. 

Being able to go to the "Shared with me" directory seems the simplest way to access shared databases. Though it might be easier for users to remember directories in their "My Drive" and so if keepass2android can, and if it's easy to, open databases that are Google Drive shortcuts, then this might be the preferred feature request.

Thank you

**Comment by PhilippC** [comment] 2021-02-07 18:50
duplicate of https://github.com/PhilippC/keepass2android/issues/189

**Closed by PhilippC** 2021-02-07 18:50 UTC
