### ISSUE TITLE
Keepass2android - Sync with OnDrive not possible

### ISSUE THREAD

**Issue by horstwutscher** [PhilippC/keepass2android#1334] opened 2020-07-24 09:55 UTC
Hello,
I am using Keepass2android with my mobile phone and also over Win10 Client, the normal Keepass Version.
The database is sotroed on Ondrive.

My Keepass Database size is about 20MB.

Now I am not able to snyc my database from mobile phone with OneDrive.
The error message is, see screenshot.

![Screenshot_20200723-072931_One UI Home](https://user-images.githubusercontent.com/38691598/88379930-00cd3300-cda4-11ea-96cc-557d4a9e20e9.jpg)

How is it now possible to sync the data from mobile phone to the keepass at OneDrive?

I didn't find the "local - cache" keepass Database on my phone storage? That I am able to copy them to OneDrive with copy paste.

I hope somebody can help me, would be great :-)

Horst

**Comment by PhilippC** [comment] 2020-07-25 13:24
duplicate of https://github.com/PhilippC/keepass2android/issues/1036

**Closed by PhilippC** 2020-07-25 13:24 UTC
