### ISSUE TITLE
Switch keyboard to privacy mode when using Keepass

### ISSUE THREAD

**Issue by Stan-Tastic** [PhilippC/keepass2android#723] opened 2019-02-21 08:56 UTC
I'm a user of GBoard (Google keyboard app), and my phone (SGS7 Oreo) is not rooted.

GBoard has built-in "privacy mode", and some applications seem to be able to call on it when entering private data. I noticed recently that KeepassAndroid does not do this - everything I put into the app potentially reaches Google cloud (well, it's disabled for me, but you get the idea).

Is it possible for you to update the app so it switches keyboard into privacy mode? (and yes, I understand that general solution is "use Keepass keyboard instead" :D).

**Comment by JohnLGalt** [comment] 2019-02-22 16:25
Hi, Stan,

I didn't realize that this existed, so I went looking for it.  I'm on a Pixel 2 XL with GBoard as my daily driver, full stock, no root.

In searching the 'inerwebs', I found many an article from late 2016 - mid 2017 regarding the privacy mode of GBoard - **but only when using Chrome incognito mode**.  I did find one article on how to, I suppose, simulate, the privacy mode, but basically it boils down to just disabling sharing analytics and snippets to Google servers.  See https://www.guidingtech.com/stop-gboard-collecting-personal-data/

Are you saying that you're able to use the incognito mode of GBoard outside of Chrome Incognito mode?

**Comment by Stan-Tastic** [comment] 2019-02-25 06:06
Hi,
Yes, I initially thought it's limited to Google apps, but then I started
noticing it elsewhere - from the top of my head Signal also uses it. I
think I saw it somewhere else as well, but I'm not certain.

pt., 22 lut 2019, 17:25 użytkownik John L. Galt <notifications@github.com>
napisał:

**Comment by Stan-Tastic** [comment] 2019-02-25 06:09
Ah, it's also enabled in Samsung Browser private mode.

pon., 25 lut 2019, 07:06 użytkownik Stanislaw Kaminski <
stasheck.fora@gmail.com> napisał:

**Comment by JohnLGalt** [comment] 2019-02-27 21:38
Interesting.  I don't use Signal and I don't have any Sammy devices (Motorola-made Nexus 6 and Google branded Pixel 2 XL are my 2 most recent devices).

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2019-03-04 05:23
Duplicate with my #718  issue open

IME_FLAG_NO_PERSONALIZED_LEARNING
added in API level 26
public static final int IME_FLAG_NO_PERSONALIZED_LEARNING

Flag of imeOptions: used to request that the IME should not update any personalized data such as typing history and personalized language model based on what the user typed on this text editing object. Typical use cases are:

When the application is in a special mode, where user's activities are expected to be not recorded in the application's history. Some web browsers and chat applications may have this kind of modes.
When storing typing history does not make much sense. Specifying this flag in typing games may help to avoid typing history from being filled up with words that the user is less likely to type in their daily life. Another example is that when the application already knows that the expected input is not a valid word (e.g. a promotion code that is not a valid word in any natural language).
Applications need to be aware that the flag is not a guarantee, and some IMEs may not respect it.

Constant Value: 16777216 (0x01000000)

**Comment by jmichael2497** [comment] 2019-03-13 01:03
Duplicate of #718

**Comment by lindhe** [comment] 2019-12-21 11:57
I guess this is the same as #718

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2019-12-21 14:14
>
> I guess this is the same as #718

> > Duplicate with my #718 issue open
>

**Comment by PhilippC** [comment] 2020-01-06 10:58
closing as duplicate

**Closed by PhilippC** 2020-01-06 10:58 UTC
