### ISSUE TITLE
open file created with iterations

### ISSUE THREAD

**Issue by ms1222** [PhilippC/keepass2android#2180] opened 2023-01-04 23:12 UTC
I cannot open my file created with Keepass on a PC, I copied the .kdbx file and the keyfile.
Any suggestions (I plan on continuing using keepass on the PC and periodically copying the file to my Samsung tablet).

My database encryption algorithm is AES/Rijndael(256-bit, FIPS 197
and AES-KEF derivation function. with a couple of thousand iterations.

Thanks in advance.

**Comment by PhilippC** [comment] 2023-01-05 07:49
please create an example database and upload here including the password.

**Comment by ms1222** [comment] 2023-01-05 19:06
Attached are three docs:
1. the JPG key file (a picture)
2. a word doc which shows the settings that were used by keepass to create the kdbx file. including the password.
3. The kdbx file: note, please rename to delete the .txt (I had to do this to upload to github  (of course this  is not a text file!)


![Capture](https://user-images.githubusercontent.com/114269332/210859797-b7775131-9728-4e75-85f8-7d433c9c5841.JPG)
[test password databae settings and password.docx](https://github.com/PhilippC/keepass2android/files/10354972/test.password.databae.settings.and.password.docx)
[testdatabase.kdbx.txt](https://github.com/PhilippC/keepass2android/files/10354975/testdatabase.kdbx.txt).

When I copy the JPG and the KDBX file over to my Samsung Android,  I get an error when opening.   Your help is greatly appreciated.

**Comment by PhilippC** [comment] 2023-01-09 09:39
this is a duplicate of #1824. It seems like on some devices .jpg files do not work as key file. Unfortunately I cannot reproduce and thus cannot investigate this on my devices. Renaming the key file on Android or using a .keyx keyfile should help.

**Closed by PhilippC** 2023-01-09 09:39 UTC
