### ISSUE TITLE
Save needs 50 seconds to finish

### ISSUE THREAD

**Issue by RealSchlimbo** [PhilippC/keepass2android#945] opened 2019-09-07 12:30 UTC
My KeePass database is located at my Home NAS, and is only reachable when my Android device is connected to my home net.
If I'm not connected KeePass2Android is using the cashed database.

Whenever I open the database, add or change entrys there is a fix timeout of 25s to try connecting the network storage.
By saving changes it needs 50s to finish the save (25s for "Checking target files for changes" and than additional 25s for "saving database").

Is it possible to make this timeout adjustable or even to implement a fasters way to check the database connectivity?

**Comment by Karreg** [comment] 2019-09-07 15:12
This is probably due to security settings and not network. Your smartphone needs 25 seconds to open or close the database with these settings.
When sharing a database between desktop and mobile, I usually remove one digit to the '1 second' value set up by Keepass with AES. With Argon2, you can use the same settings on both with the latest kp2a beta version

**Comment by RealSchlimbo** [comment] 2019-09-07 22:10
Maybe my description was a bit unclear:
The problem is only present when I'm not connected to my home network and the database isn't reachable, in this case the changes are saved to the cashed local database on the device and will be synced later when the network storage is reachable again. 
If the database is reachable there isn't a delay by opening or saving.

Here is the logfile:
9/7/2019 2:33:37 PM:155 -- status message: Initializing...
9/7/2019 2:33:37 PM:156 -- status submessage: 
9/7/2019 2:33:37 PM:171 -- status message: Saving database…
9/7/2019 2:33:37 PM:173 -- status submessage: Checking target file for changes…
9/7/2019 2:34:02 PM:188 -- failed to connect to /192.168.0.1 (port 5000) from /192.168.178.23 (port 44089) after 25000ms
9/7/2019 2:34:02 PM:194 -- status submessage: 
9/7/2019 2:34:02 PM:431 -- Xml WriteDocument: 221ms
9/7/2019 2:34:27 PM:476 -- failed to connect to /192.168.0.1 (port 5000) from /192.168.178.23 (port 44091) after 25000ms
9/7/2019 2:34:27 PM:483 -- couldn't save to remote https://KeePassUser:password@192.168.0.1:5000/KeePass/KeyFile/KeePass2.kdbx
9/7/2019 2:34:27 PM:488 -- System.Exception: failed to connect to /192.168.0.1 (port 5000) from /192.168.178.23 (port 44091) after 25000ms ---> Java.IO.IOException: failed to connect to /192.168.0.1 (port 5000) from /192.168.178.23 (port 44091) after 25000ms
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <daf82fa226e64866b6883f2960c1a0f1>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.UploadFile (System.String p0, System.Byte[] p1, System.Boolean p2) [0x00092] in <bbfdbb1fb19a4f0a8a8c95bc1465a6cb>:0 
  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x0001c] in <d9555282dea14061ab4400355adad9e4>:0 
   --- End of inner exception stack trace ---
  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x00036] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.Io.CachingFileStorage.TryUpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00000] in <d9555282dea14061ab4400355adad9e4>:0

**Comment by Karreg** [comment] 2019-09-08 10:50
OK, that's more clear indeed ;)
Seems legit to me...

**Comment by PhilippC** [comment] 2019-09-14 05:32
closing this as duplicate of https://github.com/PhilippC/keepass2android/issues/374
Please note that you can manually switch to "working with internal cache" before you make file operations to workaround this.

**Closed by PhilippC** 2019-09-14 05:32 UTC
