### ISSUE TITLE
Keepass2android trauncates password entries 

### ISSUE THREAD

**Issue by indkal** [PhilippC/keepass2android#244] opened 2018-02-07 03:59 UTC
I am using Keepass2android on Samsung Galaxy 7. I noticed that some of my password entries get truncated on the right. Since there is no landscape mode for viewing it, is there some way to see the entire password entry? Thanks.

**Comment by PhilippC** [comment] 2018-02-08 08:12
duplicate of #230

**Closed by PhilippC** 2018-02-08 08:12 UTC
