### ISSUE TITLE
KP2A Key Does not have fields in it

### ISSUE THREAD

**Issue by stewart-anderson** [PhilippC/keepass2android#1308] opened 2020-07-04 22:37 UTC
Just switched to a new phone and I find that when I have selected an entry from the DB and clicked the KP2A small padlock the dialogue only has select new entry and the URL selector in it, where it used to have  a Los tofball the fields with the "select..." At the bottom of the list.

I don't recall seeing this before.

Cheers
Stu

**Comment by stewart-anderson** [comment] 2020-07-04 22:38
Sorry, should have said, be phone is a OnePlus 8 Pro.

**Comment by PhilippC** [comment] 2020-07-06 07:08
duplicate of https://github.com/PhilippC/keepass2android/issues/695

**Closed by PhilippC** 2020-07-06 07:08 UTC
