### ISSUE TITLE
Keepass2android does not work with nginx-1.13.6

### ISSUE THREAD

**Issue by satarsa** [PhilippC/keepass2android#80] opened 2017-10-28 20:34 UTC
Hi
I use keepass2android synchronized with a nextcloud through webdav (https and http/2). Apparently, upgrade to nginx-1.13.6 breaks synchronization: k2a says that it cannot get header :status. Downgrade to nginx-1.13.5 resolves the issue.
Thanks

**Comment by PhilippC** [comment] 2017-10-29 05:20
duplicate of #44

**Closed by PhilippC** 2017-10-29 05:20 UTC
