### ISSUE TITLE
[feat] Download icon from website

### ISSUE THREAD

**Issue by aetonsi** [PhilippC/keepass2android#2177] opened 2023-01-04 16:55 UTC
Hello,
just like [keepassxc](https://keepassxc.org/), it would be cool to be able to fetch the favicon from the remote URL (or additional URLs, as fallback). This would also mean resizing it and embedding it into the keepass database, from my understanding.
At the moment i can recognize the entries created on Android just by the fact that they have no icon...

---

Have a nice day

**Comment by NumbGnat** [comment] 2023-04-16 17:43
I just use the feature in KeePassXC every once in a while and let it update all entries. Everything shows up in KeePass2Android, if you're syncing the database between them.

**Comment by aetonsi** [comment] 2023-04-17 08:08
Yes i do that too, for now. It would be nice not having to rely on external software for this small thing (if it's not too difficult to implement ofc).

**Comment by PhilippC** [comment] 2023-04-21 02:51
closing of duplicate of #68

**Closed by PhilippC** 2023-04-21 02:51 UTC
