### ISSUE TITLE
SFTP Access using Private Key

### ISSUE THREAD

**Issue by hammi1** [PhilippC/keepass2android#273] opened 2018-02-25 15:20 UTC
Hello, I like the SFTP option for the databases to sync with my desktop, but to access it over SSH I use a private/public keypair. I have the private keyfile on my android device on /sdcard/ (so its possible to access it) but there is no option to authenticate to SSH using the key file.

My workaround; I use ES File Explorer and saved my server on there, ES supports private key authentication, and I accessed ES from within Keepass2Android and retrieved my database. However there is no option to synchronise the database with this workaround.

Could you please implement private key authentication to SSH servers for the SFTP option so that synchronisation of the database is possible?

Thank you.

**Comment by PhilippC** [comment] 2018-02-26 08:27
duplicate of #69

**Closed by PhilippC** 2018-02-26 08:27 UTC
