### ISSUE TITLE
[Feature Request] Add support for associating multiple logins for an app with autofill framework

### ISSUE THREAD

**Issue by ceribik** [PhilippC/keepass2android#254] opened 2018-02-12 10:03 UTC
It would be nice if it was possible to associate a second login with a given app for use with the Autofill framework.

Currently, the only way to do so is to manually add the required k2pa field for a 2nd, 3rd, etc login for the same site/app.

**Comment by NumbGnat** [comment] 2018-03-30 23:21
Agreed. I have this problem a lot.

Once I manually copy the search string to the other entries, I am prompted which account I want to use.

There is an option in KeePass2 that says, "always prompt". I use that just to make sure the correct entry is auto matched.

KP2A could implement the same option so when an entry is auto matched, it prompts even if there is only one matching entry. Providing the "search for another" option and then asking whether to save the app search string again, just like a search when no entries match. 

I think that would be a fairly simple implementation, as all functionality already exists. Just one added setting that causes a prompt to select an entry when there's one or more matches instead of 2 or more.

**Comment by PhilippC** [comment] 2018-09-17 09:06
duplicate of #544 (or vice versa)

**Closed by PhilippC** 2018-09-17 09:06 UTC
