### ISSUE TITLE
Add support for OneDrive for Business

### ISSUE THREAD

**Issue by carpac** [PhilippC/keepass2android#55] opened 2017-10-17 14:56 UTC
When I try to open a database that is stored on *OneDrive for Business*, I always get a "password is wrong" error (although I am pretty sure that I typed in the correct password). Does *Keepass2Android* work with *OneDrive for Business*, too, or only with *OneDrive* (the "consumer" version)?

**Comment by PhilippC** [comment] 2017-10-20 04:11
OneDrive for Business is currently not supported. As far as I understand I need a MS subscription account just for including this feature.

**Comment by carpac** [comment] 2017-10-25 13:20
I don't know if you need a MS subscription account. On my Windows pc I am using KeePass with the plugin "KeePass OneDrive Sync" (see https://github.com/KoenZomers/KeePassOneDriveSync). Maybe you could ask the author of this plugin, Koen Zomers, what is needed to support OneDrive for Business.

**Comment by tswierkot** [comment] 2018-02-27 15:57
Bump. Any news on this front?

**Comment by kribjo** [comment] 2018-03-02 10:19
I am also very interested in this. As carpac commented it is working with that plugin. I guess it is because its developer has the needed MS developer account.

I would be interested in sponsoring an account for the developer of this app. Which account would be needed (individual/company) and how much would it be (region dependent, see link below)? Is that an option?

https://docs.microsoft.com/sv-se/windows/uwp/publish/account-types-locations-and-fees

**Comment by kribjo** [comment] 2018-03-02 11:11
Here is some further information, seems the client secret can be created without expiration.
https://github.com/KoenZomers/KeePassOneDriveSync/issues/51

**Comment by mainlt** [comment] 2018-05-18 12:32
Bump. I'm also very interested :)

**Comment by Wiredframe** [comment] 2018-06-16 21:12
I'd really like to kindly ask you if you could add OneDrive for Business support. I didn't even notice that these are two different things and I've been trying to login but always failed.

Thanks in advance!

**Comment by legolasdimir** [comment] 2018-06-18 14:35
I would also very much be interested in this feature.

**Comment by PhilippC** [comment] 2018-08-13 19:30
please use the thumbs-up reaction on the issue itself. I occasionally sort issues for this reaction when I try to decide which features will be included for the next release.

**Comment by Calico90** [comment] 2018-08-14 13:00
This option would be great! :)

**Comment by KallistiMan** [comment] 2018-11-18 13:30
Not sure what was in the deleted comments, but I was wondering if there is anything in addition to using the thumbs-up to help make this feature happen?

**Comment by pstorch** [comment] 2018-12-08 13:34
I'm also interested in this feature. 

It looks like OneDrive for business needs a different authentication mechanism:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth?view=odsp-graph-online

And the developer needs an Office 365 subscription: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration-server?view=odsp-graph-online

A developer subscription would cost 99$ per year :cry:

**Comment by jpdied** [comment] 2018-12-09 22:34
I would be willing to donate the sub fee for this feature. I'm sure there might be a few who would also chip in for a developer o365 sub.

**Comment by PhilippC** [comment] 2018-12-29 16:00
I have purchased a Developer subscription and re-implemented OneDrive access using the new MS Graph SDK. It seems to be working for personal accounts but I can't access my OneDrive for business account, so for now that's no improvement...
@kribjo I am not sure if something is wrong with my account so if you have the possibility to create another account for me for testing just for a month, I'd be really grateful. Any subscription which comes with OneDrive for business access would be fine.

**Comment by PhilippC** [comment] 2018-12-30 06:47
@kribjo please ignore my request, I think the error is more related to my app configuration than to the account.

**Comment by michielhageman** [comment] 2019-01-08 07:35
Hi Philipp, 
Just installed your app, also try to connect to the .kdbx on my Onedrive for Business. Do you think you will be able to add the above mentioned support for it? Would be great!
Regards,
Michiel

**Comment by PhilippC** [comment] 2019-01-13 19:34
@michielhageman  as you may read in the posts above yours - I am trying to do so but wasn't successful so far yet.

**Comment by MarkJenniskens** [comment] 2019-01-14 07:48
@philippC thanks for your effort. This feature would be great. Currently rolled out KeePass in our company, so O4B support would be much appreciated. If you need anything let me know.

**Comment by mplogas** [comment] 2019-02-12 10:25
>It seems to be working for personal accounts but I can't access my OneDrive for business account, so for now that's no improvement...

@PhilippC So this is either an issue in your app registration (in the Microsoft App Registration Portal) or you're not using the ADALv2 authentication endpoint. I would assume it's the latter, as you're still using MS-ADAL 1.14. Have you tried the "MSA Auth For Android Adapter" with the Graph SDK already?

**Comment by PhilippC** [comment] 2019-02-17 07:33
@mplogas thanks a lot for taking a look! I am close to giving up on this, but it would be awesome if we could solve this issue and I really appreciate any help. 
I am not exactly sure if I understand what you mean. Please note that I currently have two OneDrive implementations in the repo (my plan was to keep the old implementation so users which are currently using OneDrive can continue and don't have to re-login or anything, but use the new implementation for new connections).
The new implementation can be found on https://github.com/PhilippC/keepass2android/blob/master/src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/OneDriveStorage2.java.
It uses the PublicClientApplication class and I don't think this is still using the ADAL 1.14, right?
I rather have the feeling that it might be an issue with my app registration, I don't even know if the Office 365 Enterprise E3 Developer subscription which I have purchased for this is what I need (I received a "free credit has expired" mail from Microsoft some days after setting everyithng up). 
If you think my implementation is ok, what should I provide so you can take a look at the app registration? 
Again, thanks a lot for any help!

**Comment by mhors** [comment] 2019-05-25 06:28
I have a slightly different experience. Not "password is wrong" but when I try to open OneDrive for Business with an account name of x@y.onmicrosoft.com, I get "that Microsoft account does not exist" even though I can open this account on OneDrive for Android. This onmicrosoft.com domain is used when you don't want to associate your own domain with the OneDrive account.

**Comment by J-O-P** [comment] 2019-05-26 08:33
I also need this feature, as I am moving all my data from "OneDrive Personal" to "OneDrive for Business". As in the previous post: When I enter the UserID of my "OneDrive for Business" account I get the error  "Account does not exist" in KeePass4Android (Apparently it only finds OneDrive Personal accounts). A short search brought me here to this topic to find out OneDrive for Business is not supported yet.  Let me know if there is anything I can help with.

**Comment by Edouard37** [comment] 2019-06-26 11:09
Hello Philipc, how can i help you ? i have ent account on OneDrive for business.
Thank you. I test OneDrive with a pesonnal account : work great ! But i want now to deploy over 3000 users… :-)

**Comment by qj0n** [comment] 2019-06-27 14:58
Hi @PhilippC 
If you need an enterprise account with OneDrive and some other licenses I can provide you with a few for free. 
Thanks for all the work ;)

**Comment by ethzero** [comment] 2019-07-29 22:54
+1, regarding the:  "OneDrive for Business" account I get the error "Account does not exist" in KeePass4Android.

**Comment by paololec** [comment] 2019-08-01 16:01
Also I like this features

**Comment by vepman** [comment] 2019-08-05 08:47
I need this feature also

**Comment by MPNeosociety** [comment] 2019-08-29 08:20
I use this app now - for sure with some good new features. Anyway: It's not working with OneDrive for Business via the menu. I tried also using OAuth via Github but you can not add OneDrive for Business because it's not possible with work or school accounts (you get that information when you try). I think that is the problem: It's not allowed from Microsoft to authorise other Apps to access OneDrive for Business via OAuth and that's why you can't use KeePass2Android for that. I used before the KeePass2Android Offline Version and this simple works if you go to the database file in your OneDrive App and then open it with the Offline Version. If you then Open the Offline Version it automatically tries to open the database file, so you don't have to go again through the OneDrive App. THIS WORKS ALSO for the new KeePass2Android Version! So you just have to select it and then you're fine. So from my side: Problem solved in that way.

**Comment by pstorch** [comment] 2019-08-29 17:09
@MPNeosociety I tried it. Opening is possible, but when I change something KeePaas2Android can't save it.

**Comment by vepman** [comment] 2019-08-29 21:16
>  It's not allowed from Microsoft to authorise other Apps to access OneDrive for Business via OAuth and that's why you can't use KeePass2Android for that. 

No, other Apps can use Onedrive for Business via OAuth. For example, X-plore for Android works.

**Comment by PhilippC** [comment] 2019-08-30 05:15
note for myself: it looks like https://github.com/microsoftgraph/android-java-snippets-rest-sample has an up-to-date documentation on how to implement this. Will try when I'm back from my current travel.

**Comment by vepman** [comment] 2019-08-30 16:21
Great, wish you a good journey.

**Comment by PhilippC** [comment] 2019-09-01 07:49
I couldn't wait and installed Android Studio on a laptop I have with me. After a while I was able to find the required changes to my previous code to get this working! Finally!
(At least on the Java side. Integration into the main app is still pending and has to wait until I return home in a week.)

One thing that I would like to test/implement is working with shared files (because this currently is not working):

Can anybody share a file or folder with me for testing? I'd prefer a simple text file plus a kdbx file  for testing (with master password "test").
My Office365 account is PhilippC@crocoapps.onmicrosoft.com. 

Would be great if someone could share a txt+kdbx file also with a "personal" OneDrive account (not OneDrive for business) with my personal OneDrive account: philipp.crocoll@web.de 
because I'm using the same implementation for both and would like to test both.

Thanks in advance!

**Comment by pstorch** [comment] 2019-09-01 09:13
@PhilippC I've sent you an invite to a shared folder.

**Comment by PhilippC** [comment] 2019-09-01 10:52
@pstorch thanks! Unfortunately it looks like I can access the files through the browser, but I don't see them as "Shared with me" (if I click Share on the files and type my email address, it says your organization doesn't allow sharing with me). I'm not experienced with this, but it looks like there are different ways to share. I would need to see the folder in "Shared with me" to try to access it from Keepass2Android.

**Comment by pstorch** [comment] 2019-09-01 11:13
I don't have other share options. I could share the individual files as well, but I guess this is not what we would like to test.
Do you have to include the shared folder into your personal library?

**Comment by PhilippC** [comment] 2019-09-01 14:20
@qj0n as I have now a first implementation of this, I would like to do some testing with using files from different accounts. I only have one, so another O365 account would be great. Can you send credentials to crocoapps@gmail.com

**Comment by paololec** [comment] 2019-09-02 06:52
I shared a folder with you PhilippC with OneDrive for business

**Comment by Mr-Pingu** [comment] 2019-09-03 08:22
@PhilippC if  still needed I can supply you a shared folder, both onedrive business & personal. Let me know. Really waiting for oneDrive business support :)

**Comment by PhilippC** [comment] 2019-09-03 08:30
it looks like @paololec and @pstorch have shared the folder using the "Share" button and then directly inputting my email, but this didn't work as I couldn't import the folder to my OneDrive. Maybe someone (e.g. @Mr-Pingu ) can try to click "Share" and then "Manage access", then under "Grant access" type my mail?

**Comment by paololec** [comment] 2019-09-03 08:43
@PhilippC I have also give you grant access.

**Comment by Edouard37** [comment] 2019-09-03 09:03
Hello,
Shared to crocoapps@gmail.com<mailto:crocoapps@gmail.com> and PhilippC@crocoapps.onmicrosoft.com<mailto:PhilippC@crocoapps.onmicrosoft.com>
You have right to modify folder.


De : PhilippC <notifications@github.com>
Envoyé : dimanche 1 septembre 2019 16:21
À : PhilippC/keepass2android <keepass2android@noreply.github.com>
Cc : DENIZE, Edouard (COLAS DIGITAL SOLUTIONS) <edouard.denize@colasds.com>; Comment <comment@noreply.github.com>
Objet : Re: [PhilippC/keepass2android] Add support for OneDrive for Business (#55)

Message sent from Internet with noreply@github.com<mailto:noreply@github.com> email address
Security warning : Do not click on the links or attachments contained in this message unless you are sure of the sender’s address.
________________________________

@qj0n<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqj0n&data=02%7C01%7Cedouard.denize%40colasds.com%7C14117990181d4c4508cf08d72ee79504%7Cbe0be093a2ad444c93d95626e83beefc%7C1%7C0%7C637029444501966557&sdata=djNyabqrwBUhTFmadQzaLJBYuWNd9OmDUPFj2OrJ9OM%3D&reserved=0> as I have now a first implementation of this, I would like to do some testing with using files from different accounts. I only have one, so another O365 account would be great. Can you send credentials to crocoapps@gmail.com<mailto:crocoapps@gmail.com>

**Comment by PhilippC** [comment] 2019-09-03 09:33
either I am doing something wrong or this does not work across domains or between your type of business accounts and my E3 developer account. Anybody with access to more than one account to test sharing internally first?

**Comment by paololec** [comment] 2019-09-03 09:46
@PhilippC if you have E3 developer Subscription you have 25 account with license, you can add an account in admin.microsoft.com -> active users -> add user

**Comment by PhilippC** [comment] 2019-09-03 10:10
unfortunately I have just one, but I talked to MS support and they told me how I can activate test licences.
BTW they also confirmed that sharing is not possible across different domains.

**Comment by Mr-Pingu** [comment] 2019-09-04 09:15
@PhilippC I could test here with two accounts within the same domain. Do you have sort an APK i could install and test?

 Another option would be to give you short-term access to our domain.

**Comment by PhilippC** [comment] 2019-09-04 16:14
thanks for the offer, @Mr-Pingu . But I think I will first try to work wtih the test licenses!

**Comment by PhilippC** [comment] 2019-10-04 19:10
I finally made it. Thanks for the patience, everyone :-)

Here it is:
Version 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android) has support for OneDrive for Business, but also for shared files, app folder access, multiple accounts etc.

Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file. 

Let me know if you have any trouble.

**Closed by PhilippC** 2019-10-04 19:10 UTC
Labels: enhancement

**Comment by Edouard37** [comment] 2019-10-04 19:53
Congratulations!

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by michielhageman** [comment] 2019-10-04 20:00
Great work Philipp!


Regards,
Michiel

________________________________
Van: PhilippC <notifications@github.com>
verzonden: vrijdag 4 oktober 2019 21:10
Aan: PhilippC/keepass2android
Cc: Michiel Hageman | Mhitz; Mention
Onderwerp: Re: [PhilippC/keepass2android] Add support for OneDrive for Business (#55)


I finally made it. Thanks for the patience, everyone :-)

Here it is:
Version 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android) has support for OneDrive for Business, but also for shared files, app folder access, multiple accounts etc.

Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file.

Let me know if you have any trouble.

**Comment by pstorch** [comment] 2019-10-04 20:02
Maybe I'm doing something wrong: I don't have "Open database", but "Open file...". When I choose OneDrive there I can enter my company email, but OneDrive says "That Microsoft account doesn't exist". :thinking:

**Comment by PhilippC** [comment] 2019-10-04 20:06
You're right, it's called "Open file". If you click OneDrive, do you see the dialog to choose the variant (All files, shared files, app folder)? If not, you're probably running the old version? You can also check in app settings / about?

**Comment by pstorch** [comment] 2019-10-04 20:15
Ah, sorry, after changing from release to the test channel I got an update on Version 1.07b-pre1 not pre2. I've now checked again and got pre2.
It's working. :tada:  Thanks :+1:
