### ISSUE TITLE
"Do not show again" does not work with AutoOpen databases

### ISSUE THREAD

**Issue by Karreg** [PhilippC/keepass2android#751] opened 2019-03-18 10:50 UTC
When multiple databases are defined with KeeAutoExec, there's a popup proposing to configure the child databases, with a `Do not show again` button. This button does nothing, the popup stays. Always.

The problem is that child databases targeting Google Drive make Keepass2Android crash, so using child database is not an option to get rid of this message... 😢 

Version 1.07-pre6 on Android Pie (OnePlus 6T)

**Comment by PhilippC** [comment] 2019-03-18 11:08
I also found this immediately after releasing 1.07-pre6, will be fixed in the pre7. However, I cannot reproduce the issue you have with GDrive child databases.

**Comment by Karreg** [comment] 2019-03-18 11:45
I guess it depends how they are defined. Do you define a database relative to the master database? On my side, I define a full path database, for multiple reasons:

- It's compatible with KeeAnywhere in Keepass2. Using relative path does not work.
- I would like to be able to use a database defined in another account (like we discussed in the dedicated thread)

format for URL is: gdrive:///<ACCOUNT>/<PATH>/<FILE.kdbx>

**Comment by Karreg** [comment] 2019-03-18 11:54
More information on my setup (if it can help understand why it does not work):

Password: `<DB password>`
URL: `gdrive:///<ACCOUNT>/<PATH>/<FILE.kdbx>`
IocUserName: `Anonymous`
IocPassword: `Anonymous`

The last two values are to avoid GDrive login each time the child database is opened. But the issue occurs both with or without them...

**Comment by Karreg** [comment] 2019-03-18 12:23
OK, I came across your discussion with Dominik. I set up two entries, one with KeeAnywhere format with a DeviceID being my pro desktop, and one using KP2A format (from KP2A), with the Android Device ID... Nice integration you did there 👍

**Closed** 2019-03-20 03:28 UTC
