### ISSUE TITLE
Issue with viewing longer passwords 

### ISSUE THREAD

**Issue by maxlandry** [PhilippC/keepass2android#104] opened 2017-11-09 20:05 UTC
I've encountered a little bug with longer passwords. 

When we hit the button to show them, they don't display completely and it isn't possible to scroll to see more of it. I need to edit the entry and then scroll in the field to see it. 

Is this normal or is there a solution I haven't found? 

![screenshot_20171109-150122](https://user-images.githubusercontent.com/19274247/32627007-05e611f4-c55f-11e7-9191-3f3e3f447549.png)

**Comment by PhilippC** [comment] 2017-11-13 05:59
duplicate of #96

**Closed by PhilippC** 2017-11-13 05:59 UTC
