### ISSUE TITLE
generate passphrases

### ISSUE THREAD

**Issue by illionas** [PhilippC/keepass2android#407] opened 2018-06-12 19:38 UTC
Let me cite a classic comic from xkcd (probably many of you already know):

"Correct horse battery staple"

https://www.xkcd.com/936/

Passphrases have many advantages:
- they are longer, thus brute force attacks unaware of passphrases take a lot longer
- random words are easier to remember than random letters or numbers
- one word contains more entropy than one letter

(I think it's a good idea to combine them with some short uppercase+number+special sign combination to appease some services that require to have them: e.g. "6*W outdoor flew content picks".)

Generating passphrases shouldn't be too difficult. The more difficult question would be what dictionary to take:

I think it would be a good idea to use a database entry with a special name (like "passphrase dictionary"). There you could put one or more dictionaries as txt file attachments. Every line is a word. Generate a number between 1 and the number of lines in the file to pick a word.

Everybody could use different dictionaries according to language etc. There's the original diceware dictionary, there's the EFF dictionary, also a version with shorter words for quicker typing. There are translations for many languages.

You could even just put all the symbols to choose from in such file. Hate that l and I look similar in your passwords? Remove them from your preset file.

**Comment by illionas** [comment] 2018-06-12 19:40
http://www.useapassphrase.com/

https://www.rempe.us/diceware/#eff

www.diceware.com

**Comment by illionas** [comment] 2018-06-12 19:42
https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

**Comment by levinus** [comment] 2018-06-12 20:32
This makes sense if you have to remember the password you want to generate (e.g. your master password). If I understood you correctly you want to apply this generator template to all password entries. 
But that is why you have a password manager: You dont have to remember the different passwords and can just copy them. The xkdc comic mentions passwords you put together yourself. **Thats not random and thats why they are not safe.**  Keepass generates real random passwords with even higher entropies (if they are long enough) than passwords from diceware.

**Comment by illionas** [comment] 2018-06-13 10:13
You are partially right.

The biggest advantages are indeed for passwords that need to be remembered.

However there are still enough advantages even for passwords you just copy and paste in my opinion.

For example, i use a passphrase for my wifi router. Usually I log on a device maybe once a year. I could easily look it up in my database. However, I would have to type a bunch of random letters, some not always welcome to find or type on a ,(soft) keyboard.

The random letters are so meaningless, that you easily get lost even during typing.


Of course I am talking about randomly generated passphrases. I am aware that the human mind is not suitable to make up a random enough password. However, the human mind can more easily grab words than letters. Concerning password strength you just have to treat words like letters from a big alphabet (i.e. the size of the dictionary). The biggest difference is that they are longer, of course.

"prompter agreement overarch thirsting wispy reheat" contains 77.55 bit of entropy according to dempe.us (mentioned before)

"NEl^[%ZIfKAd" contains 78 bits (generated at https://ae7.st/g/ )

If you just copy and paste them, then there's no reason to prefer either method. Still, I guess you would type the former a lot quicker; someone could easily tell it to you over a phone line. You would soon start to remember it if you typed it several times.

The only reason for random symbols would be a character limit: if a website says "your password just be 6-10 letters long", then symbols are the better choice.

**Comment by illionas** [comment] 2018-06-13 10:19
what I am suggesting is that in addition to the selectable "letters, numbers, symbols, brackets" in the password generation dialog, there'd be a "words from passphrase dictionary" option.

Maybe a entropy measurement should be added too.

**Comment by Karreg** [comment] 2018-06-13 12:21
> The random letters are so meaningless, that you easily get lost even during typing.

True, I was wondering what could be a real use case, and you found one. I am skeptical about the other use cases as they aren't really bringing anything a randomly generated password can't. The only one that made sense to me was for passwords that must be remembered (for opening keepass DB I guess, everyone is using this kind of password, right ? Right ?)

However, if you want to have a strong WiFi key, you will need a long list of words. So instead of let's say 24 characters, you will have 10-15 words. You replace the difficult characters by far more simple characters.

I don't really care about this feature, but the discussion is really interesting :)

If it is to be developped, I would suggest to make it a plugin so it won't increase the size of the app...

**Comment by rwuwon** [comment] 2018-06-18 22:07
For what it's worth, Diceware.com's FAQ recommends sticking to lower case.

**Comment by nullsarebad** [comment] 2018-07-11 07:21
Another issue requesting the same thing: https://github.com/PhilippC/keepass2android/issues/284

**Comment by James-Firth** [comment] 2018-07-11 18:31
My use case is for generating a passphrase that I can view on my phone and will be easy to type on a computer (friend's, work laptop, etc) that I don't have keepass installed on/can't install it on.

**Comment by PhilippC** [comment] 2018-07-11 18:46
duplicate of #284

**Closed by PhilippC** 2018-07-11 18:46 UTC
