### ISSUE TITLE
Can't open database a 2nd time: KeeChallenge + Yubikey

### ISSUE THREAD

**Issue by ERFM** [PhilippC/keepass2android#583] opened 2018-10-07 07:47 UTC
I can open the database one time only on my phone using Keepass2Android.  If I close it and reopen it I'll get an error message and can't reopen it until I recopy the xml file used in challenge-response over from my PC to the phone.

Keepass2Android 1.06f on Nexus 6P Android 8.1.0
KeeChallenge 1.5 with Yubikey Neo and new Yubikey 5 NFC
KeePass 2.40 on Windows 10

1) Copy database and xml file to phone.  Set to Password + Challenge-Response.  click "LOAD OTP AUXILIARY FILE..." -> click "system file picker" select xml file, then type password and open database.  Yay!

2)  Close database.

3)  Can't reopen database. When I click "LOAD OTP AUXILIARY FILE..." -> click "system file picker" select xml file, I get the following error message:
"Could not load auxiliary challenge file! Please use KeeChallenge plugin in KeePass2.x (PC) to configure your database for use with challenge-repsonse"

4) Have to copy xml file from PC to the phone each time I want to select the xml file from the LOAD OTP button.

I used this setup for months on my old Android 4 phone several years ago without any problems before that old yubichallenge plugin stopped working on newer android versions.  Not sure what's causing the xml file to stop working after one use.

**Comment by hermannx** [comment] 2019-12-11 12:38
I have the same problem with the following setup:
Keepass2Android Offline 1.07b-r0 on Mi9 Android 10
KeeChallenge 1.5 with Yubikey 5 NFC

Is this a bug of K2A? 
Is there maybe a beta version of K2A Offline which solves this problem?
I registered yesterday for K2A Offline beta program but didn't see any updated versions yet.
Thanks!

**Comment by hermannx** [comment] 2019-12-16 08:40
Here's a workaround:
The problem is that KP2A  is not able to re-read the XML-file it has created itself, whereas KP2A can read the XML-files created by a PC without a problem.
Therefore I had a look at the XML files and found that the files K2A cannot read have an additional "</data>" line at the end. After deleting the duplicate line with the text "</data>" everything worked fine.
And what is funny: After doing this once, KP2A from the on created the XML-file correctly, without the duplicate last line :)

**Comment by Frazzle1** [comment] 2019-12-18 08:32
Thanks you so very much hermannx, your work around worked perfectly for me. After removing the second <data> entry in the .xml file my database would open every time with no errors. One other thing I had to do however was change the database name to something KP2A had not seen before. Removing the old database in the app itself did not seem to fix this and this was evident because KP2A would never ask me for the location of the .xml file when I tried to reinstall the database using the same name again. It would just reproduce the same old error I had before when trying to open the database. I tried resetting restarting the phone but this didn't help. It's not a big deal using a new name for my database however. I'm just so happy it works without giving me any error messages anymore! Now I have the .xml file on my phone rather than in the cloud somewhere. It was a very strange bug indeed and maybe PhilippC will be able to fix it now that he knows how it works. Great job in figuring out that work around though!! Many Thanks hermannx!

**Comment by Lucky225** [comment] 2019-12-31 21:59
Just chiming in with a 'me too', and this goes not only for challenge-response but also for OATH-HOTP OTP which I was originally testing, pulled my hair out, tried yubichallenge instead just to run into the same issue. Had me pretty sad cus I bought the NFC yubikey pretty much for this purpose of adding 2FA to my keepass file that I store on the phone.

**Comment by thn80** [comment] 2020-01-03 16:07
I'm facing exactly the same issue.
Will there be a fix soon?

**Comment by shadeIess** [comment] 2020-01-05 12:41
I'm having the same issue.

Removing the additional </data> tag at the end of the auxillary .xml file allows me to do challenge-response again.

_However_ if I open the DB in Keepass for Windows and sync it back to android, I can only open the DB once in keepass2android before the second </data> tag is written again.

So it looks like the first time you open the db in keepass2android, it writes the unnessesary </data> but not in subsequent openings?

@PhilippC can you please look into this? I'm happy to provide more info or sample .xml files if you need them

**Comment by PhilippC** [comment] 2020-01-06 11:07
I cannot reproduce this. Tested on a Google Pixel with Android 10, with kdbx/xml files on Dropbox as well as on local storage. Can you check if using another storage type changes the behavior?

**Comment by thn80** [comment] 2020-01-06 15:31
> 
> 
> I cannot reproduce this. Tested on a Google Pixel with Android 10, with kdbx/xml files on Dropbox as well as on local storage. Can you check if using another storage type changes the behavior?

I have the files located inside the internal memory of a Samsung Galaxy S10 with Android 10.
The folder with the Keepass files is synchronized via Syncthing (not Dropbox) with my Windows machine.
If the problem occurs, the XML file looks like this (additional `</data>` tag at the end):

`<?xml version="1.0" encoding="utf-8"?>
<data>
	<aes>
		<encrypted>*****</encrypted>
		<iv>*****</iv>
	</aes>
	<challenge>*****</challenge>
	<verification>*****</verification>
	<lt64>False</lt64>
</data>
</data>`

I highly assume that this is a Keepass issue, because only Keepass on my Android phone adds this additional tag.

**Comment by Lucky225** [comment] 2020-01-06 16:11
What steps did you try to reproduce @PhilippC? I'm on a Pixel 3a, Android 10, it does work the FIRST time you open the database. It's once you close the database that keepass writes the additional </data> tag at the end of the xml file, and upon attempting to re-open the database a second time is when it fails. This fails both with keechallenge and OATH-HOTP OTP, presumably because the app writes a </data> to either type of file.

**Comment by PhilippC** [comment] 2020-01-06 19:30
My XML file has exactly the structure as described by @thn80 and I tried to open twice, using keechallenge. I see that the xml file contents (i.e. challenge) change when loading the database.

**Comment by shadeIess** [comment] 2020-01-06 20:03
@PhilippC did you try switching between keepass2android and keepass for windows? thats what screws up my .xml file.

Steps to reproduce the issue for me were:
-create a new database in keepass for windows and enable keechallenge
-sync the .kdbx and .xml to your phone (used syncthing as well as copying it directly via usb)
-open the db in keepass2android for the first time -> opens without a problem
-make some changes in the db on android (add new entry or whatever)
-close/lock the db on android
-try to open it again -> doesn't work, additional `</data>` has been added
-remove additianl `</data>` from the xml -> file can be opened again on android
-sync back to windows and open it -> also works
-sync back to android -> opens the first time, but not the second time
-and so on

Im also using a Galaxy S10 and Android 10

**Comment by Lucky225** [comment] 2020-01-06 23:00
> @PhilippC did you try switching between keepass2android and keepass for windows? thats what screws up my .xml file.
> 
> Steps to reproduce the issue for me were:
> -create a new database in keepass for windows and enable keechallenge
> -sync the .kdbx and .xml to your phone (used syncthing as well as copying it directly via usb)
> -open the db in keepass2android for the first time -> opens without a problem
> -make some changes in the db on android (add new entry or whatever)
> -close/lock the db on android
> -try to open it again -> doesn't work, additional `</data>` has been added
> -remove additianl `</data>` from the xml -> file can be opened again on android
> -sync back to windows and open it -> also works
> -sync back to android -> opens the first time, but not the second time
> -and so on
> 
> Im also using a Galaxy S10 and Android 10

Ah yes, I did neglect to state the DB is originally made on a different keepass (also windows in my case) before transferring it to android, where keepass2android then adds the additional `</data>`. I suppose making the db on keepass2android to begin with may in fact work fine.

**Comment by Frazzle1** [comment] 2020-01-06 23:07
I'm not having the same problem shadeless describes after I remove the additional </data> when moving the database .kdbx  between my windows 10 machine and my Pixel 3 smartphone. I always transfer the data file from my windows machine manually to my phone after making any changes to the database. I never make changes to the data base on the phone, then move it to the Windows computer then back again however. Also I never move the .xml file off the phone after I correct the additional data anomaly. There is no need to move the .xml file as it is not constantly being modified when you change the database. Not sure if shadeless is moving both these files on and off the phone but it sounds like this may be what he's doing??? The only difference I can see when loading a new database for the very first time compared to successive loadings is that the first time the program askes you to tell it the location of the .kdbx and .xml files on your phone. Perhaps it is this subroutine that creates the corruption? On successive loads it remembers where these files are and no further corruption occurs. The corruption only occurs when the files are stored on the phone however and not in the cloud which is interesting. If anyone is having trouble recreating this bug I would suggest changing the name of both files to something KP2A has never seen before. It seems even when you remove a previous database name in KP2A it still remembers it's old location when you try and reinstall it again and doesn't prompt you for the location. Hense you may not be able to recreate the error. When I first upgraded from my Nexus phone to my pixel 3 phone I told setup to import all my programs and settings. KP2A worked perfectly on my new Pixel 3 and I was totally unaware of this error. It was only after I reset my phone and reinstalled manually all my programs and KP2A databases that the error appeared. I think the reason it worked perfectly in the first case was because it knew where the database was from the imported settings and never prompted me to locate it. I'm only guessing but I think someone should take a closer look at what's happening to this .xml file during the location routine?

**Comment by thn80** [comment] 2020-01-07 17:57
As reference you can find some hex dumps of the correct and damaged files attached.

And just another idea: During christmas time my Galaxy S10 installed the latest Android 10 update and I have a bit the feeling, that the problem started right after. Could someone confirm this guess? Is Keepass using some Android libraries which could have been affected by this update?

![Diff_1](https://user-images.githubusercontent.com/2078784/71917047-80d0da00-317f-11ea-8b68-bab5fa047400.jpg)
![Diff_2](https://user-images.githubusercontent.com/2078784/71917048-80d0da00-317f-11ea-8861-e790901708a2.jpg)

**Comment by PhilippC** [comment] 2020-01-08 06:06
I still cannot reproduce, but in @Lucky225 's description I am suprised to see that you need to make a change to the database. Could you please watch the xml file and see whether it is corrupted after opening the database or after modifying it?
On my Android and using Keepass2 on Windows, the .xml file is not touched when saving the database, only when opening.

**Comment by hermannx** [comment] 2020-01-08 10:04
First of all, to answer Philips question, I saw a modification of the xml file directly after opening the database. No change to the db necessary.

However, I found something else:
The xml file generated by the PC is always 394 bytes. Whenever I load this into KP2A, it gets corrupted by the duplicate tag, even though the file length is the same.
When I delete the additional "data" tag, I get a file of 387 bytes, which from then on works fine with KP2A.

This seems to be the problem: 
The PC-generated file has ASCII 0x0D + 0x0A for a new line, i.e. Line Feed + Carriage Return. The file that KP2A generates has only 0x0A :)
So it looks like KP2A overwrites the xml generated by the PC, using 0xA instead of 0x0D + 0x0A for each new line. Therefore the text overwritten by KP2A is shorter than the original text, leaving the additional "data" tag in the end.

**Comment by thn80** [comment] 2020-01-08 16:02
> Therefore the text overwritten by KP2A is shorter than the original text, leaving the additional "data" tag in the end.

I think @hermannx got exactly the point. After his comment I modified the xml file with Notepad++ and added some additional line breaks as you can see in the attached image on the left INPUT.

When opening the database in KP2A (without doing any modifications or storing the database), KP2A overwrites the xml with the OUTPUT shown on the right side inside the image.

My result exactly shows what @hermannx described. You can clearly see, that KP2A writes the output xml until the closing `</data>` tag in line 10 of my screenshot. Everything else, which is located after this closing data tag, is the original data from the INPUT xml file and untouched by KP2A.

![Diff_3](https://user-images.githubusercontent.com/2078784/71993938-352e3700-3238-11ea-969c-11e941d1a44b.jpg)

**Closed** 2020-01-08 20:22 UTC

**Comment by PhilippC** [comment] 2020-01-08 20:23
thanks everybody for helping to analyze the error! It only occurred with local files AND when starting with a small file. I tested both, but not together. When I did, I could reproduce and then fix the issue.

**Comment by thn80** [comment] 2020-01-08 20:39
> 
> 
> I could reproduce and then fix the issue.

Wow, you are our hero :-)
When will be the next regular KP2A release in the Play store?

Thanks so much,

Thomas

**Comment by Lucky225** [comment] 2020-01-09 01:41
> thanks everybody for helping to analyze the error! It only occurred with local files AND when starting with a small file. I tested both, but not together. When I did, I could reproduce and then fix the issue.

Huh, I'm not so sure about that, I was using an existing database that's pretty extensive, 77kb in size fwiw

**Comment by Wiingy** [comment] 2020-02-02 03:58
Hi Philipp

I am having a very similar issue.  I unlock my database with a OTP.  I can open the database once.  Then it makes an error in the xml file down the bottom.

`		</EncryptedData>
	</EncryptedSecrets>
	<Counter>x</Counter>
	<OtpLength>x</OtpLength>
	<OtpsRequired>x</OtpsRequired>
	<LookAheadCount>x</LookAheadCount>
</OtpInfo>**unter>x</Counter>
	<OtpLength>x</OtpLength>
	<OtpsRequired>x</OtpsRequired>
	<LookAheadCount>x</LookAheadCount>
</OtpInfo>**`

The lines in bold should not be there.  My database is large at ~550kb

**Comment by Wiingy** [comment] 2020-02-02 10:36
Hi Philipp, must be something to do with the schema.  Comparing the new xml file created by KeePass to an older one.  The new one has 129 lines, while the older file only has 102 lines.  Older xml file works perfectly fine with the app.  The only difference I did differently this time was made the LookAheadCount=12, where it use to be 9 .  Don't know if this created the extra 17 lines.

**Comment by GeorgeHahn** [comment] 2020-02-22 23:15
I was seeing the same issue - this is fixed in 1.08-pre3 on the releases page. (/cc @Wiingy)

**Comment by MPatzek** [comment] 2022-01-11 07:13
So, I am using KeypassXC on PC (Windows and Linux) and keypass2android on my android phone. I use my yubikey 5 to unlock the database, which works flawlessly on the PC, but not on my Phone (neither USB nor NFC).
I tried to find these xml file mentioned here, but I am not able to do so.

Can someone help me out with this?
How can I fix this issue?

**Comment by GeorgeHahn** [comment] 2022-01-11 08:02
I don't think KXC uses an XML file; it stores the info it needs in the database file. I seem to remember the two not being compatible. It's been a couple of years since I did that research, so don't put too much stock in my memory. There should be some docs for that around though.

**Comment by techjunkie91** [comment] 2023-01-06 04:19
Sorry to drag up an old issue.

I am still having this issue today on version 1.09c-r0. I used to be able to do the workaround as @hermannx mentioned but that does not work anymore, I need to clear the app cache before the updated XML file can be selected.

I am using Samsung fold4 on Android 13 - my database is stored on OneDrive same issue if I use the Onedrive integration or sync locally to my phone and then use the local file picker.
