### ISSUE TITLE
Problems when autotyping through keyboard

### ISSUE THREAD

**Issue by XaeonBE** [PhilippC/keepass2android#199] opened 2018-01-08 12:02 UTC
When I let the keyboard autotype my password and I am in the username section and I press username on the keyboard to let it type the username in the field it enters the username en presses return making the login happen without entering password or giving me the chance to go to password field and entering it manually.

What could the cause of this be?

**Comment by PhilippC** [comment] 2018-01-08 12:12
please upgrade to beta channel, duplicate of #89

**Closed by PhilippC** 2018-01-08 12:12 UTC
