### ISSUE TITLE
It is not possible to open the database saved in PCloud

### ISSUE THREAD

**Issue by Richsor** [PhilippC/keepass2android#1475] opened 2020-11-21 19:17 UTC
It is not possible to open the database saved in PCloud, after entering the login and password, endless authorization ver.1.08b-r1

**Comment by PhilippC** [comment] 2020-11-21 19:23
duplicate of https://github.com/PhilippC/keepass2android/issues/1257

**Closed by PhilippC** 2020-11-21 19:23 UTC
