### ISSUE TITLE
Problem with Android 9 (Pie)

### ISSUE THREAD

**Issue by richardhaven** [PhilippC/keepass2android#510] opened 2018-08-17 14:49 UTC
The pop-up from the lock key from the KeePass2 keyboard does not show on the top of the display; the window is beneath the top-most window. I can see and click on the Cancel (or I would not have figured out what was happening)

Cheers

**Comment by PhilippC** [comment] 2018-08-18 05:00
duplicate of https://github.com/PhilippC/keepass2android/issues/377

**Closed by PhilippC** 2018-08-18 05:00 UTC
